### ISSUE TITLE
Tom40 not KW-0626 porin

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#1021]
fission yeast 
O13656  Probable mitochondrial import receptor subunit tom40 
is annotated by SPKW mapping to:

GO:0015288 - porin activity 
Definition: "Catalysis of the transfer of substances, sized less than 1000 Da, from one side of the membrane to the other. The transmembrane portions of porins consist exclusively of beta-strands which form a beta-barrel. They are found in the outer membranes of Gram-negative bacteria, mitochondria, plastids and possibly acid-fast Gram-positive bacteria." [GOC:mtg_transport, ISBN:0815340729, PMID:10839820, TC:1.B.1.-.-]

but this doesn't look correct for Tom complex...

val

Reported by: ValWood

Original Ticket: [geneontology/annotation-issues/1022](https://sourceforge.net/p/geneontology/annotation-issues/1022)

**Comment by mcourtot** [comment]
@ValWood: can you please check status?

**Comment by ValWood** [comment]
Still there.

Ion transport mapping looks dodgy too?

**Comment by mcourtot** [comment]
Action: remove KW-0626 from O13656 (both porin activity and pore complex come from the same KW)

**Comment by Antonialock** [comment]
hmm I'm not sure, a lot of papers call it a pore, and tomm40 is the pore-forming subunit? I agree the GO def of pore is much narrower
https://www.nature.com/articles/s41594-019-0339-2

Our high-resolution structures of the yeast TOM complex offer new mechanistic insights into how Tom40 mediates translocation of precursor proteins. While precursor polypeptides are first recognized by the cytosolic domains of Tom20 and Tom70, they need to be threaded into the pore of Tom40. Because there is no external energy input (that is, ATP or membrane potential) involved, this early step of translocation must be driven solely by the affinity of precursor proteins toward the pore interior. Our structural and functional analyses suggest that electrostatic interactions between the Tom40 pore and the precursor protein play an important role in this process (Fig. [6](https://www.nature.com/articles/s41594-019-0339-2#Fig6)). Particularly, in the cases of presequence-containing proteins, the positively charged presequence may be first attracted into the overall negatively charged Tom40 pore and then drawn toward the IMS by interaction with acidic patches on the IMS side. This mode of interaction may provide not only a driving force for presequence insertion into the pore but also an additional ‘filter’ for increased targeting specificity, as initial recognition of presequences by Tom20 is mediated by hydrophobic interactions[18](https://www.nature.com/articles/s41594-019-0339-2#ref-CR18). It remains to be elucidated how the presequence moves out from the pore interior into the IMS. This would likely require thermal (Brownian) motion of the precursor protein, as well as some movement of the C-terminal tail of Tom40. Once exposed in the IMS, the presequence might be captured by Tim50 of the TIM23 complex, which has been shown to interact with presequences[47](https://www.nature.com/articles/s41594-019-0339-2#ref-CR47), and would thus be prevented from backsliding.


from wikipedia 

TOMM40 is the channel-forming subunit of a [translocase](https://en.wikipedia.org/wiki/Translocase) of the mitochondrial outer membrane ([TOM](https://en.wikipedia.org/wiki/Outer_mitochondrial_membrane)) that is essential for protein transport into [mitochondria](https://en.wikipedia.org/wiki/Mitochondrion).[[](https://en.wikipedia.org/wiki/TOMM40#cite_note-pmid15644312-7)

According to [TCDB](https://en.wikipedia.org/wiki/TCDB), there are five evolutionarily independent [superfamilies](https://en.wikipedia.org/wiki/Protein_superfamily) of porins.

Porin Superfamily IV (Tim17/OEP16/PxMPL (TOP) Superfamily)

This superfamily includes protein that comprise pores in multicomponent protein translocases as follows: 3.A.8 - [Tim17 (P39515) Tim22 (Q12328) Tim23 (P32897)]; 1.B.69 - [PXMP4 (Q9Y6I8) PMP24 (A2R8R0)]; 3.D.9 - [NDH 21.3 kDa component (P25710)]

**Comment by ValWood** [comment]
You are right. It does seem to be a porin structurally. I have an annotation to ATPase which is clearly incorrect!

How to combine porin with protein transmembrane transporter?

**Comment by ValWood** [comment]
i.e do we need "protein porin activity"
under protein transmembrane transporter activity 
 and 
porin activity

At present I have 2 annotations to convey the same activity (pet hate)

**Comment by Antonialock** [comment]
I don't know! If it's passive diffusion it might be worth specifying that it is a "passive TM protein transporter"?

I think  people mean something very specific when they talk about "porins". I.e. even if tom40 forms a "pore", people might be surprised if it is associated with anything with "porin" in the name? 

The paper above states "A stable form of the complex is a dimer consisting of two copies each of Tom40, Tom22, Tom5, Tom6, and Tom7 arranged in twofold symmetry. "
whereas wikipedia page for "porin" states: "All porins form homotrimers in the outer membrane, meaning that three identical porin subunits associate together to form a porin super-structure with three channels."

itochondrial porin in yeast are POR1 and POR2.

**Comment by ValWood** [comment]
OK maybe we need to ask somebody who works on TOM

This paper 
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC155987/
describes TOM as a channel and "not a passive pore", but are porins passive (I have no idea)?

The acronym "TOM" stands for
 Translocase of the Outer Mitochondrial membrane 
So it is decribed variously as a channel, porin, translocase.....

**Comment by ValWood** [comment]
According to GO channels and porins are 'passive'
<img width="731" alt="Screenshot 2023-08-30 at 17 57 13" src="https://github.com/geneontology/go-annotation/assets/7359272/254b2ebe-fbd7-4acb-9b7e-a2a0d7f45735">

I just think we have too many terms here ;)

Probably this coud be closed. It isn't completely incorrect as a mapping, and the issue will go away if the terms are streamlined somewhat.
