### ISSUE TITLE
remove mapping for pom1 Q09690 to EC:2.7.12.1

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#1256]
I'm not sure where the best place is to report this.

Pom1 is picking up an EC mapping to 
protein serine/threonine/tyrosine kinase activity

but is a 
protein serine/threonine kinase activity

thanks

Val

Reported by: ValWood

Original Ticket: [geneontology/annotation-issues/1277](https://sourceforge.net/p/geneontology/annotation-issues/1277)

**Comment by hdrabkin** [comment]
Hi Val
So is Pom1 picking this up through a UniProt assignment of an incorrect EC id? 
I see EC:2.7.12.1 in the UniProt record. 
EC says that this is "This family of enzymes can phosphorylate both Ser/Thr and Tyr residues. "
So if this is wrong, the mapping at UniProt is incorrect. It should not have this EC associated with it.

**Comment by hdrabkin** [comment]
update: UniProt is investigating; awaiting feedback

**Comment by pgaudet** [comment]
Hi @hdrabkin Do you know who's investigating? just checking if this can be resolved.

**Comment by hdrabkin** [comment]
Nothing yet; I'll see if I can trace. This EC needs to be removed from this protein.
@ValWood , do you have a PMID to support that pom1 Q09690 is not protein serine/threonine/tyrosine kinase activity but is a protein serine/threonine kinase activity?

**Comment by hdrabkin** [comment]
Ah, on 12/8/2017, Sylvain said Marc (?) is looking into it (help #141904); not sure which Marc

**Comment by ValWood** [comment]
It doesn't look like a tyrosine kinase, and of 100 substrates none are tyrosine, but I'm checking with 3 labs who work on pom1... I guess it is possible but we don't know....

It is related to the dual specificity LAMMER kinase lkh1, which could be why it has the mapping.

**Comment by ValWood** [comment]
a quick response form one lab (James Moseley)

I am not aware of any data. However, the DYRK family of protein kinases (of which Pom1 is a member) autophosphorylate a tyrosine residue during protein folding. Once fully folded, they only phosphorylate serine and threonine. Hence the name DYRK for Dual-specificity tYrosine Regulated Kinase. 

I don’t think the related tyrosine on Pom1 has been shown to be phosphorylated, but I could be wrong. I also don’t know if anyone has looked for it (we haven’t). I suspect the automated mapping to tyrosine phosphorylation is due to this previous work on DYRK. It certainly seems like a possibility for Pom1.

so since it is possible, but not known I'll close this.....

**Comment by ValWood** [comment]
and another (Sophie Martin)

I second that! 
No direct evidence that I know of. 
Sophie

(I think ideally the mapping would be restricted to the known family members so I'll continue to filter locally at PomBase)

**Comment by hdrabkin** [comment]
I'll ping @sylvainpoux on this one to see where Marc is at with this. I could have been removed for all I know put we wouldn't see that until the next monthly release.

**Comment by hdrabkin** [comment]
On 1/29/18, 7:21 AM, "Marc.Feuermann@sib.swiss via RT" <sp-upd@expasy.org> wrote:

      Dear Harold,
      
      I've got finally some time to go through the big literature about the
      pom1 kinase and updated the corresponding UniProt entry. Pom1 is part of
      the DYRK family of kinases that have the dual activity, this is probably
      the reason of the mapping to EC:2.7.12.1
      
      After reading over 50 papers and finding several substrates, I did not
      not find a mention about of the specificity of the targeted residues. I
      might of course have missed something, so if I could know on which bases
      this suggestion was made it could be helpful to take a decision.
      
      Thanks a lot.
      
      Best regards,
      
      Marc.

**Comment by ValWood** [comment]
Hi Marc,

@marcfeuermann
Oh blow, You didn’t need to do that....I already read all of these papers ;)

 I closed the ticket 14 days ago because we  decided  that there is no evidence either way…it could be the case but we don’t know.
It seems that the typrosine Phosphorylation performed by the DYRK family is know for Lkh1, it autophosphorylates it's own tyrosine during folding, so its a bit of an edge case...

This is why it is better that we use git hub… but you ID is in the look up table now so I will be able to tag you easily!
