### ISSUE TITLE
UniProtKB-KW:KW-0866 mapping to GO:0000184 for 	Q9P805

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#1279]
Is this correct? This is decapping complex. 

http://www.uniprot.org/uniprot/Q9P805
https://www.pombase.org/spombe/result/SPBC3B9.21

I don't think its nonsense mediated-decay is it?

Reported by: ValWood

Original Ticket: [geneontology/annotation-issues/1302](https://sourceforge.net/p/geneontology/annotation-issues/1302)

**Comment by sylvainpoux** [comment]
Well, there is no evidence for S.pombe, but the role in Nonsense-mediated mRNA decay is reported in vertebrates (PubMed=12417715;, PubMed=10564284) and there is a paper in yeast (PubMed=10564284;)

I would keep it for the moment, except if the role in Nonsense-mediated mRNA decay was proven to be erroneous

**Comment by ValWood** [comment]
I thought decapping directly presceeded  NMD

And NMD is defined
Definition (GO:0070479 GONUTS page)
The chemical reactions and pathways resulting in the breakdown of the nuclear-transcribed mRNA transcript body of an mRNA in which an amino-acid codon has changed to a nonsense codon; occurs when the 5' end is not protected by a 5'-cap; degradation proceeds in the 5' to 3' direction. PMID:18554525

but maybe the decapping is itself part of the NMD rather than directly upstream......
