### ISSUE TITLE
getting PAINT annotations for things with taxon restrictions

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1320]
tions:

PomBase	SPCC5E4.04	cut1		GO:0005813	PAINT_REF:12792	IEA	PANTHER:PTN000300670	C	separase/separin	ptr4	protein	taxon:4896	20150313	GO_Central	

see
GOTAX:0000518	 GO:0005813	centrosome	never_in_taxon	4751	Fungi

**Comment by selewis** [comment]
The problem is that all the old GAF files used the previous taxonID of 28xxxxx rather than the revised taxonID (4751). So, the taxon check didn't spot the error (the taxon checker only has the current taxon, we might need to consider keeping previously used ones as well).

I've made a change to the touchup code that will revise all of the GAF files, -and- do the proper taxoncheck. However for this to take effect touchup needs to be run across all the existing GAFs. Waiting for the green light to run touchup.

**Comment by selewis** [comment]
See https://github.com/obophenotype/ncbitaxon/issues/4

**Comment by pgaudet** [comment]
Hi Suzi, 

'Preclude' as in forbid ? That wouldn't work, as most eukaryotes have centromeres. 

Thanks, Pascale

**Comment by mah11** [comment]
Just to preclude (swidt?) panic - pombe most assuredly does have centromeres. It does not have GO:0005813; that's *centrosome*.

I'm not sure what subset of eukaryotes have centrosomes, although I think Fungi generally don't.

**Comment by selewis** [comment]
Preclude the branch (fungi?) but the other branches it would be fine.
P.S. It looks like there may be a bunch of these corrections to make. Basically for every time the taxon checker fails, we need to determine whether it's the correct biology (yay) or the taxonchecker itself needs to be educated.
Question!:

There are two ways for providing the taxa to check to the taxonchecker
1. Use the taxon of the ancestral node (PANTHER provides these)
2. Use the collected taxa of the leaves.

(or possibly use both of these for a short while to really clean up the taxonchecker, because the true&false combinations are a dead giveaway that something is wrong). That's what was happening in this case. When checking GO:0005813 (centrosome) against Eukaryote it returned true, but when using the leave's for the taxa list, then it returned false for pombe. true&false.

**Comment by cmungall** [comment]
> When checking GO:0005813 (centrosome) against Eukaryote it returned true, but when using the leave's for the taxa list, then it returned false for pombe. true&false.

This is the intended behavior, centrosome is a valid structure for Eukaryotes in general (but this can be overridden if we know more about the specific lineage; e.g. pombe where it is lost)

**Comment by selewis** [comment]
Why was this decided upon? This effectively precludes being able to ask whether a given GO term is valid for -all- members of a given higher level taxonomic classification.
In what possible situation is it useful to be able to ask "Can any members of XXX taxon have this GO term YYY applied?". Are there any extant use cases (that is, actual pieces of software) that utilize this type of query? The only piece of software I can imagine using the taxon checker is for annotation, and in that case it would need to use the -all- members type of query.

**Comment by cmungall** [comment]
> Why was this decided upon?

It's been this way since the Deegan et al paper. But it was not so much decided upon, more the consequence of the semantics of the two relations being used: never-in-taxon and only-in-taxon. In the initial paper by Waclaw he defined an additional relation for found-in-all-members-of, but in practice this is very hard to apply at higher levels because loss is so common, and we are rarely confident enough to make this claim.

> This effectively precludes being able to ask whether a given GO term is valid for -all- members of a given higher level taxonomic classification

Yes, this is a consequence of the two relations currently in use.

It doesn't preclude asking a closed-world question: are there any members of this taxon for which it is known that S is invalid (which would be implemented by iteration, either client or served side)? This is a closed-world question because the answer is not guaranteed complete. For example, if you do this query now with 'hindlimb morphogenesis' you will get the answer that there are no known cases of this being absent in vertebrates. But this is because GO is incomplete when it comes to annotating loss (because GO isn't funded for snakes and whales)

> In what possible situation is it useful to be able to ask "Can any members of XXX taxon have this GO term YYY applied?".

Think of it as: is this entity valid for this taxa? The answers are 'no' or 'this is not a violation as far as I am aware' 

This is useful because if the answer is no you can immediately rule out the entity for that taxon or any member of the taxon. 

In PAINT terms, you can tentatively safely assign the term to a PTN with that taxon, saying that this ancestral gene had this function. This is valid, or at least not provably invalid.

It does not guarantee validity for sub-lineages.

So you could annotate centrosome at the base of eukaryotes (or possibly some sub-lineage encompassing the opsithokontes and dicty), on the tentative understanding it evolved there. However, if you try and propagate down to fungi, the ontology tells you this is invalid, reflecting the actual biological loss that happened presumably somewhere near or around the ur-fungus.

> Are there any extant use cases (that is, actual pieces of software) that utilize this type of query? The only piece of software I can imagine using the taxon checker is for annotation, and in that case it would need to use the -all- members type of query.

The original main use case was primarily species-level GAF validation, and secondarily for ontology consistency.

**Comment by selewis** [comment]
Being done by iteration, implemented in PAINTv2.09 (actually in Touchup1.09, which PAINT2 relies upon)
