### ISSUE TITLE
UniProtKB:P15442, UniProtKB:P33892 

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-annotation#1346]
Pombe gcn1 and gcn2 (UniProtKB:P15442, UniProtKB:P33892) are annotated to
positive regulation of cell death with a uniprotKB reference (?), could this please be removed.

Also remove 'positive regulation of translational initiation in response to starvation' - I think these kinases are involved in negatively regulating translational initiation in response to stresses.

The ISSs to 'response to X substance' terms should probably also be removed as different organisms may respond differently to the same stresses (I don't think you can infer this from orthology?).

**Comment by ValWood** [comment]
and yih1 	O13997
negative regulation of cell death	ISS	UniProtKB:O55091	GO_REF:0000024

**Comment by mcourtot** [comment]
Could you please let me know where exactly you see these annotations, and what you mean by "UniProtKB reference" - is this the assigned_by, WITH string or else? 

I checked the first annotation and it is not in QuickGO, https://www.ebi.ac.uk/QuickGO/GProtein?ac=P33892. Our internal audit tables also don't see it.

Thanks!

**Comment by Antonialock** [comment]
Val could you have a look? I couldn't see them in our files so I assumed they're from an external source.

**Comment by ValWood** [comment]
weird, we presumed they were coming in from the GOA file as they are't in our annotation either. If they aren't there, they are clearly removed from wherever they were coming from, so I guess we can close this.

**Comment by ValWood** [comment]
Actually I see it in the table (6th row, source UniProt)
val

**Comment by ValWood** [comment]
Oh that is cerevisiae...but its  a suspect GO annotation, its a phenotype really.....I doubt SGD would make that annotation. I'll check the pombe entries...

**Comment by mcourtot** [comment]
Hi Val, could you please raise the dispute from P2GO? Those annotations seem to come from SIB.

**Comment by ValWood** [comment]
yep its here
http://www.uniprot.org/uniprot/Q10105

I would remove the original annotation  (SGD) and the ISS derived from it... for all...

I think its based on some sort of cell survival assay:
overexpression of IMPACT in yeast cells inhibited growth under all stress conditions that require GCN2 and GCN1 for cell survival, 
Using these criteria to annotate to "cell death" every yeast gene could be annotated to this term eventually.

The Uniprot curators probably  need  to be alerted to the appropriate use of the term (maybe a comment could be added..There needs to be some sort of mechanism for cell death, like programmed cell death or apoptosis, not just cell 'survival').

**Comment by ValWood** [comment]
cell death already has this comment:

This term should not be used for direct annotation. The only exception should be when experimental data (e.g., staining with trypan blue or propidium iodide) show that cell death has occurred, but fail to provide details on death modality (accidental versus programmed). When information is provided on the cell death mechanism, annotations should be made to the appropriate descendant of 'cell death' (such as, but not limited to, GO:0097300 'programmed necrotic cell death' or GO:0006915 'apoptotic process'). Also, if experimental data suggest that a gene product influences cell death indirectly, rather than being involved in the death process directly, consider annotating to a 'regulation' term.

I think the same comment should be added to the positive and negative regulation terms. It shouldn't be necessary to use them if it really is a 'cell death' mechanism.

**Comment by ValWood** [comment]
will do...

**Comment by ValWood** [comment]
I raised the dispute.

**Comment by mcourtot** [comment]
Closing this issue as the ticket has been raised in P2GO.
