### ISSUE TITLE
Ortholog relevance displayed on CGD/AspGD pages

### ISSUE THREAD

**Issue by dianeoinglis** [geneontology/go-annotation#1380]
Hello Editors, 

The IEA annotations from different fungal species are presented in a context on the CGD or AspGD gene/protein pages that is not communicated in the annotations as they are presented in UniProtKB. The impact is mostly on BP that varies widely among fungi with many processes being mutually exclusive between some fungal species. In the absence of the hierarchy of relevance that is shown on CGD and AspGD web pages, annotations made from Neurospora crassa to Candida glabrata are confusing as the relevance information is missing. The annotations to BP in other fungi are useful even if the process/function is not present in the species but in fungi, the combinations and differences are so numerous that it is hard to know if the annotation is to a trait the species possesses or if the annotation refers to a process in another fungal species that is not present in the species of the protein of interest.

Fungal species are likely the most complicated of any group of species for the combinations and restrictions for processes.

The text of comments I made to Chris Mungall are pasted here:
"I realized where the strange choices for GO transfer from questionable fungal species are incorporated by CGD. The orthologs are highly context dependent on the CGD website. The most sensible organisms are grouped together and species that are more of a stretch are also grouped by lesser relevance. This is clear on the CGD webpages but not distinguished in the download.  "  An example might be CPH1. There are "Orthologs in non--CGD species" and "best-hits in non-CGD species" that are set apart on the CGD webpages but probably not obvious in the download. That explains why some of the GO terms are being transferred have had me scratching my head as they strike me as odd without explanation that these are bottom of the barrel to provide any information at all for proteins that lack GO information from more relevant orthologs. I thought it was worth explaining how the orthologs from a strictly filamentous fungus like Neurospora appear odd when applied to an asexual, strict yeast species, like Candida glabrata, in the absence of context.  http://www.candidagenome.org/cgi-bin/locus.pl?locus=cph1&organism=C_albicans_SC5314"

There are other fungal annotations issues for separate tickets. I also have suggestions to make that may improve clarity in some areas.

Let me know if further clarification is needed.

Diane

**Comment by ValWood** [comment]
Hi Diane,

Transfer of annotations between fungal species is going to create problems.  At present @tonysawford ebi  is in the process of replacing the pipelines.

I *think* the procedure is to transfer annotation between !:1 orthologs only. Inevitably this will   create some problematic annotations for some processes, particularly for  terms related to transcription and signalling processes.

Probably the best way to deal with these is to  begin by reporting the problems you notice on a case by case basis becausse the solution will depend on the type of problem.

The first approach might be to add taxon restrictions where processes do not apply. For example, you don't really want annotations to "budding'. These are easy.

Secondly, we can hopefully identify terms which are never appropriate for transfer.

Thirdly, for fission yeast,  we are unlikely to use no IES's  transferred from SGD or  CGD by this automated pipeline, because hopefully if  the annotations were valid, we would have made them. However, we will assess the unique annotations first to provide feedback on the pipeline, and see what we might be missing.

These automated annotation will be more useful for the 500-1000 species with  no manual annotation.

I looked at the link you provided above.  Which annotation was problematic for you?
I see:
 sequence-specific DNA binding (IEA with S. cerevisiae: STE12)
 invasive growth in response to glucose limitation (IEA with S. cerevisiae: STE12)
negative regulation of transcription from RNA polymerase II promoter by pheromones (IEA with S. cerevisiae: STE12)

CGD have already made:
 positive regulation of transcription from RNA polymerase II promoter by pheromones (IGI with S. cerevisiae: STE12)
presumably from a complementation experiment? (this is annotated as being involved in both positive and negative regulation at SGD, which seems slightly strange but based on this, these annotations seem OK).

I'm guessing that you are questioning:
 invasive growth in response to glucose limitation (IEA with S. cerevisiae: STE12)
This might be an example of   a term we would never want to transfer  because it is so context dependent (type 2 above).

Do you have  any more specific examples?
If  you can add the terms to this ticket,  hopefully the pipelines can be improved

Tagging @mcourtot  because ages ago I said I would find examples of this.

**Comment by pgaudet** [comment]
Hi @dianeoinglis @cmungall 
What is the next step for this ? 
Who can we assign this ticket to ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
Pinging  @dianeoinglis  @cmungall again - if there is no answer I'll close this. 

Thanks, Pascale

**Comment by dianeoinglis** [comment]
In .my opinoon, the varoety of matches from strong to very little homppogy in the protein sets make the transfer of BP in every pairwise direction pf questiomable value. These data we're designed for CGD and AspGD wenpages that have a lot of contextual infpmation. I would m not display the transferred BP in if I had the godly powers.

Diane

**Comment by ValWood** [comment]
These might be the datasets that Fungidb are maintaining ?  In which case the cleanup is in progress. @vanaukenk Achchuthan in which case they will be reviewed shortly.

**Comment by suzialeksander** [comment]
@Achchuthan @marekskrzypek this seems to be very relevant to the call today, just mentioning you here so you see this ticket.

**Comment by suzialeksander** [comment]
@jlewsmith I'm assuming this is now being reported as specific issues on each incorrect IEA, so I'm closing this.  Please reopen/open a new ticket if there are still problems in this ticket I overlooked.
