### ISSUE TITLE
UniProtKB - P53384 cellular component annotation

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-annotation#1382]
human NUBP1 is annotated to extracellular exosome from PMID:23376485
http://www.sciencedirect.com/science/article/pii/S1874391913000407

but I can't see this gene mentioned in this paper? Could you please take a look

**Comment by Antonialock** [comment]
Also ALOT of IEAs have been created based on this annotation, these should be removed I guess?

**Comment by ValWood** [comment]
They  disappear eventually once the primary annotation is removed....

**Comment by Antonialock** [comment]
I'm not sure who to tag in this? Thanks

**Comment by ValWood** [comment]
@ggeorghiou can you assign to appropriate person?
cheers
val

**Comment by ggeorghiou** [comment]
Hi Antonia, 

The annotation is correct. The data for many of these annotations from this paper is in the supplementary tables. We flagged this paper a while ago as high-throughput and put the correct HTP evidence code with it to make sure that the annotations from this paper were to be taken with some consideration. 

Best,

George

**Comment by Antonialock** [comment]
Thanks George, the authors set a cut-off for what they believed were 'real hits" to keep false-positives to a minimum

"1234 proteins were identified on the basis of at least two unique peptides (Table 1; Supplementary Tables S1 and S2 in the Supporting information). In addition, 673 single-hit proteins were identified, bringing the total number of identified proteins to 1907 (Supplementary Table S3 in the Supporting information). However, due to the lower reliability of identifications based on just one unique peptide, single-hit proteins were not considered for further data analyses."

NUBP1 is one of the 673 single-hits that they discarded. The "hits" are listed in table 1, main paper

**Comment by ValWood** [comment]
@hattrill

**Comment by hattrill** [comment]
In terms of QC on exosome annotations, I think the exosome annotations are going to be quite often associated with things that we don't expect. I guess that's what happens when you do mass spec of wee! It is a field of research that I have avoided, so I can't possibly say what we (or should that be wee) expect to see.

**Comment by Antonialock** [comment]
I thought 2 seemed low too @ValWood :-) Better than 1 in any case...

**Comment by ggeorghiou** [comment]
Hi all,

After much careful thought and reflection on the fact that someone looked at exosomes in urine, and seeing as this paper has been flagged in our database as not suitable for curation, I think the best solution is to delete these annotations. There are annotations from other sources for the majority of these proteins to extracellular exosome so we will not be losing much by getting rid of them. In order to save myself from RSI, Tony will go ahead and delete these in the morning. 

Best,

George

**Comment by Antonialock** [comment]
peerfect

**Comment by hattrill** [comment]
Thanks for reviewing them! 
I hope that you told Tony to "flush 'em" - it would seem appropriate given the source!

**Comment by ggeorghiou** [comment]
Tony has sent them to the great cesspit in the sky.
