### ISSUE TITLE
presentation of the Term matrix in AmiGO 2.4

### ISSUE THREAD

**Issue by mcourtot** [geneontology/go-annotation#1388]
AI from Geneva meeting

@ValWood to give presentation of the Term matrix in AmiGO 2.4

**Comment by ValWood** [comment]
Blimey, I think we all need a way to be reminded which tickets are assigned to us!

I know @hdrabkin  would find this useful too :) because all my e-mails to him go to spam....

Can this be done in some  sort of "git hub" management mode (i.e select all tickets and send a message saying "you are  the assignee of this ticket, please check if it can be closed").... A monthly alert......I will never look otherwise....  I think this would get  a lot of GitHub tickets  "unstuck"
