### ISSUE TITLE
GOC to decide what is HTP data 

### ISSUE THREAD

**Issue by mcourtot** [geneontology/go-annotation#1390]
[moved from https://github.com/geneontology/go-ontology/issues/12412]

AI from Geneva GOC meeting
https://docs.google.com/document/d/12CDf4s8YsylPMNHM3UuPis9NyVQ9WFpBpNYTFYAH7kc/edit

@bmeldal @selewis @cmungall @tonysawfordebi

Discussion at managers call, http://wiki.geneontology.org/index.php/Manager_Call_2016-04-20: make sure we have an ECO to capture this

Discussion at annotation call, http://wiki.geneontology.org/index.php/Annotation_Conf._Call_2016-04-26:
- if experiment is hypothesis driven, this is not considered HTP (even if the dataset is large) as better quality
- if experiment is non-hypothesis driven, exploratory: HTP

**Comment by pgaudet** [comment]
Resolved, see https://docs.google.com/document/d/1ScIeclAzUXMe-tU6n0lVfsSwMHpOeNb7uK8On9-iKXc/edit

For reference, in case that Google doc gets deprecated, GO defines HTP data as follows: 
What qualifies as HTP data?

As HTP datasets are generated from the scaling of normal experimental techniques, it is difficult to create a definition that exactly captures what is ‘HTP’. It is more useful to highlight certain characteristics that are often associated with HTP papers to help guide the curator’s decision as to whether it should be classed as HTP for the purposes of annotation.

**Characteristics of HTP papers:**
* Apply the same workflow to a large number genes/gene products.
* Generate data in an automated or semi-automated fashion.
* Address open-ended rather than hypothesis-driven questions.
* Generate dataset(s) (usually presented in tabular form).
* Datasets contain ‘false positives’.
* Ascribe the same property to all gene products that fall within a given measurement range.
