### ISSUE TITLE
 EC to GO mapping query

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1410]
In pombe SPBC337.16 	O74827 has a mapping to
GO:0004608	phosphatidylethanolamine N-methyltransferase activity	IEA	EC:2.1.1.17

This  seems to  be
GO:0080101	phosphatidyl-N-dimethylethanolamine N-methyltransferase activity
and	
GO:0000773	phosphatidyl-N-methylethanolamine N-methyltransferase activity	

Do you agree?
If so can the mapping be deleted

![phospholipid_biosynthesis](https://cloud.githubusercontent.com/assets/7359272/16416712/7b7e9772-3d3b-11e6-8a2e-00656cce5df3.jpg)

**Comment by ValWood** [comment]
My term selection also agrees with SGD manual annotation
http://www.yeastgenome.org/locus/YJR073C/overview#go

**Comment by mah11** [comment]
I think GO:0004608 - EC:2.1.1.17 might OK.

What confuses me is that MetaCyc has both reactions, GO:0000773 and GO:0080101, associated with EC:2.1.1.71, same as GO, but EC's record only has one (corresponding to GO:0000773).

**Comment by ValWood** [comment]
From the PomBAse trracker:

There are 3 reactions
1 PE -> PMME
2 PMME -> PDME
3. PDME-> PC

and these are
1. GO:0004608 phosphatidylethanolamine N-methyltransferase activity (Cho2)
2. GO:0000773 phosphatidyl-N-methylethanolamine N-methyltransferase activity (Cho1)
3. GO:0080101 phosphatidyl-N-dimethylethanolamine N-methyltransferase activity (Cho1)

respectively ?

**Comment by pedruzzi** [comment]
Hi Val,
2.1.1.17 is your reaction 1
2.1.1.71 are reactions 2 and 3 (reaction 3 being hidden in the comments of 2.1.1.71 in EC)
and the GO term mappings 2.1.1.17 -> GO:0004608 and 2.1.1.71 -> GO:0000773 & GO:0080101 are therefore correct as well.

the problem is with the protein to EC mapping:
- In mammals and plants, a single enzyme PEMT catalyzes all three steps, and has therefore both ECs assigned.
- In fungi, the ortholog of PEMT (S.p. cho1, S.c. OPI3/PEM2) catalyzes the steps 2 and 3, and a new enzyme not present in mammalia catalyzes step 1 (S.p. cho2, S.c. CHO2).
Detailed analyses in yeast have however shown that OPI3 can and does still catalyze reaction 1 in the absence of CHO2 (and in analogy to the mammalian/plant enzyme) (PuMed:2684666 and PubMed:22001639).

This raises the question of course at which point the presence of a catalytic activity in a structural enzyme warrants the assignment of an EC and its corresponding reaction. I'll have this discussed with our enzyme specialists here at UniProt.
I guess the O74827 to GO:0004608 mapping in pombe has been done in analogy to yeast, but since no such detailed analyses have been done in S.pombe, I can have this mapping removed.
Best
-ivo

**Comment by ValWood** [comment]
Hi Ivo,

Phew! Yes I see. I agree with all this, and can see how the EC was added to pombe.
Although If I remember correctly, the paper above  shows genetic analysis which indicates that in fission yeast cho1  doesn't substitute for cho2 (see legend on pathway above) so I think it might be best to remove?

Or, if this is difficult, I can just add a NOT annotation at PomBase.

**Comment by pedruzzi** [comment]
I'll have the EC and GO term removed from pombe, yes, and updated the HAMAP rule to remove it from other fungi as well unless proven differently. It'll just stay in cerevisiae for now.
This should be public in UniProt release 2016_09

**Comment by ValWood** [comment]
Thanks Ivo!
