### ISSUE TITLE
HAMAP:MF_03209 mapping 	O14111

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1415]
HAMAP:MF_03209 query mapping to "protein autoprocessing"
this might be correct but  if so, I can’t figure out how.....
This is an enzyme  "Catalysis of the reaction: H(+) + phosphatidyl-L-serine = CO(2) + phosphatidylethanolamine., As far as I know it has no other activity. I can't reconcile this activity  with a processing role

protein processing
Any protein maturation process achieved by the cleavage of a peptide bond or bonds within a protein. Protein maturation is the process leading to the attainment of the full functional capacity of a protein.

**Comment by ValWood** [comment]
O14111 =SPAC31G5.15,psd3

**Comment by pedruzzi** [comment]
This is annotated in analogy to the E.coli (P0A8K1) and Plasmodium knowlesi (B3L2V1) enzymes, where it has been consistently shown how this enzyme is produced by autocatalytic cleavage from an inactive precursor. There is a PTM/processing comment in all family members (trying) to explain how this is done. (Very interesting case, as the amino acid at the cleavage site become the active site residue of the active enzyme. And because of this I think it valid that this processing is conserved in all family members to generate the active site.
Trying to add a figure from PubMed:25724650 (P.knowlesi)
![psd2](https://cloud.githubusercontent.com/assets/17901419/16732516/e894231c-477d-11e6-8cb1-08bc46115ed0.jpg)

**Comment by ValWood** [comment]
Ah, got it. I was trying to reconcile this with the  decarboxylase activity. In this case it is also a protease? I'll add this IC from the GO:0016540 
Thanks!

Val

**Comment by pedruzzi** [comment]
Yes, it uses a serine protease mechanism to catalyze the cleavage and produce the pyruvoyl prosthetic group. However, since it acts only on itself and not on any other substrate I think it would be going too far to annotate a protease activity on this protein, it's main physiological function still being the decarboxylase activity. The protease activity is just a means of generating the active enzyme, and GO:0016540 perfectly captures this. But this is just my personal opinion :-)

**Comment by ValWood** [comment]
Yes I think you are right. It is quite clear what it means, nothing else is required.
Val
