### ISSUE TITLE
P23258 annotation  to GO:0000086

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1454]
@deustp01 

I'm transferring this one from the Protein2GO tracker, as this doesn't appear to be the best place to report these.

original ticket
"Hi, I don't think gamma tubulin has a role in G2/M transition. It seems that the Reactome pathway this is mapped from, is happening at the "same time' as the G2/M transition? but isn't the G2/2M transition (a regulatory switch converging on CDK1)"

Val

**Comment by ValWood** [comment]
Hi Peter,
@deustp01 
and another one. Hopefully this one is easier....
I don't think this is involved in G2/M  transition as this is defined as the signalling pathway converging on Cdc2...

**Comment by deustp01** [comment]
We have P23258 linked to GO:0000086 G2/M transition of mitotic cell cycle because we have the protein annotated as a component of the centrosome, which in turn plays a role in centrosome maturation, which in turn eventually has something to do with cell cycle progression. We now have a strategy in place to break this too-extensive downward propagation of GO terms from a process to entities and events that are many steps removed but implementing it requires manual re-curation of the offending items as they are noticed, so it's slow.

Does this also account for the "easier" one you just noted?

Thanks.

Peter

**Comment by ValWood** [comment]
I think tubulin is  "post" G2/M transition (if the centrosome has the same role in  cell cycle progression as the spindle pole body in yeast). Tubulin has an indirect role in the transition because the spindle checkpoint originates from here, and monitors things spindle wise. However the spindle checkpoint  inhibits metaphase/anaphase not G2/M (which is more about DNA integrity and other things). So I still think that  G2/M is incorrect, but metaphase/anaphase is too downstream (tubulin isn't part of the transition per.se. but if there are defects in the processes it is involved in, they will be detected (in some not completely known way, but likely a modification event) and the spindle checkpoint will be activated) .

**Comment by deustp01** [comment]
This one goes onto the curators' to-do list for checking and revision. Thanks.

**Comment by ValWood** [comment]
Still present.
