### ISSUE TITLE
Incorporate expanded list of GP-GO term relations into annotation tools and files

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go-annotation#1468]
To enable more expressive annotation between gene products and GO terms, and to allow for faithful representation of LEGO annotations in a GAF or GPAD output, we will add additional GP-GO term relations to annotation tools and files.

**Comment by ValWood** [comment]
It is on my to do list to update Canto with the relations which are allowed in LEGO. Can the list be posted here.  PomBase have already started to use them like this:

![directly inhibits](https://cloud.githubusercontent.com/assets/7359272/20445720/2a28ab16-adce-11e6-990a-1538912110a0.jpg)

So we  we don't need to say

![instead of](https://cloud.githubusercontent.com/assets/7359272/20445770/5a9dcdb2-adce-11e6-898c-40749bb749b6.jpg)

**Comment by ValWood** [comment]
srw1 is a ubiquitin ligase activator
clp1 is the phophastase which is antagonistic to cdc2 during mitotic exit

so the older statements can be inferred from the more biologically  informative replacement annotations.

I will upload   my slides to the repository shortly...its on my list...

**Comment by dosumis** [comment]
Hi Val,

These look nice and clear.  Keen to discuss further, but are distinct use case from the new GP-GO relations:

![image](https://cloud.githubusercontent.com/assets/112839/20466735/558e16d0-af70-11e6-9159-9e08af9d7cd9.png)

**Comment by ValWood** [comment]
yes I put this in the wrong ticket....
I thought these relations were available for extensions....

I'll migate my comments to the other ticket.
v

**Comment by ValWood** [comment]
migrated my comment to 
https://github.com/geneontology/annotation_extensions/issues/70

**Comment by ukemi** [comment]
Seems like this ticket is resolved?

**Comment by ValWood** [comment]
Out of date? 
Came up when I was searching for something else...
