### ISSUE TITLE
Examples for New qualifier to capture roles in both a general and a specific process

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#1531]
I just came across another issue that we might be able to address with qualifiers, ie when it makes sense to annotate to a term and to its parent. One example is Q9H773, a dCTP pyrophosphatase. Hydrolyzes deoxynucleoside triphosphates (dNTPs) to the corresponding nucleoside monophosphates but has a strong preference for modified dCTP.
The curator annotated to GO:0047840 dCTP diphosphatase activity and also to the parent
GO:0047429 nucleoside-triphosphate diphosphatase activity
The meaning of the annotation to the parent here is that it has activity on several of the children, as opposed to 'we don't know which of the children'.

An alternative representation would be to have some 'main substrate' qualifier for the dCTP diphosphatase activity and annotate other siblings without that qualifier (or with a 'weak activity/weak affinity qualifier).

Note that this also applies to dual roles in 'process x' and 'regulation of process x'
Any feedback on these suggestions would be more than welcome.

Thanks, Pascale

**Comment by ValWood** [comment]
Hmm, I prefer  annotating to the independently shown substrates with a qualifier.
We used to do this using "major" or "minor" at PomBase but I think we dropped it because it was not used very much.
We also have a way to capture kcat, we don't use this often, but this info would allow us to make this deduction.

The problem  with the first option is how would you know the meaning was "all substrates below this term" as opposed to  "we do not know the specificity from this experiment".

**Comment by hdrabkin** [comment]
If the annotation were to the parent (less specific) term, it doesn't mean (and everything below it). If it were to a child term, it could propagate up.

**Comment by suzialeksander** [comment]
has_input solves this
