### ISSUE TITLE
InterPro:	IPR000544

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1543]
Is mapped to

GO:0016415octanoyltransferase activity
"Catalysis of the transfer of an octanoyl (CH3-[CH2]6-CO-) group to an acceptor molecule
and
 GO:0009107 - lipoate biosynthetic process 

but should it be
	lipoyl(octanoyl) transferase activity
Catalysis of the reaction: octanoyl-[acyl-carrier protein] + protein = protein N6-(octanoyl)lysine + acyl-carrier protein."

and
GO:0009249 - protein lipoylation

(I'm not sure if GO:0016415 octanoyltransferase activity should be a descendant of
GO:0033819 lipoyl(octanoyl) transferase activity but it isn't at present)

**Comment by asangrador** [comment]
Thanks Val, I have made these changes.

Amaia

**Comment by ValWood** [comment]
I'm wondering if the function was correct.
I can't figure out if IipB/2 is  catalysing attachment to the carrier or  to the protein

**Comment by asangrador** [comment]
Having a deeper look at this,  LipB  transfers octanoyl from the carrier to the protein: " LipB (octanoyl-ACP: protein N-octanoyl-transferase) transfers the endogenously produced octanoyl moieties from octanoyl-ACP to lipoyl domain..." PMID:25611823 and is involved in lipoic acid synthesis (with LipA ) .
So lipoyl(octanoyl) transferase activity should be fine, but the BP should be  lipoate biosynthetic process better than protein lipoylation (because it does not add  a lipoyl group but a octanoyl  group).

**Comment by ValWood** [comment]
Thanks for digging. will fix  ours...probably both processes re fine, difficult to know where these begin and end until we document them precisely in GO
