### ISSUE TITLE
MGI gaf has only 2537 genes

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-annotation#1554]
```
$ curl -L http://www.informatics.jax.org/downloads/reports/gene_association.mgi.gz | gzip -dc | egrep '\tgene\t' | cut -f2 | sort -u | wc
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 4498k  100 4498k    0     0  2872k      0  0:00:01  0:00:01 --:--:-- 2876k
    2537    2537   29920
```

Looks like many genes are incorrectly typed as proteins:

```
$ curl -L http://www.informatics.jax.org/downloads/reports/gene_association.mgi.gz | gzip -dc | grep Arpc1a | cut -f1,2,3,12
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 4498k  100 4498k    0     0  3411k      0  0:00:01  0:00:01 --:--:-- 3418k
MGI     MGI:1928896     Arpc1a  protein
MGI     MGI:1928896     Arpc1a  protein
MGI     MGI:1928896     Arpc1a  protein
MGI     MGI:1928896     Arpc1a  protein
MGI     MGI:1928896     Arpc1a  protein
MGI     MGI:1928896     Arpc1a  protein
MGI     MGI:1928896     Arpc1a  protein
MGI     MGI:1928896     Arpc1a  protein
MGI     MGI:1928896     Arpc1a  protein
```

**Comment by hdrabkin** [comment]
!!!!  Let me check new one

**Comment by hdrabkin** [comment]
I checked the previous gaf; appears to be the same. Not sure how long this has been happening

**Comment by hdrabkin** [comment]
Looking as far back as  Thu Mar 27 2014 column 12 has protein because the gene object codes for a protein. This was decided on may GOC meetings ago. 
Column 12:
A description of the type of gene product being annotated. If a gene product form ID (column 17) is supplied, the DB object type will refer to that entity; if no gene product form ID is present, it will refer to the entity that the DB object symbol (column 2) is believed to produce and which actively carries out the function or localization described. one of the following: protein_complex; protein; transcript; ncRNA; rRNA; tRNA; snRNA; snoRNA; any subtype of ncRNA in the Sequence Ontology.

**Comment by cmungall** [comment]
> This was decided on may GOC meetings ago.

I don't think so

> Note "gene" for column 12 is not a choice

Not sure what you mean

**Comment by hdrabkin** [comment]
I specifically remember that the argument was that if it's a protein-coding gene then we are annotating the protein product. If it's an RNA-coding gene, then the entry would be a transcript, or ncRNA, tRNA, etc.  
So the only thing about the documentation that is confusing is that if there is NO entry in column 17; remember, we altered our scripts to just load whatever we had from our db referring to column 17, but not then default to a UniProt, then if no UniProt, whatever our database considered the representative protein id (remember we use VEGA and Ensembl ids by default, and had to construct a workaround to force a UniProt ID to be used if there was one. But that resulted in problems at the GOC end. But I suppose if the reference proteome project is successful, we could use those. 

And the choices as listed do not include "gene" since the entry is "the entity that the DB object symbol (column 2) is believed to produce and which actively carries out the function or localization described.

(and I meant MANY GOC meetings ago; not one in May).

**Comment by ukemi** [comment]
I think the point of confusion is here:
http://www.geneontology.org/page/go-annotation-file-format-20
See the documentation for column 12 and for column 17. I believe what @hdrabkin is saying is that our GAF conforms to this spec.

**Comment by hdrabkin** [comment]
I dug out a file I uploaded for 2009 GO meeting (http://wiki.geneontology.org/index.php/Oregon_GO_Consortium_Meeting#Action_Items) 
 but it conflicts with the documentation:
"When column 17 is filled with a protein id, the value in column 12 must be “protein”.
Column 17 may be left blank. If left blank, the value in column 12 is “gene"
From that meeting's official documentation for column 16 and 17
http://wiki.geneontology.org/index.php/GAF_Col17_GeneProducts#What_goes_in_col_12.3F
What goes in col 12?
.......The type of the entity in col 17
What goes in col 12 if col 17 is blank?
 .......gene_product

SO, I suppose we could put "gene_product" in all columns except where col 17 is filled in.

**Comment by cmungall** [comment]
OK, I stand corrected. That was a bad choice on our part. I will look at how consistently this is implemented

**Comment by cmungall** [comment]
@hdrabkin - MGI is still implementing this inconsistently

In your GAFs you have:

 * 7793    gene
 * 359276  protein

According to the rules you present above, MGI should only use 'protein' when something is in c17. In fact this is not what you're doing.

e.g

```
MGI     MGI:98297       Shh             GO:0071285      MGI:MGI:3703195|PMID:17284610   IDA             P       sonic hedgehog  Hhg1|Hx|Hxl3|M100081    protein taxon:10090     20100720        MGI             
MGI     MGI:98297       Shh             GO:0071542      MGI:MGI:5700306|PMID:16243425   TAS             P       sonic hedgehog  Hhg1|Hx|Hxl3|M100081    protein taxon:10090     20160105        ParkinsonsUK-UCL                
MGI     MGI:98297       Shh             GO:0072136      MGI:MGI:2388350|PMID:12399320   IMP             P       sonic hedgehog  Hhg1|Hx|Hxl3|M100081    protein taxon:10090     20110203        UniProt         
MGI     MGI:98297       Shh             GO:0090090      MGI:MGI:3703195|PMID:17284610   IMP             P       sonic hedgehog  Hhg1|Hx|Hxl3|M100081    protein taxon:10090     20100720        MGI     regulates_o_occurs_in(EMAPA:18272)       
```

**Comment by hdrabkin** [comment]
This was because we had been auto populating C17 if we had no isoform data, but were told that the entires were causing problems (not all of our genes had a UniProt ids as the representative protein; so we stopped the auto generation. 
However, the documentation is not clear because it suggests that we could use protein even if C17 was unpopulated if the assumption was that it was a protein-coding gene 
Before I approach our software team, I need to know what exactly are the rules. If the documentation is incorrect, it needs to be changed. 
If no C17 is it gene_product or gene.

**Comment by hdrabkin** [comment]
The easiest thing (and most likely to get done sooner) is for us to just impliment column 12 = gene for all entries in our gaf.

**Comment by hdrabkin** [comment]
At the moment, c12 should be being classified accordingly
protein coding gene (22,927) (we class these as protein for the c12 gaf
non-coding RNA gene (24,682) (we class them as transcript I believe for the gaf

**Comment by hdrabkin** [comment]
I think what is in column 12 IS still consistent with the documentation on the GO site
" if no gene product form ID is present, it will refer to the entity that the DB object symbol (column 2) is believed to produce".

**Comment by hdrabkin** [comment]
We can easily populate 12 now based on our marker type classification (protein-coding, non-protein coding (with various RNAs as subclasses); this would be in line with the documentation on the go site.
OR, we could just put them all to "gene" as your thought it should be. 
Just let me know one way or the other so I can finalize a software request.

**Comment by ValWood** [comment]
done? reopen if not

**Comment by hdrabkin** [comment]
FWIW: I was never told a decision; however it goes, it will NOT happen immediately due to software request triage.

**Comment by ValWood** [comment]
OK,

**Comment by hdrabkin** [comment]
Now that the type of gene in gaf and gpad agree, can we close this now?

**Comment by pgaudet** [comment]
@hdrabkin Who is your question addressed to ? @cmungall ? 
Anyways, this looks OK to me, from the release point of view.

**Comment by hdrabkin** [comment]
@pgaudet 
to anyone. I think it can be closed now.
