### ISSUE TITLE
Clarify signalling pathway- role of Autoinducers in  'GO:0009372 quorum sensing'

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/go-annotation#1555]
Clarify signalling pathway- role of Autoinducers in  'GO:0009372 quorum sensing'

There's a little documentation on geneontology.org/page/go-annotation-conventions on Downstream Processes.  Under 'General ligand-receptor pathway' (sorry none of the shortcut links work for us), we thought it was (fairly) clear what should be annotated to a pathway and what is regulating it.  

However, PMID: 9990077 "Quorum sensing in Escherichia coli, Salmonella typhimurium, and Vibrio harveyi: a new family of genes responsible for autoinducer production" shows a fluid from a culture does not contain the autoinducer (AI-2) that the WT produces.  

Is there a process term more descriptive than, say, GO:0052100 intraspecies quorum sensing for us to annotate the ligand LuxS/YgaG?

@ jimhu-tamu

**Comment by pgaudet** [comment]
Hi @suzialeksander @jimhu-tamu
Can you be more specific about the term you need? What are you trying to express? 

Thanks, Pascale

**Comment by suzialeksander** [comment]
Hi,

Unless @jimhu-tamu remembers, I don't recall what details were needed.  I think you can close this.

**Comment by pgaudet** [comment]
Thanks @suzialeksander 

- Looking at PMID: 9990077, it looks like LuxS could be annotated to ''S-ribosylhomocysteine lyase activity" 
Wikipedia states that "the luxS gene, which encodes the protein responsible for AI-2 production is widespread, the latter has mainly a primary metabolic role in the recycling of S-adenosyl-L-methionine, with AI-2 being a by-product of that process" , citing PMID 17360270.

- I think it would be OK to create 'autoinducer-2 biosynthetic process', but according to that wikipedia page, LuxS would be 'upstream of' rather than 'involved in'. 

@suzialeksander @jimhu-tamu
Should I do that ? Or do you just want to close the ticket with no action ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
Nice review: https://academic.oup.com/femsre/article/40/5/738/2198039

**Comment by jimhu-tamu** [comment]
I only vaguely remember this item, but I reviewed the notes @suzialeksander made in GONUTS. 

For annotation of the paper, we can't use an activity term because the chemical nature of AI-2 was not known at the time. I'm not seeing how you get to the suggested term from PMID:999077.

So, the issue was what process term to use. The notes from @sandyl27 are concerned that GO:0009372 Quorum Sensing was not specific enough, insofar as the paper shows luxS is involved in production of the signal rather than sensing it. 

I'm also not sure how you get to the upstream vs involved part, but I can't figure out what the wikipedia page is trying to say. PMID:17360270, but my reaction is that even if it's true that luxS has a "primary" role in metabolism, that's not relevant to whether or not it also has an evolved role in signaling in quorum sensing. Moonlighting functions are still functions, right? And small molecule signals have to come from somewhere in metabolism.

The authors of PMID:17360270 seem to want to exclude AI-2 systems from being signaling at all on the basis of saying "we don't understand the evolutionary benefit". But I haven't read it thoroughly enough. I don't think that's widely accepted.

This is another review that might be more relevant: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5056591/
