### ISSUE TITLE
panther/PAINT annotation -  PTHR23099

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1566]
YGR196C DNA demethylation

yeast don't have DNA methylation AFAIK?

but I'm not sure the annotation would be correct for other species, its describing the ortholog of this protein

Lopez-Mosqueda J, Maddi K, Prgomet S, Kalayil S, Marinovic-Terzic I, Terzic J, Dikic I. "SPRTN is a mammalian DNA-binding metalloprotease that resolves DNA-protein crosslinks." Elife 5:null 2016 Europe PMC | PubMed

**Comment by ValWood** [comment]
If you can track down the annotations I can take a look...

**Comment by krchristie** [comment]
I'm not aware that cerevisiae has CpG islands around transcription start sites, but it seems that cerevisiae might have DNA methylation after all:
https://www.ncbi.nlm.nih.gov/pubmed/22852529 

Source of annotations is an Arabidopsis protein:
http://www.arabidopsis.org/servlets/TairObject?type=locus&name=AT5G58130
from this paper: 
https://www.ncbi.nlm.nih.gov/pubmed/18815596?dopt=Abstract

but I wonder why the RNA binding annotation to the A.thaliana protein wasn't also propagated since that seems to be one of the main claims of the paper, judging by its title...

**Comment by ValWood** [comment]
OK maybe a axon restriction isn't appropriate.

I still don't think there is evidence to link this protein to DNA methylation

pombe SPBC19G7.04 http://preview.pombase.org/gene/SPBC19G7.04

human http://www.uniprot.org/uniprot/Q9H040 http://www.ebi.ac.uk/QuickGO/GProtein?ac=Q9H040

YGR196C

**Comment by pgaudet** [comment]
There is indeed very little evidence. I moved the annotation to the root of the plants. 
I am not sure when the changes will be visible. @ValWood : I let you decide if you want to close the issue already or wait until you see the changes. 

- Pascale

**Comment by ValWood** [comment]
thanks, no need to keep open
