### ISSUE TITLE
Query on 'GO:0051531 NFAT protein import into nucleus' annotations

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#1573]
This is a follow up on 
https://github.com/geneontology/go-ontology/issues/13686

NFAT translocation to the nucleus is part of the calcineurin-NFAT signaling cascade (def = Any intracellular signal transduction in which the signal is passed on within the cell by activation of a member of the NFAT protein family as a consequence of NFAT dephosphorylation by Ca(2+)-activated calcineurin. The cascade begins with calcium-dependent activation of the phosphatase calcineurin. Calcineurin dephosphorylates multiple phosphoserine residues on NFAT, resulting in the translocation of NFAT to the nucleus. The cascade ends with regulation of transcription by NFAT. The calcineurin-NFAT cascade lies downstream of many cell surface receptors, including G-protein coupled receptors (GPCRs) and receptor tyrosine kinases (RTKs) that signal to mobilize calcium ions (Ca2+). ) 

These are the annotations: 

33 EXP  GO:0051533 positive regulation of NFAT protein import into nucleus
6 EXP	GO:0051534 negative regulation of NFAT protein import into nucleus
2 EXP	GO:0051531 NFAT protein import into nucleus
1 EXP	GO:0051532 regulation of NFAT protein import into nucleus

Evidence for the annotations I checked indicate that the proteins annotated regulate or are involved in signaling that leads to NFAT nuclear localization, for eg. PMID: 11439183 "Since calcineurin is thought to control nuclear localization of NFATc proteins, we introduced a mutation into the calcineurin B gene that prevents phosphatase activation by Ca(2+) signals."

Groups that have annotations: 
(16 EXP)	FlyBase @hattrill 
(11 EXP)	MGI @ukemi 
(8 EXP)	UniProt @sylvainpoux
(5 EXP)	BHF-UCL @RLovering 
(2 EXP)	RGD @slaulederkind 

Can you please check if you can move the annotations ? 

Thanks, Pascale

**Comment by hattrill** [comment]
Flushed the FlyBase ones. All from one paper, all circumstantial.

**Comment by RLovering** [comment]
Hi Pascale 

So you saying that if a protein regulates the calcineurin-NFAT signaling cascade it is implied that it regulates NFAT protein import into nucleus. So there is no need to annotate proteins to both terms. Or are you saying the plan is to remove the NFAT protein import into nucleus term (and child terms)?

Will you expect the proteins that actually bind NFAT and transport it to the nucleus to be annotated to this term, distinguishing these entities from those which activate the phosphatase calcineurin? What about annotating the proteins involved in the cascade as either regulating NFAT import or actually transporting it?

BHF-UCL annotations to these terms mostly based on PMID:22688515  - I have removed those which regulate the cascade as well as regulate the NFAT import. But some of these annotations describe the protein phosphatase as being part of the cascade and these also regulate directly the import of NFAT to the nucleus. 

Let me know what I should do with this annotations, and why. I do wonder if this should wait until we have had a signaling annotation workshop so that everyone understands and agrees with the logic being imposed here (but it is 10:15pm on a saturday night and maybe I should stop working)

Thanks

Ruth

**Comment by pgaudet** [comment]
Hi Ruth, 

> So you saying that if a protein regulates the calcineurin-NFAT signaling cascade it is implied that it regulates NFAT protein import into nucleus. 
Yes, at least according to the definition, NFAT import in the nucleus is the last step of the cascade, hence it is a readout of the cascade (similar to testing DNA fragmentation to assay apoptosis). 

> Or are you saying the plan is to remove the NFAT protein import into nucleus term (and child terms)?
I suspect that NFAT import into nucleus takes place via normal mechanisms, so this is not a special type of nuclear protein import. Annotating to this term makes the protein annotated involved in transport rather than signaling, I don't think this is what we mean biologically, is it ? 

Does this help explain why I am suggesting not annotating signaling molecules to 'NFAT protein import into nucleus' (and similar terms? 

I agree that would be a good example to discuss at the signaling meeting (unless we can agree on a solution before that!). 

Thanks, Pascale

**Comment by ValWood** [comment]
my main issue with the terms
positive regulation of NFAT protein import into nucleus
negative regulation of NFAT protein import into nucleus
NFAT protein import into nucleus
regulation of NFAT protein import into nucleus

was that they are gene product specific. It won't be sustainable to have  such terms for every  individual protein where nuclear localization is regulated by a signalling cascade.

However, are you sure that  for all of these annotations the "nucleocytoplasmic transport" process is actually being regulated at all?
For a lot of  nuclear translocation of proteins in response to signalling/sensor , it is not  transport that is being regulated. The protein travels into the nucleus because it is released from sequestration.  The transport will just happen if the  protein is made available to the transport system.
A lot of papers talk about "nuclear translocation" and "translocation" is "location" not necessarily transport..... This is one of the annotations that you probably can't make from a phenotype alone because a phenotype won't inform you if it's localization (only) or transport that is being regulated.

I think it would be useful to discuss generally how to capture localization components required for signalling pathways at the signalling workshop.

I have a number of similar examples that I don't quite know how to capture .
Including:
Proteins required to localize the spindle checkpoint to the spindle pole body.
Proteins required to sequester major cell cycle regulators during negative regulation of the G2/M transition
Proteins required to transport cell cycle regulators into the the nucleus 

(I'm not convinced that all of these are part of the regulation)


I think it might be best to use this as signalling workshop discussion fodder.
It might be helpful for people to review if the nucleocytoplasmic transport system is really being regulated

**Comment by ValWood** [comment]
It was a reply to Ruth's question here:
https://github.com/geneontology/go-ontology/issues/13686
I put it in the wrong ticket (but they are about the same thing)

v

**Comment by RLovering** [comment]
great I am getting the picture, thank you both, I will modify the NFAT annotations

**Comment by RLovering** [comment]
FYI there are just a couple of RGD and MGI annotations left I think

Ruth

**Comment by pgaudet** [comment]
Right I see two MGI annotations to P26450 and Q63810 @hdrabkin

**Comment by slaulederkind** [comment]
The RGD annotations have been moved.
