### ISSUE TITLE
MAPK cascade- Signaling Project

### ISSUE THREAD

**Issue by ukemi** [geneontology/go-annotation#1592]
Google spreadsheet of annotations to genes annotated to the MAPK cascade:https://docs.google.com/spreadsheets/d/198q2DtHRmzbXa9icUIu30DoaRjwKKQkCROfE1KsoO6I/edit#gid=1361703775

- [ ] review annotations to the MAPK cascade

- [x] Flag annotations that are annotated to the cascade but do not have MF support as being part of the process.

- [x] check term and annotations to GO:0000189 'MAPK import into nucleus'. It is currently part of the MAPK cascade. #1596

- [x] GO-CAM models are here: http://noctua.berkeleybop.org/editor/graph/gomodel:5437882f00000024   http://noctua.berkeleybop.org/editor/graph/gomodel:5966411600000155

- [x] check term and annotations to GO:0005078 'MAP-kinase scaffold activity'. How does this molecular function relate to the cascade?

- [x] How do we identify the specific MAPK pathways.
Pombe has 3 regulating conjugation, stress (sometimes known as osmolarity signalling). These have over time found their way into GO. It is difficult to see this working for all species. #1597

- [x] Is a "MAPK activated kinase" part of the MAPK cascade? #1598  This needs to be discussed.

- [x] How do name the specific MAPK pathways.
https://github.com/geneontology/go-ontology/issues/14676

**Comment by ukemi** [comment]
- [ ] check term and annotations to GO:0000189 'MAPK import into nucleus'. It is currently part of the MAPK cascade.

**Comment by ValWood** [comment]
Hi David,

We have a few things like this (in other pathways), and this is one of my outstanding questions.

In the cell cycle, for example, cdc25 phosphatase dephosphorylates and activates cdc2 (Cdk1)
as part of the signalling pathway that controls the G2/M transition.
Cdc25 itself is a target of a number of signalling pathways  including replication checkpoint pathway, cell  size pathway, MAPK pathway etc 
When cdc25 is inhibited by these pathways it is sequestered in the cytoplasm (by a 14-3-3) protein.

So transfer into the nucleus appears to be part of the process at first glance.
However, I have been wondering if these should  really be represented as part of the process.
We know that certain karyopherins are required for the pathway, but does this mean they are involved in the signalling ? Or is it just the case that this is constitutive- just a "conduit" (what do you call them in CamModels?), and they are not  part of the process per se, or regulatory.   We only know  they are required because the transition does not occur when the nucleocytoplasmic transporters are mutated.

If there is no  evidence for regulation of the transport system  itself, would these  be annotated along the lines:

karyopherin (has_substrate cdc25) involved in "protein import into nucleus" happens_during(positive  regulation of G2/M transition of mitotic cell cycle).

My feeling is that the "regulation of the transition" here has nothing to do with the transport system per se but rather controlled by whatever releases cdc25 from the inhibitory sequestering by the 14-3-3 protein (although I am not sure that this is fully known). 

I have a similar problem with localization of participants in spindle checkpoint pathway.

I hope we can resolve this  in Sept. I hope to discuss this with Jacky  H too, as she  has co-authored and curated  a number of papers which generated "localization within a signalling pathway data" (mainly the pathway above), and she has done a some work on the role of the nuclear transport system in cell cycle control. I'm hoping she will also be able to attend the signalling meeting too.

**Comment by ValWood** [comment]
Perhaps we  should make this ticket about localization discussion, and open a new ticket for the general MAPK cascade discussion (linking to this one). Localization and signalling could get long.....

**Comment by ukemi** [comment]
This ticket is supposed to be a ticket for the overall project.

**Comment by ValWood** [comment]
Shall I  open a ticket about  localization  generally in signalling or do you want to keep one huge ticket?

**Comment by ukemi** [comment]
This ticket was opened to specifically keep track of the MAPK signaling cascade portion of the signaling project. The original idea was to open tickets like this and then to cross reference them to specific check-box tasks and other tickets. So when I added the check box above, it was simply a task to look at this in the very defined context of the MAPK cascade in this project because I identified annotations to the transport and subsequently saw it was a part of the cascade in the ontology.

**Comment by ValWood** [comment]
I'll open a general ticket about localization issues within signalling pathways and move these comments.

**Comment by ukemi** [comment]
Thanks. I'll figure out a way to link to it from here.

**Comment by ValWood** [comment]
See https://github.com/geneontology/go-annotation/issues/1596
for general discussion abut localization within a signalling pathway.

**Comment by ValWood** [comment]
- [ ]  Question which has arisen for us here. How do we identify the specific MAPK pathways.
Pombe has 3 regulating conjugation, stress (sometimes known as osmolarity signalling). These have over time found their way into GO. It is difficult to see this working for all species.

Perhaps a model were we just say

MAPK cascade part_of "response to osmolarity stress"
MAPK cascade part_of "response to oxidative stress"
would work better. The current situation already has lots of problems. 

For instance the same pathway named differently (is stress-activated MAPK cascade the same as MAPK cascade involved in osmosensory signaling pathway?)




--

**Comment by ValWood** [comment]
- [ ] question
Is a MAPK activated kinase part of the MAPK cascade?
http://pombase2.aska.gen.nz/gene/SPAC23A1.06c

**Comment by ValWood** [comment]
@Antonialock .....cool 

![mapk](https://user-images.githubusercontent.com/7359272/28257695-9ca751de-6ac4-11e7-854e-8ce24b7fff04.jpg)

This is the  "PomCam" (automatically generated from GO annotation) model of MAP kinase pathways today. You can see here that if you connect the MF's up correctly, the models resolve themselves without requiring Noctua (you can clearly see the 3 separate MAP kinase pathways).

Our next step  for the network generating work is to have more labelling so that you can see what the actual gene products, activities and relations are...

**Comment by Antonialock** [comment]
That's so cool! What URL do you get that from?

**Comment by ValWood** [comment]
You just export the 
systemtic IDs for MAPK cascade from here
http://pombase2.bioinformatics.nz/query

Then import list into esyN 
http://www.esyn.org//index.php
select PomBase curated data (this is updated nightly)

I had to rearrange the layout, and I deleted some redundant  edges for protein binding (just kept the directional ones). But we are not far from being able to do this automatically for every process directly in  PomBase....

Do we know what goes on upstream of all of those inhibitory phophatases? (I think that is a bit of a black hole at the moment).

@ukemi  I hijacked your ticket but I wanted to convince you that we could create nice/complete models automatically without touching noctua....

**Comment by Antonialock** [comment]
Ah ok, that makes sense. Thought there was a new tool out thee :-)

**Comment by RLovering** [comment]
Hi Val

this is brilliant. Do you get the directionality from the AE field?

Ruth

**Comment by Antonialock** [comment]
@RLovering yeah if you look in the dropdown list here: http://www.esyn.org//index.php#START
for pombe it is possible to select "PomBase curated".
It should include "protein binding" MFs, and annotations using "has substrate" extension.

Does it also include some intact data Val?

**Comment by Antonialock** [comment]
@RLovering we have been busy :-)
http://preview.pombase.org/term/GO%3A0004672

**Comment by RLovering** [comment]
Can you colour the nodes according to annotation to a specific GO pathway?

**Comment by ukemi** [comment]
Hi @ValWood 

This is great, but can you move this discussion to another ticket and then let me know which one it is? This ticket is supposed to be reserved for a checklist of tasks that we want to accomplish with this project. I'd like to keep all discussions in separate focused tickets.

**Comment by ValWood** [comment]
I only posted it because this *is* our MAPK review...
This is everything in pome MAPK pathways connected up, according to current defs.
Will migrate later...

**Comment by ukemi** [comment]
No worries. I think this is great, just trying to keep things organized.

**Comment by ValWood** [comment]
Hi @RLovering  I put some notes on this in a ticket if you are interested https://github.com/pombase/curation/issues/1699

Can answer questions at the meeting...

**Comment by hattrill** [comment]
Hi @ukemi @sabrinatoro 
I know there was discussion on the role of MAPK scaffolding proteins at the GOC meeting, but I am not sure if any firm conclusion was reached wrt regulation vs within pathway.
Can you advise?
Thanks.

**Comment by ValWood** [comment]
I think the conclusion was, that @ukemi  thinks they are regulators and I don't ;) ...I think they are part of pathway, because they are effectively a 'complex' with the MAPK'/K/Ks.

They prevent "incorrect signal flow"  it prevents cross-talk signaling but I'm not convinced that they regulate pathway choice....  because the complex exists before the pathway is 'activated'.

.....But, I'm happy to annotate them as "regulators"  if that is the consensus.

**Comment by hattrill** [comment]
Hmmm.....then there is only one way to decide - an arm wrestling contest!

**Comment by hattrill** [comment]
Just to completely trash this ticket with side-issues - did anyone define where Ras signaling ends? I have annotations to MAP cascade components (or regulators!), like ksr, to regulation of Ras signaling. This applies to older papers when the assays are essentially looking at genetic interactions. Before I move them and get UniProt to chip in, I'd like to be sure.

**Comment by sabrinatoro** [comment]
Based on the publications, the scaffold protein is necessary to bring the MAPKinases together. You can look at it as a protein which assemble the complex, but is not really part of that complex. David and I agreed that it regulates the pathway. (I am not sure what the 'latest' correct relation is: directly_activates, or directly positively regulates,...)
However, it is GO, so we can review the publications and discuss this during one of our calls...

**Comment by ValWood** [comment]
> Hmmm.....then there is only one way to decide - an arm wrestling contest!

I'll put that down for the Cambridge meeting...

**Comment by ValWood** [comment]
> but is not really part of that complex. 

I thought it was...why is that?

**Comment by ValWood** [comment]
OK I just found this.

Abstract
The scaffold proteins of signaling pathways are thought to act as passive tethering devices bringing together catalytic components of signaling cascades. Good et al. (2009) now reveal that in the budding yeast the scaffold protein Ste5 acts as an allosteric activator of the mitogen-activated protein kinase Fus3, rendering it competent to be a kinase substrate for signal transmission.

Comment on
The Ste5 scaffold directs mating signaling by catalytically unlocking the Fus3 MAP kinase for activation. [Cell. 2009]
PMID: 19303841 


So in this case it is regulating the pathway. 
But passive tethering devices/scaffolds are not generally "regulators".  

This would need a separate annotation IMHO
under "enzyme regulator activity". It isn't a scaffold activity.....

**Comment by ukemi** [comment]
There are other cases/experiments like this one.

**Comment by ValWood** [comment]
My expert thinks it is "part of the pathway":

I would argue that it is a bit of both.  It is a physical component of the pathway, thus a.  

It is and is not an upstream regulator.  The scaffold holds the various kinases (KKK, KK and K) together into a signaling complex.  Loss of the scaffold would therefore lead to loss of signaling.  

Is it upstream?  Yes, in the a mutation that activates a MAPK would suppress the loss of the scaffold. 
No, in that a mutation that activates the MAPKKK or MAPKK would not suppress the loss of the scaffold, since you would still have a defect in signaling to the MAPK.

Charlie


On Thu, May 31, 2018 at 11:50 AM, Valerie Wood <vw253@cam.ac.uk> wrote:


    A quick  (hopefully) question.

    Is a MAPK scaffold

    a) 'part' of the MAPK signaling pathway

    b)  an 'upstream regulator' of a MAPK signalling pathway?

    Val

**Comment by ValWood** [comment]
So here is my  take on this.

1. The scaffold is part of the pathway.

2. The scaffold has another function as an  direct upstream regulator (always or sometimes?).

I would have annotated for the example above

1. MAPK scaffold activity part_of  MAPK signalling pathway has_input MAPKKK, MAPKK,MAPK

AND

2. enzyme regulator activity  (or more specific child) has_direct_input MAPK (In the above eg) part_of MAPK signalling pathway 
(because here, it is acting as a canonical allosteric activator and this is separable from its scaffold activity)

**Comment by hattrill** [comment]
That's a good point about the enzyme reg function, as it certainly isn't a passive scaffold.
I think that for now I will go with "part of", to distinguish it from casual (not causal!) interlopers that modulate the cascade.
(But happy to yield)

**Comment by pgaudet** [comment]
Looks like the suggestions here were all implemented. MAPK annotations have been reviewed for the 2023/2024 signaling cascade project: 
https://github.com/geneontology/go-annotation/issues/4930
https://github.com/geneontology/go-annotation/issues/4929
https://github.com/geneontology/go-annotation/issues/4928
https://github.com/geneontology/go-annotation/issues/4865

**Comment by pgaudet** [comment]
To clarify: GO:0000165 MAPK cascade is **not** being obsoleted
