### ISSUE TITLE
IPR007596 viral proteins? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#1600]
Hello, 

These Interpro domains contain at least one eukaryote but have annotations to 'viral process' or children; these should probably be removed. 

Thanks, Pascale

InterPro:IPR007596
InterPro:IPR033907
InterPro:IPR008981
InterPro:IPR024135
InterPro:IPR001257
InterPro:IPR007094
InterPro:IPR004259
InterPro:IPR033591
InterPro:IPR008748
InterPro:IPR009013
InterPro:IPR007096
InterPro:IPR007796
InterPro:IPR011492
InterPro:IPR033320
InterPro:IPR033314
InterPro:IPR008740
InterPro:IPR013828
InterPro:IPR000721
InterPro:IPR003036
InterPro:IPR008919
InterPro:IPR010332
InterPro:IPR004913
InterPro:IPR003383
InterPro:IPR006429
InterPro:IPR006965
InterPro:IPR007099
InterPro:IPR015960
InterPro:IPR003389
InterPro:IPR021304
InterPro:IPR008609
InterPro:IPR033318
InterPro:IPR006777
InterPro:IPR004196
InterPro:IPR007322
InterPro:IPR002166
InterPro:IPR008743
InterPro:IPR007663
InterPro:IPR007100
InterPro:IPR002532
InterPro:IPR004954
InterPro:IPR004109
InterPro:IPR003515
InterPro:IPR016407
InterPro:IPR000657
InterPro:IPR000982
InterPro:IPR001866
InterPro:IPR004929
InterPro:IPR009429
InterPro:IPR009228
InterPro:IPR000939
InterPro:IPR007098
InterPro:IPR003513
InterPro:IPR008760
InterPro:IPR000081
InterPro:IPR000349
InterPro:IPR000236
InterPro:IPR004997
InterPro:IPR004339
InterPro:IPR004999
InterPro:IPR007611
InterPro:IPR021152
InterPro:IPR033685
InterPro:IPR005208
InterPro:IPR000501
InterPro:IPR002493
InterPro:IPR010615
InterPro:IPR004996
InterPro:IPR002689
InterPro:IPR015961
InterPro:IPR004955
InterPro:IPR015962
InterPro:IPR004917
InterPro:IPR008980
InterPro:IPR002574
InterPro:IPR000382
InterPro:IPR008043
InterPro:IPR007961
InterPro:IPR008982
InterPro:IPR008751
InterPro:IPR010881
InterPro:IPR004174
InterPro:IPR000931
InterPro:IPR002512
InterPro:IPR000211
InterPro:IPR008187
InterPro:IPR000745
InterPro:IPR015200
InterPro:IPR005059
InterPro:IPR000776
InterPro:IPR010270
InterPro:IPR009225
InterPro:IPR034738

**Comment by asangrador** [comment]
Hi Pascale,
We are looking into the list you sent us. Probably many of these entries will match a very small number of trembls derived from unassembled sequence reads, which are not very reliable, and we would not like to lose our annotation to accommodate them. But we will look at the individual cases and get back to you.
Cheers,
Amaia

**Comment by asangrador** [comment]
Hi Pascale,
We have been looking at this issue and our conclusion is that we should not remove the annotation for these entries. Sometimes the eukaryotic hits are due to unreliable WGS sequences in TrEMBL, and we do not feel that we can remove the annotation solely based on this; we would need more evidence than a gene prediction based on WGS data from a taxonomy that doesn’t match. In other cases the eukaryotic hits are not false hits, they belong in the taxon the virus infects. In some cases, virus genes could be integrated into the host genome (e.g IPR004997, PMID: 26784220), while some sequences could be artefacts (e.g. IPR000982 matches human protein Q86VZ9, first identified as a human protein [PMID:12675278] and later isolated as a viral protein [PMID:16325221]). 

In any case, there is nothing we can do about this. GOA could delete this annotation for eukaryotic proteins as already does for proteins with InterPro annotations that violate taxonomic constraints. The problem is that virus terms don’t seem to have taxonomic constraints. May be is something that could be considered?

Amaia

**Comment by pgaudet** [comment]
Hi @asangrador 

Thank you very much for looking into this. We plan to add a taxon constraint to forbid the annotation of non-viral proteins to these terms (see https://github.com/geneontology/go-ontology/issues/13214), hopefully that will simply filter out the InterPro false positives. 

Thanks, Pascale
