### ISSUE TITLE
SGD GAF has not been submitted since Jan 2017

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-annotation#1619]
The latest SGD GAF is from January, hence is missing genes like YBL048W / http://www.yeastgenome.org/locus/S000000144/overview

The source location in sgd.yaml is set to be the go svn submissions dir:
http://viewvc.geneontology.org/viewvc/GO-SVN/trunk/gene-associations/submission/

@srengel ping me on skype if you want more details, let me know if I should assign another person

**Comment by srengel** [comment]
this is a known issue.  the SGD database has been frozen since 1/17/17 because we are trying to finish up a schema change.  we plan to complete that work and go live with our webpages by end of this month, but i do not yet have an ETA for getting our GAF submissions up and running on a regular basis again.

note that we have continued curating into P2GO during the last 8 months of freeze, so we'll have updates for our GAF once we get going again.  hopefully very soon.

**Comment by cmungall** [comment]
OK, feel free to close

**Comment by srengel** [comment]
p.s. YBL048W is not in our GAF because we don't include high-throughput annotations in the GAF.  we will start including those once the new HTP ev.codes are fully in place (did that happen already since the June GO mtg?).
