### ISSUE TITLE
MGI annotations have invalid combinations of anatomy ID and stage in extensions

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-annotation#1633]
```
MGI     MGI:1354727     Smtn            GO:0060452      MGI:MGI:4437553|PMID:18678771   IMP     MGI:MGI:3613292 P       smoothelin              protein taxon:10090     20170906        MGI   occurs_in(EMAPA:35342),occurs_in(MA:0002039 TS28)
MGI     MGI:1354727     Smtn            GO:0060452      MGI:MGI:4437553|PMID:18678771   IMP     MGI:MGI:3613293 P       smoothelin              protein taxon:10090     20170906        MGI   occurs_in(EMAPA:35342),occurs_in(MA:0002039 TS28)
```

Not currently reported but will be when this is implemented:
https://github.com/biolink/ontobio/issues/99

recommend:

```
occurs_in(MA:0002039),occurs_during(MmusDv:0000037)
```

(but not clear if necessary, if MA is implicitly TS28)

**Comment by ukemi** [comment]
Looks like a bug in our GAF generation when we combine an anatomical structure with a stage. I will follow up.

**Comment by ukemi** [comment]
happens_during?  That is what I see in gorel.obo.

**Comment by hdrabkin** [comment]
Note: I tried a couple of ways to fix this
1. removed the TS28 from MA but kept TS28 for the EMAPA  term; this failed
2. removed TS28 from BOTH MA and EMAPA: this went through (the use with MA is just wrong)
Strange because we have always been using EMAPA:id + stage; we have hundreds of annotatons like that. However, it was only just these two new annotations.

**Comment by hdrabkin** [comment]
actually, now I see there were TWO annotations with an MA + TS28
I fixed one but not the other so when I got the second error report after removing ONE MA+TS28, but there was a second one, and I thought it was same one so removed the TS28 from the EMAPA 
The happens during is not the issue, otherwise all of our previous annotations would be flagged.
I will try a test now.

**Comment by cmungall** [comment]
TS28 is not a valid ID. Please see my original recommendation. Use MmusDv for stages.

**Comment by hdrabkin** [comment]
We currently have 3500+ genes with at least ONE annotation using TS28 specifically. If this was a problem all of them should have been flagged.

**Comment by hdrabkin** [comment]
Ok, I seem to have forgotten that our TSs are stripped from our gaf. I know I was told this was so once a long time ago but totally forgot.
So the problem after removing the MA+TS was that there was STILL two EMAPA with a TS in the gaf. BUT these SHOULD have been removed like all our other EMAPA usages. THAT is why there was a sudden unexpected white-space in the 'cherry script'. 
So, tomorrow, the annotation Li made today should have that TS stripped from the EMAPA term line.
If it isn't then our gaf generation is having a bad day (or maybe just a bad day last Friday if it is now ok).
Should this now be as it was, we will then test making an annotation with the two separate extensions, (occurs_in  EMAPA:blah, and then happens_during MmusDv:x, and see if that comes out in the gaf(our gaf generator might not like it), and then see if it gets by the cherry script (so it isn't stripped out for Amigo loading). 
Sorry for the confusion.

**Comment by hdrabkin** [comment]
Ok;  the filter removing the TS28 from EMAPA lines is working now as before. Today's gaf has no TS28.

**Comment by hdrabkin** [comment]
The MmusDv id line passes the MC script, so these would not be stripped. 
We (GO@MGI) will discuss this further.
I'll close this ticket as resolved (the original appearance of the "TS28" was NOT suppose to be in the file to begin with.
