### ISSUE TITLE
Annotation challenge: Yeast SPT6 and transcription antitermination factor activity, DNA binding

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#1641]
Hello, 

I came across the term 'transcription antitermination factor activity, DNA binding',  annotated once by EXP in SGD to SPT6/S000003348 based on a single paper. 

The SGD description does not mention antitermination activity (and the paper on which that annotation is based does not implicate SPT6 in antitermination; in fact it talks about termination, but not about antitermination, http://www.jbc.org/content/280/2/913.long) 

As far as I can tell anti-termination only occurs in bacteria, see paper cited in the ontology: 
https://www.ncbi.nlm.nih.gov/pubmed/8332211
and wikipedia: https://en.wikipedia.org/wiki/Antitermination

In eukaryotes 'translational reinitiation' (GO:0002188) seems more appropriate, see https://link.springer.com/content/pdf/10.1007%2F978-1-4020-6754-9_978.pdf

@srengel Can you please have a look ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
For the DNA binding I still see 1 protein + 1 paper (3 annotations:) 
![image](https://user-images.githubusercontent.com/4782928/31394190-049fbca2-adde-11e7-9584-1181bb35f0e9.png)

**Comment by srengel** [comment]
yes, you are right.  one gene from one paper.  i just realized that i was looking at the P term 'transcription antitermination', not the F term.  oops!

...but if you are saying that antitermintation only occurs in bacteria, then i guess i'll have to address those P annotations also.

**Comment by pgaudet** [comment]
OK right ! 

I was just worried about getting the stats wrong ...

**Comment by srengel** [comment]
SPT6 allows read-through at the GAL10-GAL7 locus to created a dicistronic mRNA.  mutated SPT6 allows less read-through.  the paper from which the annotation was made provides evidence that the transcription elongation factors Spt6p and Spt4p promote transcription elongation past the GAL10 3' end.

the Nature review at https://www.ncbi.nlm.nih.gov/pubmed/8332211 doesn't say it's only in bacteria.  they use lambda phage and HIV as their examples, trying to find models to explain how antitermination works in eukaryotic systems.

i'm inclined to leave the yeast annotations as they are, but am happy to discuss further.

**Comment by krchristie** [comment]
I agree with @srengel that antitermination is not only in bacteria. The HIV example she mentioned from the Nature review she cited is already occurring in eukaryotic cells since HIV is a virus of eukaryotic cells.

**Comment by pgaudet** [comment]
Hi @srengel @krchristie 
Thanks for the precision; I meant that anti-termination did not occur in eukaryotes (only viruses and bacteria). 

Looking at the reference supporting the SPT6/S000003348  annotation, how about if we created a new term, 'RNA polymerase processivity factor activity'? (similar to 'DNA polymerase processivity factor activity'). This also matched the description in SGD of the function of SPT6 (it seems like SPT4 and SPT5 could also have that annotation). 

Would that work ? 

Thanks, 
Pascale

**Comment by krchristie** [comment]
@pgaudet - My recollection of the word "processive" and how it applies to polymerases is that you absolutely cannot use it for RNA polymerases.

One of my UC Berkeley professors, and the PI of the other half of my joint lab, lectured at great length about how it is not appropriate it use the word "processivity" for RNAP's because it has a very specific meaning about how many nucleotides a DNAP links together in a single visit to the template before it falls off. DNAP's can come on and off the DNA template many times. In contrast, once an RNAP comes off the template, it does not get back on. Therefore the term "processivity" is irrelevant.

**Comment by ValWood** [comment]
I have seen it used in the context of RNA pol 
https://www.ncbi.nlm.nih.gov/pubmed/15780939

and microtubule polymerases. 

I don't know if it is correct...

**Comment by pgaudet** [comment]
I saw it for polII as well: 
https://www.ncbi.nlm.nih.gov/pubmed/24837678
http://www.nature.com/nrm/journal/v16/n3/abs/nrm3953.html

**Comment by srengel** [comment]
i see anti-termination mentioned for eukaryotes.  are we just glossing over that?  have i lost the plot?

**Comment by krchristie** [comment]
It may be that my professor was railing against a misuse of a term that is now out of the barn.

However, if you put "processivity factor" into PubMed, that specific phrase seems to only be used for some DNA polymerase factors. 

While I do see quotes like this from Patrick Cramer's lab (PMID:21386817):

> The core function of NusG and Spt4/5 is to stimulate transcription elongation and RNAP processivity, and this function resides in the conserved NGN domain

So, though Spt4/5 is described as affecting processivity (i.e. making it fully processive so that it does not fall off), I still do not see anyone calling factors like Spt4/5 a "processivity factor". I'm not sure we should be inventing terminology that we are not seeing in the literature. In the Cramer lab paper I quoted above, Spt4/5 is called a "transcription elongation factor".

Then, for Spt6, here are what it is called in 3 papers that come up near the top of a PubMed search:
Wang AH, Juan AH, Ko KD, Tsai PF, Zare H, Dell'Orso S, Sartorelli V. The
**Elongation Factor Spt6** Maintains ESC Pluripotency by Controlling Super-Enhancers
and Counteracting Polycomb Proteins. Mol Cell. 2017 Oct 19;68(2):398-413.e6. doi:
10.1016/j.molcel.2017.09.016. Epub 2017 Oct 12. PubMed PMID: 29033324.

Jeronimo C, Robert F. **Histone chaperones FACT and Spt6** prevent histone
variants from turning into histone deviants. Bioessays. 2016 May;38(5):420-6.
doi: 10.1002/bies.201500122. Epub 2016 Mar 15. PubMed PMID: 26990181.

Jeronimo C, Watanabe S, Kaplan CD, Peterson CL, Robert F. The **Histone
Chaperones FACT and Spt6** Restrict H2A.Z from Intragenic Locations. Mol Cell. 2015
Jun 18;58(6):1113-23. doi: 10.1016/j.molcel.2015.03.030. Epub 2015 May 7. PubMed
PMID: 25959393; PubMed Central PMCID: PMC4475440.

Again, I would not call this a "processivity factor" in GO either.

**Comment by krchristie** [comment]
I agree with @srengel that the review @pgaudet cited implies that antitermination can happen in eukaryotes too.

Also, antitermination definitely happens in mitochondrial transcription too, so you definitely should not try to apply taxon constraints to say antitermination is specific to bacteria and viruses.

**Comment by pgaudet** [comment]
Hi @srengel 
Going back to my original request: 
- Can you just check that STP6 is correctly annotated to 'transcription antitermination factor activity, DNA binding' and 'transcription anti-ermination, based on PMID:15531585 
- as well as SSU72 + transcription anti-termination, based on PMID:12453421

It seems to me "regulation of DNA-templated transcription, termination" is closer to what is described in the papers. 

Thanks for your patience ! 

Pascale

**Comment by srengel** [comment]
Hi @pgaudet yes i just checked again, and these are correct:

- SPT6 is correctly annotated to 'transcription antitermination factor activity, DNA binding' and 'transcription anti-termination, based on PMID:15531585
- as well as SSU72 + transcription anti-termination, based on PMID:12453421

**Comment by pgaudet** [comment]
OK got it, thanks !! 

Pascale
