### ISSUE TITLE
U6 small nuclear RNA (adenine-(43)-N(6))-methyltransferase (IPR017182)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1669]
I'm not sure that this is correct

GO:0048024 regulation of mRNA splicing, via spliceosome 

it might be but is there a ref. I seems to methylate quite a few  rRNAs and snRNAs of various types. I'm not sure if it is regulating splicing though,  is probably upstream?

**Comment by asangrador** [comment]
Hi Val,
This term has already been removed, but you won't be able to see the change till our next release. I think the term was added because in mammals it seems to have a role in splicing [PMID:28525753], but the entry also matches others methyltransferases than U6 small nuclear RNA (adenine-(43)-N(6))-methyltransferase, like psiM, and therefore the only term it has at the moment is methyltransferase activity.
Cheers,
Amaia

**Comment by pgaudet** [comment]
@ValWood please close as appropriate.
