### ISSUE TITLE
Interested in submitting a GO annotation for non-model organism

### ISSUE THREAD

**Issue by manyasi06** [geneontology/go-annotation#1670]
Greetings,

I am emailing before I begin to setup GO-annotation reference set for Channel Catfish.  We additionally plan to update the data as well after the initial submission.

Regards

Bryan Musungu

**Comment by vanaukenk** [comment]
Hi Bryan,

Thanks very much for contacting GO about your submission.

Can you tell us a bit more about what types of annotations you would like to submit (e.g. InterPro2GO-based annotations, literature-based annotations) and what primary identifiers you'll be using to associate the genes/gene products with GO terms?  That will help us get started.

Best,
--Kimberly Van Auken

**Comment by manyasi06** [comment]
Hello Kimberly,

It will be doing the Interpro2go based annotation and I will be using NCBI accession as the identifiers if that is okay.  If not I am not opposed to using different identifiers.

Regards,

Bryan

**Comment by selewis** [comment]
We'd prefer the UniProtKB identifiers because that is what we use for the
reference proteomes of each organism ("model" or not).

Hope that's possible, but since you're using interpro2go, seems even easier.

-S

**Comment by vanaukenk** [comment]
Hi Bryan,

Thanks again for your interest in GO annotations for channel catfish.

As Suzi mentioned, for non-model organisms, we typically work with UniProt as they have an established InterPro2GO pipeline, as well as other automated annotation pipelines, for a large number of proteomes.  

Also, from querying the UniProt database for 'channel catfish' it seems that there are already some manual (i.e. literature-derived) GO annotations from curation groups such as AgBase.  Is your group also interested in making manual GO annotations?

Have you had a chance to compare your sequences to what already exists in UniProt, and if so, how complete is the current coverage?  Once we have a better sense of how your reference sequences compare to what is currently in UniProt we can come up with a more concrete plan on moving forward.

Best,
--Kimberly

**Comment by manyasi06** [comment]
Hello Kimberly,

The agbase currently only has about 6221/47978.  I am not too particularly sure how recent the update has been because the genome was updated last year.  Another question I had is the current genome assembly does not appear to link with uniprot because I am unable to look ids from NCBI or is it my side.

Best,

Bryan

**Comment by vanaukenk** [comment]
Thanks, Bryan.

I think the best thing to do here would be to put you in direct contact with the UniProt group so that we can work together with them to get the channel catfish proteome into the UniProt databases and, ultimately, into the automated GO annotation pipelines.

I will send an email and cc you.

**Comment by ValWood** [comment]
It really bothers me that we no longer have an easily accessible helpdesk. In fact, it seems inexcusable that the GO does not have a helpdesk.

I'm sure that our  funders and advisors will look  very unfavourably on this. Yes, the number of queries has  dropped (probably by 99%, I am guessing, but I did see all the help-desk queries so I think this is a  ball park underestimate).

I do not think  that this 
 amigo -> data health link->
http://help.geneontology.org/
Can *possibly*  work if  users need  to register on Github to report a problem. My concern is certainly justified because nobody has  yet reported a problem via this route (is that correct?). 

Think about it....... We cannot even  easily get the UniProt curators  who use GO to get a GitHub ID, so why should we expect a random GO user or contributor to do this GO ?

Our priorities need to be based on what users say and need. It might seem to be a pain, but if we listen to  what our users need, rather than what we *think* they might need, we will be better.

We exist to support  biologists.  We cannot possibly justify not  enabling users to contact  us easily with  questions , problems or suggestions.   

Think about how frustrating this is for users.

Rant over.

**Comment by ValWood** [comment]
@RLovering  did a massive amount of work to get users to submit information, and this has effectively been stymied by the decision to remove the helpdesk.

Please go to AmiGO and follow the  instructions from the "GO health link", or better still sit with somebody wo is nothing to do with GO  and ask them tell you what they would do if they got to this link. It is actually quite pointless.....
