### ISSUE TITLE
Challenge: P46133 and secondary active transmembrane transporter activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#1672]
Hello @keseler 

Would you please have a look at the annotation of P46133 to secondary active transmembrane transporter activity? All I can find in the paper is "AbgT transports p-aminobenzoyl-glutamate as a secondary activity." (discussion). 
(which possibly also questions the annotations to 'p-aminobenzoyl-glutamate transport' and 'p-aminobenzoyl-glutamate uptake transmembrane transporter activity', but that's more debatable. 
 
 
Thanks, Pascale

**Comment by keseler** [comment]
Hi Pascale,

The "secondary active transmembrane transporter" term is a classification that I suspect doesn't show up literally in publications very often.  The last paragraph of the results in the Carter et al. paper talks about the inhibitors they tried, which mostly destroy the proton gradient, suggesting that AbgT it is a secondary transporter.  The "secondary activity" in the discussion is mentioned because apparently the activity with the substrate they were measuring isn't terrific, so they speculate that the physiological substrate might be something else.

I'm going to let Amanda, who is the real expert, weigh in on this to see if there is something I'm missing.

Cheers,
Ingrid

**Comment by amandamackie** [comment]
Ingrid's comments are accurate. 

Carter et al show that the protonophore CCCP, disrupts AbgT activity which suggests that it is reliant on the pmf to energize transport ie it is a secondary active transporter (see also the AbgT family in the Transporter Classification Database).  

Low (uM) affinity for the substrate raises the question of physiological relevance; the authors indicate that E. coli may 'utilize p-aminobenzoyl-glutamate in a “salvage” or recycling pathway, whereby part of the folate structure is scavenged' or 'it is possible that AbgT may actually serve physiologically as a transporter for some other molecule, perhaps a dipeptide'. 

Amanda

**Comment by pgaudet** [comment]
Thanks @keseler and @amandamackie , this is very useful. 

Since this protein (AbgT P46133) is the only one annotated to the term 'p-aminobenzoyl-glutamate uptake transmembrane transporter activity', I changed the term label to 'secondary active p-aminobenzoyl-glutamate transmembrane transporter activity' and added the 'secondary active transporter' parent. 

I also update the definition to include the starndard part of the 'secondary active transporter' part: 
Enables the transfer of p-aminobenzoyl-glutamate from one side of a membrane to the other, **up its concentration gradient. The transporter binds the solute and undergoes a series of conformational changes. Transport works equally well in either direction and is driven by a chemiosmotic source of energy. Chemiosmotic sources of energy include uniport, symport or antiport**.  p-aminobenzoyl-glutamate is the anion of p-aminobenzoyl-glutamic acid.

See https://github.com/geneontology/go-ontology/issues/14372

Thanks, Pascale

**Comment by pgaudet** [comment]
if you agree with the above changes please go ahead and close the present issue.

**Comment by amandamackie** [comment]
Hi Pascale,

I think the definition of secondary active transport could be improved The last sentence 'chemiosmotic sources of energy include uniport, symport or antiport' does not make sense. Chemiosmotic sources of energy are ion gradients. Symporters and antiporters are types of secondary active transporters Can I suggest changing that last sentence to: 'Secondary active transporters include symporters and antiporters'. My understanding is that uniporters mediate facilitated diffusion, if the substrate is a charged molecule, transport may rely on the membrane potential but it is not considered 'active' transport because movement is always down the concentration gradient. 
Figure 1 in Milton Saier's paper PMID 10839820 is a good outline of transporter classification (note the separation of uniport and secondary active transport). Also PMID 26234418 for a discussion of uniport

Amanda

**Comment by pgaudet** [comment]
Thanks @amandamackie, I have changed the definition of secondary active transporter activity. 

If you have more feedback on the standard definitions of transporters, please do let me know: 
http://wiki.geneontology.org/index.php/Transporter_terms_standard_definitions

Thanks, Pascale
