### ISSUE TITLE
TERF1 annotation check P54274

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1705]
http://www.uniprot.org/uniprot/P54274

I notice this has ubiquitin binding, but I think it is "ubiquitinated?"

v

@RLovering

**Comment by RLovering** [comment]
Thanks Val

annotation deleted

Ruth

**Comment by ValWood** [comment]
also for UniProt to check


G2/M transition of mitotic cell cycle IEP (this is a difficult annotation to make even from phenotypes, I don't think it is possible at all from IEP)

positive regulation of apoptotic process Source: UniProtKB
 @pgaudet  I did not check this but it seems like an experimental readout?

**Comment by ValWood** [comment]
reopening for the uniprot checks

**Comment by ValWood** [comment]
also
mitotic spindle assembly checkpoint Source: UniProtKB
positive regulation of mitotic cell cycle Source: UniProtKB
positive regulation of mitotic nuclear division Source: UniProtKB

Are phenotypes, but not regulation. They are just causing problems for the cell cycle as fas as I can see...A problem that results in the activation of a checkpoint is not necessarily  part of the checkpoint or regulating a checkpoint. It's only causing a problem that is recognised by the checkpoint sensor.

**Comment by ValWood** [comment]
@ggeorghiou
could you divvy this one up too?

thanks

Val

**Comment by ggeorghiou** [comment]
Hi @ValWood finally getting a chance to review this. I've looked over this entry carefully and have removed the questionable annotations you mentioned as well as several others that after reviewing the papers look more like an experimental readout rather than the actual protein function. In addition the paper used primary human breast cancer cells, which in itself is tricky enough to get a readout on actual gene product function due to additional mutations that are likely to mask the actual function. Closing this ticket now.
