### ISSUE TITLE
Annotation review: polIII terms 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#1734]
Hello, 

These 4 terms have 11 EXP annotations (and no other manual annotations): 
 GO:0001038 RNA polymerase III hybrid type promoter TFIIIB recruiting transcription factor activity (no direct annotations)
   -  **GO:0001005** transcription factor activity, RNA polymerase III type 1 promoter sequence-specific binding, TFIIIB recruiting **6 EXP** 
   -  **GO:0001008** transcription factor activity, RNA polymerase III type 2 promoter sequence-specific binding, TFIIIB recruiting **5 EXP** 
   -  GO:0001033 transcription factor activity, RNA polymerase III type 3 promoter TFIIIB recruiting (no direct annotations)

TFC3, TFC4, TFC6, TFC7 and TFC8 are annotated to both terms. 
TFC1 is only annotated to GO:0001005, but that seems to be a limitation of the assay since TFC1 is a member of the complex. 

I propose to merge these 4 terms into 'GO:0000995' (to be renamed "general RNA polymerase III transcription factor activity", see https://github.com/geneontology/go-ontology/issues/14790

@krchristie is this OK with you ? 

Thanks, Pascale

**Comment by krchristie** [comment]
I don't have any objection to merging the type 1, type 2, and type 3 promoter terms into the parent term. David H and I debated whether we should go to that level at the time and decided to do it as there are mechanistic differences in how the transcription factors assemble to recruit the PIC (preinitiation complex) at the three different promoter types. However, it is probably often hard for curators to determine the correct term, so I'm fine with removing that level of detail.

However, I am concerned that use of the word "general transcription factor" in the context of RNAP I is artificial and will be confusing since I have never seen the word "general transcription factor" used for anything other than RNAP II. Unless the literature has changed significantly, and the word "general" is now used in the literature for RNAP I, I am against artificially applying this word to RNAP I. 

I think that trying to standardize use of the word "general transcription factor" in this way is similar to what we were recently talking about with respect to "biogenesis" where Midori tried to standardize "biogenesis" versus "assembly", but in retrospect, it turned out to be confusing because the GO use of the words were inconsistent with usage in the literature.

**Comment by pgaudet** [comment]
Hi @krchristie 

Some recent papers uses 'basal' as well as 'general' for RNA pol III (and polI for the second paper).  
PMID: 23063749
PMID: 23031840 
PMID: 20797630 uses initiation factor

Which term do you suggest we use ? 

Thanks, Pascale
