### ISSUE TITLE
Review annotations to yeast SPT4 and SPT5

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#1735]
Hello, 

Yeast SPT4 and SPT5 are described as elongation factors, but they have some annotations inconsistent with that: 

SPT5 is annotated to 
transcription factor activity, core RNA polymerase I binding 
transcription factor activity, core RNA polymerase II binding 

SPT4 is annotated to 
transcription factor activity, core RNA polymerase I binding 
transcription factor activity, core RNA polymerase II binding 

The proposed reorganization of MF for transcription proposes to restore elongation factor (see 
https://github.com/geneontology/go-ontology/issues/14790) Perhaps this would be a better MF annotation for these proteins? 

Thanks, Pascale

Also tagging @srengel as this is an SGD issue

**Comment by krchristie** [comment]
@pgaudet  Why do you think that it is inconsistent to have binding annotations for an elongation factor? There are definitely some other elongation factors that bind to the appropriate RNAP, e.g. TFIIS (gene name = Dst1 in cerevisiae).

**Comment by krchristie** [comment]
@pgaudet - I have neither access nor authority to review SGD annotations, so perhaps you should assign @srengel instead of me.

**Comment by pgaudet** [comment]
Hi @krchristie (and @srengel ) 

For me the. binding is fine. I don't think the 'transcription factor activity' is correct; transcription elongation factor activity seems more appropriate. We proposed to restored that term. In this case you could then make 2 annotations, one to elongation factor activity, and one to core RNA polymerase binding. 

Does that seem OK ? 

Thanks, Pascale

**Comment by krchristie** [comment]
The term "transcription elongation factor activity" isn't very specific as to the function, but only to the process. There are many different mechanisms of being a transcription elongation factor, some of which bind the RNA polymerase and others which do not,  so it seems we might need more than just "transcription elongation factor". Perhaps it would be appropriate to have terms like "transcription elongation factor activity, core RNA polymerase II binding" to indicate that the RNAP binding is essential to the elongation factor activity.

**Comment by pgaudet** [comment]
I see your point, but it seems like it means a function to some people. With Astrid Ruth, Marcio and Colin we proposed this definition: 
"Mediating the transition from transcription initiation to transcription elongation, and sustaining the elongation. "

Hopefully that's more specific - suggestions for improvement are welcome. 

Thanks, Pascale

**Comment by krchristie** [comment]
I am not objecting to having "transcription elongation factor activity" as a MF term, despite the fact that this alone is not distinguishable from the BP term "regulation of transcription elongation". If you are going to make these terms into functions though, perhaps you could have more specific types of txn elongation factor MF terms, including the ones that act by binding the RNAP.

Even in that definition you list above, you are describing two different things, the ones that help the transition from initiation to elongation and the ones that act later to sustain elongation.

**Comment by ValWood** [comment]
I am objecting to the term "transcription elongation factor activity" ;). I don't think it is helpful.

It is as @krchristie  says, indistinguishable from the process of "transcription elongation". 
Any protein involved in transcription elongation could be called a "trancription elongation factor".

Here are  the proteins annotated to transcription elongation in fission yeast:
![elongation](https://user-images.githubusercontent.com/7359272/34306044-149a6384-e739-11e7-8369-7d5a40db1814.jpg)

and these are  some of their molecular functions:


not2   3’5’ exouclease
not1   ?
caf16  ?
cph1  ubiquitin-like protein ligase activity
rpb6  DNA-directed 5'-3' RNA polymerase activity
spt4   ?
spt5   ?
spt16  histone exchange?
set2   histone methyltransferase activity (H3-K36 specific)
spt6
pin1   peptidyl-prolyl cis-trans isomerase activity
cdc73  ?
paf1   ?
prf1   ?
leo1   RNA binding
tpr1   (protein-protein interaction domain)
eaf1   ?
ell1   ?
rsc7   ?
tho1   ?
tho2   DNA binding/RNA binding
iws1	protein binding
tfs1	DNA binsing/protein binding
bye1    ubiquitin ligase


I don't  see the value of annotating *everything* which is involved in transcription elongation to a MF term "transcription elongation factor". If we don't know the MF it should be "unknown" and just make the process annotation.
If the plan is NOT to annotate everything, how do you decide which of the "transcription elongation factors" to give this artificial MF term to?

This really demonstrates a hole in our biological knowledge, we still don't know what some of these components do.....if we knew, we should be able to make an informative MF annotation.

You could put "the process of ...."
in front of this definition 
"Mediating the transition from transcription initiation to transcription elongation, and sustaining the elongation. "
and it would be perfect for BP!

I have annotated  spt5 and spt6 to
MF protein binding
BP positive regulation of transcription elongation from RNA polymerase II promoter
because, right now, this is all we know.

Note also that many of these "transcription elongation factors" turn out to be involved in  RNA processing, export, and even famously tRNA modification
https://github.com/geneontology/go-annotation/issues/1270

The activity of the DSIF complex is still pretty vague:
A heterodimeric protein complex formed of Spt4 and Spt5 proteins which is expressed in eukaryotes from yeast to man. DSIF is an inhibitory elongation factor that promotes RNA polymerase II transcriptional pausing, but can also stimulate transcriptional elongation under certain conditions, and may play a role in RNA processing via its physical association with mRNA capping enzymes.

**Comment by ValWood** [comment]
Google just found this (Sept 2017)
https://www.nature.com/articles/nsmb.3465
so probably could ascribe functions to SPT5&6 now....

Although I don't know how you would define  the MF of a clamp maintaining a transcription bubble ;)

**Comment by krchristie** [comment]
@ValWood - I agree with you about the equivalence of an MF term for "transcription elongation factor activity" with a BP term for "regulation of transcription elongation", but we've already broken the principle of not duplicating BP terms in MF by adding back "transcription regulator activity".

So, if we're going to have "transcription elongation factor activity" as an MF term, then I think it needs to have child terms that start to break it down by how each functions, which might not yet be sufficiently informative, but at least start moving us in that direction. Thus, I think that terms like: 
- "transcription elongation factor activity, core RNA polymerase I binding" 
- "transcription elongation factor activity, core RNA polymerase II binding" 

would be better replacements for the existing annotations of Spt4 and Spt5 than just the uninformative "transcription elongation factor activity"

- transcription factor activity, core RNA polymerase I binding
- transcription factor activity, core RNA polymerase II binding

**Comment by ValWood** [comment]
I wasn't keen on  "transcription regulator activity" either, but this does work as a grouping term to make it easier to find the  correct molecular functions in the "transcription factors" which bind DNA or protein.

We are never going to get away from the concept of a "transcription factor" (and we have always had such a thing, in various incarnations), but there probably is not such a strong need to  have "transcription elongation factor" in the ontology (or  translation factor, splicing factor etc....). 

so I'm not sure that it should be a general principle .....unless the long term plan is to merge the MF and BP ontologies!

**Comment by krchristie** [comment]
Yes, and since transcription regualtor activity is back, I am not objecting to "transcription elongation factor activity" either. However, I don't think it should be the leaf node, but the grouping term for the different things that act as elongation factors, with more granular terms that start to tease out the different mechanisms of action.

**Comment by srengel** [comment]
forgot to update this ticket: the offending annotations were removed back in Aug2018.  closing.
