### ISSUE TITLE
Yeast DPB4 extra Molecular Function and Biological Process

### ISSUE THREAD

**Issue by keslingmj** [geneontology/go-annotation#1776]
Yeast DPB4 (Q04603) should have a molecular function added:
• 3'->5' exodeoxyribonuclease (CONTRIBUTES TO)
based on the fact that it is a subunit of the DNA polymerase epsilon (subunit D) according to the UniProtKB page http://www.uniprot.org/uniprot/Q04603

Biological Process: plays a direct role in "maintaining DNA replication fidelity".  PMID: 21124948  The molecular function by which this is not that clear.  Authors speculate that it may be via keeping replication fork processive during synthesis and 3'->5' exonucleolytic degradation in vivo.  I am just learning the GO ontology itself and can't find "maintaining DNA replication fidelity" yet, and hope you could help with that.

Michael Kesling (keslingmj)

**Comment by robnash** [comment]
Hi Michael,

Thanks for letting us know about possible additional anntotions. I decided to have a look at this item and made some but not all suggested annotations for DPB4 (and also DBP3). 

In budding yeast the epsilon DNA polymerase complex (GO:0008622) contains POL2, DPB2, DPB3 and DPB4. POL2 contains both the catalytic polymerase activity (GO:0003887; PMID:1537345 and 16369485) and the single-stranded DNA 3'-5' exodeoxyribonuclease activity (GO:0008310; PMID: 1658784). The Pol2p catalytic subunit adopts a globular domain that is flexibly connected to the rest of the complex, that has an extended structure (or tail) containing subunits Dpb2, Dpb3, and Dpb4 (PMID: 16369485). 

In assays using purified components these three subunits (Dpb2, Dpb3, and Dpb4) have been shown to have a role in DNA polymerase processivity so I annotated these as 'contributes to' DNA polymerase processivity factor activity (GO:0030337; PMID:16369485). In the paper you reference there is a also a direct measure of this activity with and without DPB3 and DPB4, so I made another 'contributes to' annotation for both DBP3 and DBP4 (PMID: 21124948). 

For the single-stranded DNA 3'-5' exodeoxyribonuclease activity (GO:0008310), using an assay for processive exonucleolytic degradation of DNA, they again see more processivity with, than without Dpb3p and Dpb4p, so I added a 'contributes to' single-stranded DNA 3'-5' exodeoxyribonuclease activity (GO:0008310; PMID: 21124948) for both subunits.

For the DNA-dependent DNA replication maintenance of fidelity (GO:0045005) term, in this paper they show that the increased mutation rate in the DPB3 DBP4 double mutant results from increased synthesis by the error-prone DNA polymerase zeta (deletion of REV3 suppresses the elevated mutation rate in the DPB3 DBP4 mutant). So I am inclined not to add this annotation as its indirect, rather than a specific function of these subunits as the absence of these subunits shifts cells to use the error prone zeta. 

Cheers,
Rob
