### ISSUE TITLE
Review fungi annotations to GO:0090399 replicative senescence and children

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go-annotation#1777]
@ValWood has asked for a 'never in fungi 'taxon restriction to be placed on GO:0090399 replicative senescence but there are three experimentally supported annotations from SGD.

https://github.com/geneontology/go-ontology/issues/14881

@srengel 
@marekskrzypek (not included under our assignee list)

Can you please review these annotations and let me know if you still wish to use this term or one of its regulation children?

The annotation review spreadsheet is here:

https://docs.google.com/spreadsheets/d/1M6zAAOopFYfbywMmb5jTuf4z8lugBAn98IURMxxhzdk/edit#gid=0

Thx.

**Comment by ValWood** [comment]
Is defined:
A cell aging process associated with the dismantling of a cell as a response to telomere shortening and/or cellular aging.

Maybe replicative cell aging?
https://www.ebi.ac.uk/QuickGO/term/GO:0001302
replicative cell aging
is what is meant?
(I still think this is a phenotype, but  the aging people  probably like the terms)

**Comment by marekskrzypek** [comment]
Right, SGD:S000004592 should indeed be GO:1900062 (regulation of replicative cell aging).

The other two, SGD:S000000482 and SGD:S000002528, are a bit more complicated. The authors of PMID:21321081 claim that "Polymerase Epsilon Is Required To Maintain Replicative Senescence" in the very title of their paper and they keep using that phrase throughout. But they define replicative senescence as "a permanent cell cycle arrest in response to extensive telomere shortening", and they do not show any "dismantling of a cell...". So I guess, they didn't use the term "replicative senescence" correctly. In that case, the two annotations should also be GO:0001302 (replicative cell aging).

Cheers,
Marek



On Jan 18, 2018, at 1:14 PM, Val Wood <notifications@github.com<mailto:notifications@github.com>> wrote:


Is defined:
A cell aging process associated with the dismantling of a cell as a response to telomere shortening and/or cellular aging.

Maybe replicative cell aging?
https://www.ebi.ac.uk/QuickGO/term/GO:0001302
replicative cell aging
is what is meant?
(I still think this is a phenotype, but the aging people probably like the terms)

**Comment by ValWood** [comment]
thanks Marek,

I'm following this up with Jurg Bahler. I think the problem is that nobody really knows (for pombe/fungi). I'll summarize later once I get answers to my recent questions.

I suspect that it might be helpful to tighten up the definition of "replicative senescence" to apply to multicellular, but  I'm still trying to figure out the  similarities/differences are.....

**Comment by ValWood** [comment]
After a few circular conversations including Jurg telling me to:
"Perhaps check in PomBase? This is my go-to place if I don't know something.."  

Eventually I got the perfect answer in the form of a a reference from this book chapter

Aging: Natural or Disease? A View from Medical Textbooks
S. Janac, B. Clarke and D. Gems

The word aging acts as a stumbling block in discussion because it has multiple
meanings that are sometimes conflated. The main, distinct meanings

are:

●● The passage of time (calendar aging).
●● Time-dependent alterations, usually in adult living organisms, but also
inert objects (age changes).
●● Cumulative deteriorative changes in adult organisms leading to pathology
and death (senescence).11–13 Senescence is one type of age change.

 
An unfortunate additional source of confusion is that the word senescence
also has a second meaning, as introduced by Leonard Hayflick, that of
cellular senescence. This refers to a specific type of cellular change where the
proliferative capacity of cells is lost and a pathogenic hypertrophic phenotype
appears. Confusion between these two meanings can, in some contexts,
be avoided by use of the term organismal senescence to contrast with cellular
senescence. However, it seems likely that the two meanings of senescence
will continue to generate confusion. Replacement of cellular senescence with
another term would solve this problem.

**Comment by ValWood** [comment]
Actually although useful these distinctions do not solve our problem. 
I think ideally we need a better def for  senesence in multicellular which appears to be distinct from yeast.

I can see that in human it is a process, as it is used to deal with cancerous cells.  For fungi I'm not sure that  replicative cell ageing  should be in GO, but I would need to read more....

**Comment by RLovering** [comment]
Hi just wanted to confirm that there is no intention to remove the term cellular senescence which is used a lot in literature describing human processes eg https://www.ncbi.nlm.nih.gov/pubmed/29042481 which describes Senescent cells withdraw from the cell cycle and do not proliferate. The prevalence of senescent compared to normally functioning parenchymal cells increases with age, impairing tissue and organ homeostasis. I am not sure I agree with the statement 'a pathogenic hypertrophic phenotype appears' the description from PMID: 29042481 seems more appropriate, but note that it is only when there is a high percentage of senescent cells that there is a problem, senescence occurs because it is advantageous to the multicellular organism for these cell not die!
Ruth

**Comment by RLovering** [comment]
not just for cancerous cell

**Comment by pgaudet** [comment]
Seems like the best solution is leave things as they stand. This is one you can probably block in pombase if needed. 

Cheers, 
Pascale

**Comment by ValWood** [comment]
The solution would not be easy anyway.

For future ref both terms refer to the same phenomena:

Cellular senescence is the phenomenon by which normal ploid cells cease to divide. In culture, fibroblasts can reach a maximum of 50 cell divisions before becoming senescent. This phenomenon is known as "replicative senescence", or the Hayflick limit.

In GO we have:
replicative senescence
Definition 
A cell aging process associated with the dismantling of a cell as a response to telomere shortening and/or cellular aging.
(this is describing what happens *after* senesence, and what  sometimes causes it, but not what it actually is).

GO:0001302   
replicative cell aging
Definition
The process associated with progression of the cell from its inception to the end of its lifespan that occurs as the cell continues cycles of growth and division. PMID:12044934
(this doesn't really define replicative ageing either).

It isn't known whether this  phenomena in yeast (or at all) is a biological process (i.e programmed), or it it is just  time-dependent deterioration.

So here the removal of cancerous cells would be a "normal process" (it fixes things which go wrong), although cancer is not  a "programmed process", removing cancerous cells is. Ageing would not be "a normal process" if it turns out not to be programmed.

Happy to close and filter...

**Comment by ValWood** [comment]
It seems that the term should at lease have the "process" it is trying to describe in the definition (A cessation of cell division?)....might be a beginning to resolve the broader issues with ageing before it gets in too much of a mess....

**Comment by ValWood** [comment]
Note:  I agree   "cellular senescence" is use a lot in the literature.
And it is a "process".  Aging is a process.

However, not all aspects of  ageing, or  cellular senescence are "biological processes"
It would be really useful to establish which aspects of senescence are the actual  processes ( a signalling pathway?, rather than the outcome (phenotype).

I can see that senescence in a multicellular organism is a programmed event  which targets specific cells to benefit the organism as a whole. 

It might be useful to define these 2 terms in such a way that one is clearly specific for human senescence and one can be used by cerevisiae for "replicative ageing".  There are clearly differences  in what they occur in response to although both are  primarily "irreversible cessation of cell division".

**Comment by vanaukenk** [comment]
@ValWood - is it okay to close this ticket?

If you have suggestions for new terms definitions, can you add them to:
https://github.com/geneontology/go-ontology/issues/14881

Thx.

**Comment by ValWood** [comment]
Well, the definition of  replicative senescence
Definition
A cell aging process associated with the dismantling of a cell as a response to telomere shortening and/or cellular aging.


is incorrect (senescence is cessation of the cell cycle...dismantling is not a requisite component (this is why senolytics are all the rage).
but   I'm happy for it to close. 

This is a term  added to describe  "multicellular senesence" of specific cells, a never in fungi taxon restriction would be useful  because this would prevent the electronic mappings we are seeing.


If  you want to leave as it is and  close I can filter locally.

v

**Comment by mah11** [comment]
Some fungi are multicellular.

**Comment by pgaudet** [comment]
@srengel See comment from @marekskrzypek  above: 


He suggests to change annotations as follows: 
>  SGD:S000004592 should indeed be GO:1900062 (regulation of replicative cell aging). 
(...) 
> SGD:S000000482 and SGD:S000002528: The authors of PMID:21321081 (...) didn't use the term "replicative senescence" correctly. In that case, the two annotations should also be GO:0001302 (replicative cell aging). 

Do you agree with this? And if you do, can you change the annotations accordingly ? 

Thanks, Pascale

**Comment by srengel** [comment]
hi sure i'll take a look.

**Comment by srengel** [comment]
ok i changed the 3 SGD annotations in P2GO just now.  thanks @marekskrzypek for looking up the necessary info.  that made it super easy. :)

**Comment by pgaudet** [comment]
Thanks!
