### ISSUE TITLE
UniProtKB-KW:KW-0570 pentose phosphate shunt indirect for triosephosphate isomerase?

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1791]
http://www.uniprot.org/uniprot/P07669

**Comment by sylvainpoux** [comment]
Again a complex case. May I ask you to contact either Catherine Rivoire (Catherine.Rivoire@sib.swiss) or Elisabeth Coudert (Elisabeth.Coudert@sib.swiss) for this because there are many prokaryotes in this family?
If Elisabeth and Catherine are not on Github, it will be a good opportunity for them to register

**Comment by deustp01** [comment]
TPI generates and consumes a molecule that is one of the participants in the pentose phosphate pathway, but it does so as part of the processes of glycolysis and gluconeogenesis. That may be an arbitrary boundary dividing a continuous reaction network but it is an old and as far as I know universally accepted one, at least for eukaryotes. Even for prokaryotes, glycolysis and variants of it are very ancient and TPI activity is part of all of them. Allowing this puts you at the start of a reasoning process whereby everything is more or less directly part of everything.

**Comment by ValWood** [comment]
@pgaudet  could you add Catherine and Elisabeth to GitHub ss?

**Comment by pgaudet** [comment]
Catherine removed the KW in the entries from this family. I'm closing this.
