### ISSUE TITLE
 IPR000182 elongator not acetyltransferase

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1805]
This is one that keeps bouncing back...

**Comment by ValWood** [comment]
See
https://github.com/geneontology/go-annotation/issues?q=is%3Aissue+elongator+is%3Aclosed

**Comment by asangrador** [comment]
This entry matches Elongator complex protein 3,  a catalytic subunit of the RNA polymerase II elongator complex, which is a major histone acetyltransferase. That does not seem wrong. Is there any other elongator protein it should not be matching?

**Comment by ValWood** [comment]
It isn't thought to be a histone transferase, its a  involved in modification of wobble nucleosides in tRNA.

There are quite a lot of papers on it post ~2005 

This is the complex
https://www.pombase.org/term/GO:0033588

The current def of elongator
Definition
A heterohexameric protein complex that is involved in modification of wobble nucleosides in tRNA. The complex can associate physically with hyperphosphorylated RNA polymerase II; it contains two discrete heterotrimeric subcomplexes. Source: PMID:23165209, PMID:17018299, GOC:vw, PMID:15769872, GOC:bhm, PMID:11689709, PMID:18755837, GOC:jh, PMID:11435442, GOC:mah
Comment
Despite its name, this complex is no longer thought to be directly involved in transcriptional elongation (PMID:23165209).

see this paper and other recent ones
https://www.ncbi.nlm.nih.gov/pubmed/23165209

**Comment by ValWood** [comment]
More info in
https://github.com/geneontology/go-annotation/issues/1806

**Comment by asangrador** [comment]
Interesting! Because Elongator complex protein 3 (Elp3) does have a GNAT (N-acetyltransferases) domain, which is precisely what IPR000182  is describing and it is backed by literature [PMID:29332244]. This domain is not involved in histone acetyltransferase activity, but it could have a role  in 5carboxymethyluridine modification through an unprecedented chemistry performed on acetyl-CoA [according to PMID:25151136]. It seems that the function of the domains of Elp3 is not exactly known.

I will make a note for this one. The UniProt annotation should be changed if possible, as still talks about  histone acetyltransferase activity.

**Comment by ValWood** [comment]
Yes its a great example of where it's really difficult  to  implement the new information and mothball the old. It's like playing Whac-A-Mole, I think I've got them all and they resurface...
I'll mail UniProt...
