### ISSUE TITLE
SPKW to covalent chromatin modification

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1808]
covalent chromatin modification Source: UniProtKB-KW

remove from
 mis16 http://www.uniprot.org/uniprot/O94244
hip1 http://www.uniprot.org/uniprot/P87314
hip4 (hpc2) http://www.uniprot.org/uniprot/O43083

**Comment by ValWood** [comment]
slm9 http://www.uniprot.org/uniprot/O74309
fub1 http://www.uniprot.org/uniprot/Q9UTI1

**Comment by sylvainpoux** [comment]
A problem of mapping. These proteins are regulators of chromatin and mapping to 'GO:1902275 regulation of chromatin organization' would be more appropriate. 
@ggeorghiou  George, could you have a look and change the mapping if you reach same conclusions?

**Comment by sylvainpoux** [comment]
We have no choice: if we map the Chromatin organization KW to "chromatin organization", you will have many false positives. In this perspective, having regulation in the mapping is much safer

**Comment by ValWood** [comment]
It's the other way around, because  annotations to "regulation" are automatically annotated to the parent. "regulation of x" is a more specific annotation.

**Comment by sylvainpoux** [comment]
ok, then it is a question of ontology. I guess George @ggeorghiou will be more accurate then me

**Comment by ggeorghiou** [comment]
Right, I'll have a look at these today.

**Comment by ggeorghiou** [comment]
@sylvainpoux @ValWood I've looked at this and I'm inclined to agree with Sylvain about changing the mapping to GO:1902275 regulation of chromatin organization since it would be a safer fit. Electronically generated annotations from keyword mappings are always more conservative in terms of the granularity of the term they will use, hence why I agree with Sylvain that switching the mapping to GO:0006325 chromatin organization is not a good idea since everytime the keyword is used it's implying that the gene product is directly involved in the process, whereas the keyword can either mean direct involvement or regulation of that particular process. 

However when you look at the GO graph, you see that indeed GO:1902275 is a more specific term than GO:0006325 chromatin orginization. But this is completely dependent upon how you traverse up the graph by relationship (see GO graph below). 

@ValWood what exactly are your concerns with switching this mapping to GO:1902275? 

![image](https://user-images.githubusercontent.com/21035247/36101635-caf82eae-1001-11e8-9202-c8d14b6d2587.png)

**Comment by ValWood** [comment]
Hi,

http://www.geneontology.org/page/go-annotation-conventions

Guideline 2: If you aren't sure, consider annotating to the parent process term.
If the gene product performs one of the functions, annotate directly to the process. If the gene product regulates then it should be annotated to regulation of that process. If you aren't sure what term to use, annotate to the parent process term. As more information about the process becomes available, you may be able to refine your annotations (see Guideline #4 below).

I.e if you don't know that it is definitely regulating, annotate to the parent.

**Comment by ggeorghiou** [comment]
Right, in that case, lets stick with the guidelines and change it to chromatin organization. @sylvainpoux is this ok?

**Comment by sylvainpoux** [comment]
yes, it is ok
Thanks
