### ISSUE TITLE
IPR005700 GO:0006859 extracellular carbohydrate transport 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#1811]
Hello, 

Just wondering if this mapping is right (IPR005700 + GO:0006859 extracellular carbohydrate transport). It seems like 'carbohydrate export' (to the extracellular region) is what was intended ? 

Thanks, Pascale

**Comment by EBI-Hsinyu** [comment]
Hi Pascale, 
This is a quite old entry. Several papers have been published since then. This group of protein are mostly like involved in polymerization and secretion of exopolysaccharides. I have updated the entry and replaced it with the "GO:0045226 extracellular polysaccharide biosynthetic process". Thank you. 
Hsin-Yu

**Comment by pgaudet** [comment]
Thanks @EBI-Hsinyu, 

From looking at these papers, do you think the process 'extracellular carbohydrate transport ' exists ? Sounds like it's just confusing, I am leaning towards obsoleting it.

Thanks, Pascale

**Comment by EBI-Hsinyu** [comment]
Hi Pascale, 
I believe it is possible to use this term if some proteins are identified as exopolysaccharide transporters. Having said that, we haven't give this term to any of our entries after we deleted this term from IPR005700. This group of transporters have not been clearly characterised. 
Hsin-Yu
