### ISSUE TITLE
nucleocytoplasmic transporters annotated as transmembrane transporters

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1840]
see
http://amigo.geneontology.org/amigo/gene_product/IntAct:EBI-13941962

possibly others
(transmembrane transport is for transport  *across* a membrane. In nucleocytoplasmic transport no membrane is crossed.

@bmeldal

**Comment by bmeldal** [comment]
Thanks, Val. I'll check all nucleocytoplasmic transporters, I was probably consistently incorrect!

**Comment by bmeldal** [comment]
I check all complexes annotated to GO:0031074 nucleocytoplasmic transport complex and none have co-annotations to GO:0071806 protein transmembrane transport. I may have fixed them since the last release but our tool doesn't log every change (at least no visible to me, maybe in a backend log). So I think they are all fine but GO maybe pulling in an old file. We are really busy working on the fixed GPAD anyway so hopefully it'll all be nice and shiny after the next or next but one release!

**Comment by ValWood** [comment]
Hi Birgit. I think it comes from a Function term and then a Function process link....

**Comment by ValWood** [comment]
it was
protein transmembrane transporter activity
and
protein import into nucleus, translocation

protein transmembrane transport was an IEA.... from GO:0008320




--
