### ISSUE TITLE
human CRB1 not nucleocytoplasmic transport?

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1853]
This paper is about CRM1 the exportin?
https://www.uniprot.org/citations/21378169

**Comment by RLovering** [comment]
Sorry but I had no idea from this ticket what the problem is. Please be more specific so that I can easily understand what the problem is and what you would like me to do about it.
ie it would have been very helpful if you had said 'you have annotated CRB1 instead of CRM1 please check the ID and paper' 

Will update

Ruth

**Comment by ValWood** [comment]
That is what I said?

**Comment by RLovering** [comment]
yes but I weirdly I was thinking - hey what is the problem with annotating exportin with export of proteins? instead of thinking - why have we annotated CRB1? Our minds all work differently and it just took me about 10 min to see where the problem was. lol

**Comment by ValWood** [comment]
I know  Ruth-  it was a crap  ticket  but I submitted > 20 tickets last night and I was getting grumpy. I'm not trying to piss people off  people honestly!
