### ISSUE TITLE
Review annotations to 'signal transducer activity' and children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#1899]
Dear all, 

In the context of the MF refactoring project, it has been decided to obsolete the following terms: 
https://github.com/geneontology/go-ontology/issues/14232

**1.  GO:0004871 signal transducer activity** 
https://docs.google.com/spreadsheets/d/1b7hC9GXCYcetawuECYjvwfTpug6maSxlU2bUJ1QVOQc/edit#gid=0

**Manual annotations (EXP and others):** 
* AgBase @jinhuiz
ARUK-UCL @RLovering 
AspGD
BHF-UCL @RLovering 
CGD @marekskrzypek
dictyBase  @pfey03 
EcoCyc @keseler 
EcoliWiki @sandyl27 
FlyBase @hattrill 
GeneDB @fatimasilva
GR
JCVI
MGI @ukemi 
PINC
PomBase @ValWood 
RGD @slaulederkind 
~~SGD~~ done 
TAIR @tberardini 
TIGR 
UniProt @ggeorghiou 
WB @vanaukenk 

**Mappings**
* 48 InterPro (see google spreadsheet
* Unirule @pedruzzi 
UniRule:UR000046415

----
**2. 'GO:0005057 signal transducer activity, downstream of receptor'**
https://docs.google.com/spreadsheets/d/1-VGm5XqimP4hZISvzaFhXy4ENTcSvyzIAsG1-USr9Vk/edit#gid=0 

**Manual annotations (EXP and others):** 
* AgBase @jinhuiz
MGI @ukemi 
PINC
RGD @slaulederkind 
UniProt @ggeorghiou 
WB @vanaukenk 

**Mappings**
InterPro:IPR003116

----
**3. 'GO:0004716 signal transducer, downstream of receptor, with protein tyrosine kinase activity'**
https://docs.google.com/spreadsheets/d/1_9buaOpNlbS3wDKE_O_iLhGU0w-SqwXURrXsXFqLOlg/edit#gid=0

**Manual annotations (EXP and others):** 
* BHF-UCL @RLovering 
MGI @ukemi 
PINC
RGD @slaulederkind 
UniProt @ggeorghiou 
WB @vanaukenk 

**Mappings**
* InterPro  @asangrador 
InterPro:IPR016245
InterPro:IPR027263
* UniRule  @pedruzzi 
UniRule:UR000690772

----
**4. GO:0004702 signal transducer, downstream of receptor, with serine/threonine kinase activity**
https://docs.google.com/spreadsheets/d/1TRCPm_6Aq-EFtU3b7VnsbaHrVCQIM98cQCmfXc-g2EY/edit#gid=0

**Manual annotations (EXP and others):** 
* AgBase @jinhuiz
AspGD @marekskrzypek
CGD @marekskrzypek
FlyBase @hattrill 
MGI @ukemi 
PomBase @ValWood 
RGD @slaulederkind 
~~SGD~~ done
TAIR @tberardini 
UniProt @ggeorghiou 
WB @vanaukenk 
ZFIN @sabrinatoro 

**Mappings**
* InterPro  @asangrador 
InterPro:IPR000333
InterPro:IPR028749
* UniRule  @pedruzzi 
UniRule:RU361271
UniRule:UR000135868
UniRule:UR000136826

----
**5. GO:0004728 signal transducer, downstream of receptor, with protein tyrosine phosphatase activity**
https://docs.google.com/spreadsheets/d/1rlPKSX-5H4xKJ8BqAP8fDmmeXGD8LsHnVIywZi-r3h0/edit#gid=0

**Manual annotations (only EXP):** 
* MGI: @ukemi 
* Flybase: @hattrill 

**No Mappings**

----
**6. GO:0009400 signal transducer, downstream of receptor, with serine/threonine phosphatase activity**
https://docs.google.com/spreadsheets/d/1jrVjxzveCVpFec0Q3kgT0NJz5z5xnhdYC2U4we9ZSE0/edit#gid=0

**Manual annotations (only EXP):** 
* CACAO @sandyl27

**No Mappings**

----
Please review your annotations - delete or move to a different term. 
Remove your name from the assigned list when done. 

Thanks, 

Pascale

**Comment by ValWood** [comment]
have done... 
GO:0005057 | signal transducer activity, downstream of receptor
was used for  Greatwall kinase pathway
because it provided a link  to signaling (process) where plain "serine/threonine protein kinase doesn't." 
 but the "signalling" annotation will be addressed by
https://github.com/geneontology/go-ontology/issues/13095

**Comment by ValWood** [comment]
also removed:
git11 | ↑is_a GO:0005057 | signal transducer activity, downstream of receptor

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete GO:0004871 signal transducer activity and children:  

GO:0005057 signal transducer activity, downstream of receptor
GO:0004716 signal transducer, downstream of receptor, with protein tyrosine kinase activity
GO:0004702 signal transducer, downstream of receptor, with serine/threonine kinase activity
GO:0004728 signal transducer, downstream of receptor, with protein tyrosine phosphatase activity
GO:0009400 signal transducer, downstream of receptor, with serine/threonine phosphatase activity

The reason for obsoletion is that in the Molecular Refactoring project we have noticed that this term was not clearly defined and it was not providing a useful grouping. 
    
There are many annotations and mapping to these terms; all groups should loook at the annotation review ticket:
https://github.com/geneontology/go-annotation/issues/1899

The good news is that most of the gene products are also annotated to other molecular functions, so that choosing a better term should be relatively straignt forward.      
    
Any comments can be added to this issue: https://github.com/geneontology/go-ontology/issues/1899
    
We are opening a comment period for this proposed obsoletion. I’ll leave tis open for longer than usual to give people some time to review annotations. 
    
Thanks,

Pascale

**Comment by sandyl27** [comment]
I changed 6. GO:0009400 signal transducer, downstream of receptor, with serine/threonine phosphatase activity to the parent term on CACAO.

**Comment by pgaudet** [comment]
(Note that I was unable to assign everyone- GH limits to 10)

**Comment by RLovering** [comment]
@BarbaraCzub

**Comment by RLovering** [comment]
Hi Pascale

what about O15169 AXIN1 ? it is currently annotated to GO:0030159 receptor signaling complex scaffold activity but this term is not associated with a signal transduction term

Ruth

**Comment by RLovering** [comment]
Also gap junctions? should they be considered to be involved in signal transduction

**Comment by bmeldal** [comment]
280 complexes to check - ouch!
I won't get to it til late April.

**Comment by hattrill** [comment]
Dumped ours (all bar one, non-experimental).

**Comment by pfey03** [comment]
Took care of the Dicty annotations, all deleted in P2GO

**Comment by tberardini** [comment]
Ok, dumped ours after review.  I was able to find some better annotations for some.

**Comment by pgaudet** [comment]
Hi @RLovering 
If I understand you would like 'GO:0030159 receptor signaling complex scaffold activity' to be linked to a signal transduction term - if that's the case please create a new ticket (that being said, if the function is 'scaffold', is it really involved in signaling?)

**Comment by ValWood** [comment]
> that being said, if the function is 'scaffold', is it really involved in signaling?

I has always wondered about this, but we annotated them to signaling because otherwise, I'm not sure what process we would use?

**Comment by RLovering** [comment]
Hi

We did discuss scaffold proteins in the signaling meeting. https://docs.google.com/document/d/1wCzCkPL9ft20ZP5XnTn8IQAcxoFEduaBmzVWKN0hbU0/edit#heading=h.91lt0pk9qmy 

the minutes state:
MF: MAP-kinase scaffold activity 
Issues: where is it in the pathways? 
Is it regulating or is it upstream of the pathway? 
Resolution: A scaffold protein regulates the pathway.
The scaffold protein brings the proteins of the pathway together
 “directly positively regulates” the pathway

So I guess that means that the scaffold proteins are not signal transducers. I will update the AXIN1 annotations.

**Comment by RLovering** [comment]
any thoughts on gap junction proteins involved in electrical signal transduction?

**Comment by ukemi** [comment]
I think we need to be cautious here. I think making a blanket statement about all scaffold proteins based on the MAPK scaffold proteins might be dangerous. In the case of the MAPK scaffold proteins, a literature review indicated that the scaffold controlled the signaling pathway, not only by bringing necessary components together but also by regulating which components were recruited to the pathway. The survey of papers also showed that the MAPK community thinks of the scaffolds as being regulatory molecules. I'm not sure this will be the case for all scaffolds that constitutively hold protein complexes together.  @sabrinatoro ?

**Comment by sabrinatoro** [comment]
@ukemi I agree with everything you said: in the case of the MAPK signaling, the scaffold proteins are necessary to bring the components together and to regulate the pathways. 
I don't think it is the case for all scaffold proteins though (to bring protein together AND regulate pathways).

**Comment by RLovering** [comment]
I guess I was thinking the other way, is it possible to consider that adaptor proteins are scaffold proteins?

**Comment by ValWood** [comment]
I  have been thinking about this for a while.... 

So David says "In the case of the MAPK scaffold proteins, a literature review indicated that the scaffold controlled the signaling pathway, not only by bringing necessary components together but also by regulating which components were recruited to the pathway"..... but isn't this what all "signalling scaffolds" do?  They are all providing binding sites to bring together the signalling molecules.


For example the SIN signalling scaffolds
cdc11 https://www.pombase.org/gene/SPCC1739.11c
sid4 https://www.pombase.org/gene/SPBC244.01c

MAPK scaffolds
ahk1 https://www.pombase.org/gene/SPAC7D4.03c

cdc42 scaffold
Scd2 https://www.pombase.org/gene/SPAC22H10.07

numerous WD repeat proteins in signalling pathways  which  are basically protein-protein interaction molecules...
git5 https://www.pombase.org/gene/SPBC32H8.07
gnr1 https://www.pombase.org/gene/SPCC1020.09

for the mitotic  spindle checkpoint:
bub3 https://www.pombase.org/gene/SPAC23H3.08c

Most (if not all) of these have a role in "recruitment". They are often annotated to a mixture of "binding" (which is clearly selective and dependent on modification events), localization of x (other subunits), or regulation of the signalling pathway....


It would be great if the signalling  group resulted in good guidelines for this. For example is the "scaffold" really regulating  (or the gene product that is modifying the scaffold?)

Or does this depend on the timing? I know more  about the  role of the Scaffold  in the SIN pathway than in the MAP kinase pathway. Here I would say that the scaffold wasn't "regulating"
anything per se, but it is part of the signalling pathway, but not a signal transducer.  It isn't regulating signalling  because the this  regulated by an upstream kinase cascade (although it is involved in the signalling).
Is the MAP kinase scaffold different? How does the scaffold regulate the signalling pathway in this case?

**Comment by ValWood** [comment]
Here is a question about scaffold  from back in 2016 using SIN as an example
https://github.com/geneontology/go-ontology/issues/12704

Obviously signalling is  *affected* in SIN mutants because the pathway components are not localized correctly. However in a normal cell the scaffold does not affect the timing of events. This is determined by the upstream kinase plo1

**Comment by ValWood** [comment]
@Antonialock

**Comment by slaulederkind** [comment]
All RGD manual annotations removed.

**Comment by RLovering** [comment]
Hi

I think there are a lot of good points raised here about scaffold proteins. 
I have raised 2 tickets about the ontology in this domain here:
https://github.com/geneontology/go-ontology/issues/15509
https://github.com/geneontology/go-ontology/issues/15510
One of the key items in the second ticket is that GO:0005068 transmembrane receptor protein tyrosine kinase adaptor activity has parents for both the process 'signaling pathway' and 'regulation of signaling pathway'

The term 'regulation' is used inconsistently by authors of papers and it is therefore often difficult for curators to be guided by authors wrt whether a gene product (gp) is involved in 'regulation of a process' or the 'process' itself. I would therefore like to see clear guidelines about whether an adaptor is regulating or part of a signaling process. I also think it is too simplistic to decide if something is regulating a pathway based on whether anything else regulates the pathway. Signaling pathways can be regulated by multiple gps/pathways/times therefore an upstream regulation event does not rule out subsequent regulation events.

However, if a adaptor is required to enable the appropriate proteins to form a complex so that this complex is then able to 'signal' then this adaptor could be considered part of the signaling pathway. Perhaps the adaptor could be considered part of the pathway if it shown that the adaptor is modified by one of the 'true' signaling components and that this modification is required for another signaling component to join the complex (or to be activated). ie the modification of the adaptor is one of many steps in the signaling process.

**Comment by pgarmiri** [comment]
All UniProt annotations have been reviewed. A couple are still awaiting action from curators at SIB. Actions taken for each annotation are reported in the spreadsheets.

**Comment by pgaudet** [comment]
Hi @pgarmiri 
In this page there are non-EXP UniProt annotations that haven't been dealt with: 
https://docs.google.com/spreadsheets/d/1b7hC9GXCYcetawuECYjvwfTpug6maSxlU2bUJ1QVOQc/edit#gid=0 (you may want to ignore them, I just wanted to make sure you knew)

Thanks, Pascale

**Comment by ukemi** [comment]
Hi @pgaudet,
When I first went through my set, I missed the non-experimental ones too. Maybe it is not a good idea to split them out this way.

**Comment by pgaudet** [comment]
Right ! I'll keep that in mind.

**Comment by pfey03** [comment]
I had missed one TAS annotation (to carB) and removed that

**Comment by vanaukenk** [comment]
I've updated the WB annotations.

**Comment by pgarmiri** [comment]
Hi @pgaudet ,
As far as I can see, in the particular spreadsheet, there are no non-experimental annotations assigned by UniProt.
In some of the other spreadsheets, there were some TAS, NAS and ISS. I have dealt with all the TAS and NAS ones. I haven't touched the ISS ones as they will be updated according the experimental master that have been already taken care of. 
Please, let me know if I have missed some.
Thanks,
Penelope

**Comment by BarbaraCzub** [comment]
I've update the ARUK-UCL annotations.

**Comment by suzialeksander** [comment]
SGD annotations are done.

**Comment by pedruzzi** [comment]
UniRules done:

UniRule:UR000046415 done
UniRule:RU361271    done
UniRule:UR000135868 done
UniRule:UR000690772 sent to PIR for review
UniRule:UR000136826 sent to PIR for review

**Comment by ukemi** [comment]
MGI is complete. Anything left comes in through a load and should stop once the source annotations are corrected.

**Comment by pgaudet** [comment]
Closing the ticket. If there are remaining annotations to that term, the reports will show it. 
Thanks everyone ! 

Pascale
