### ISSUE TITLE
Associate GO term with InterPro alpha carbonic anhydrase signatures

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#1902]
None of these InterPro signatures appear to have an associated GO term:
Alpha carbonic anhydrase (IPR001148)
Carbonic anhydrase, alpha-class (IPR023561)
Alpha carbonic anhydrase superfamily (IPR036398)

Their descriptions all refer to EC:4.2.1.1, so I'd suggest this GO term should be associated with each:
carbonate dehydratase activity (GO:0004089)
(probably other GO terms could/should be added too....)

(Note, this InterPro term already makes this GO association:
Carbonic anhydrase, alpha-class, conserved site (IPR018338) )

**Comment by sjm41** [comment]
tagging @hattrill

**Comment by asangrador** [comment]
Thanks for pointing out this. I have added the term carbonate dehydratase activity (GO:0004089) to Carbonic anhydrase, alpha-class (IPR023561).  It can not be added to the other two entries because they represent  carbonic anhydrase domains, which are also present in receptor-type tyrosine-protein phosphatases zeta and gamma, where it does not seem to have this activity [PMID: 8382771]. I will update the entries to explain this.

**Comment by vanaukenk** [comment]
Thanks, @asangrador 
Can we close this ticket?
