### ISSUE TITLE
Annotation review: IGI + ISS with a protein-containing complex in the 'with' field

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#1925]
Hello, 

From this ontology ticket: 
https://github.com/geneontology/go-ontology/issues/15421

We need to make rules for what evidence can be used for annotations having a protein-containing complex in the 'with' field (ie, an IntAct complex). Here's a list of annotations with IGI as an evidence code; these seem suspicious, I really thought that IGI involved 2 genes. 

IGI Annotations are here: 
https://www.ebi.ac.uk/QuickGO/annotations?withFrom=IntAct&evidenceCode=ECO:0000316&evidenceCodeUsage=descendants (I don't know how to make that query in AmiGO - @kltm can you help? )

ISS annotations: 
https://www.ebi.ac.uk/QuickGO/annotations?withFrom=IntAct&evidenceCode=ECO:0000250&evidenceCodeUsage=descendants

All annotations are from BHF. 

Thanks, Pascale

**Comment by RLovering** [comment]
Hi Pascale

actually these are ARUK annotations (@BarbaraCzub). I will discuss these with Barbara when she returns from holiday. I hadn't appreciated that this was being done.

Best 

Ruth

**Comment by BarbaraCzub** [comment]
Hi @pgaudet,

I am going to address your IGI query, and @RLovering will comment on the ISS.

When I click on the IGI link you provide, the first paper that comes up is PMID:23164821. 

This study uses amyloid-beta-25-35 fragment of the amyloid-beta peptide. This fragment aligns with residues 25-35 of amyloid-beta-1-40 and amyloid-beta-1-42. According to the Sigma-Aldrich record this sequence corresponds to “Functional domain of Aβ required for both neurotrophic and neurotoxic effects.” (http://www.sigmaaldrich.com/catalog/product/sigma/a4559), i.e. it is intented to illustate the roles of amyloid-beta, rather that full-length APP.

So in order to annotate the effects of this fragment I used the UniProt PRO_xxx identifiers for amyloid-beta-1-40 and amyloid-beta-1-42 peptides, and the Complex Portal identifiers for Amyloid-beta protein 40/42 oligomeric complex and Amyloid-beta protein 42 oligomeric complex (the paper discusses the effects of amyloid-beta oligomers). (An identifier for the Amyloid-beta protein 40 oligomeric complex was not available at the time of annotation).

This is the reason why there are four different identifiers in the 'with' field, including two Complex Portal identifiers. This is the only way to capture this information, given the fact that an amyloid-beta-25-35 peptide fragment was used for the study.

The next three papers in this list of annotations, PMID:24658113, PMID:22198949 and PMID:22500019, describe the effects of amyloid-beta oligomers specifically, therefore, only the Complex Portal identifier was used in the 'with' field. (The experimental methods were described in sufficient details in these articles, so that there was no ambiguity about the components of the experimental mixture).

I have not looked at papers further down the list, but from glancing at the contents of the 'with' column, I infer these annotations were based on similar experimental details.

With regard to your comment about the IGI evidence involving only two genes, the guidelines state that this evidence code is used to describe the effects of "more than one gene", or "two or more genes" (http://wiki.geneontology.org/index.php/Inferred_from_Genetic_Interaction_(IGI)).

Please let me know, if you have any more questions about these annotations.

Thanks,
Barbara

**Comment by RLovering** [comment]
Hi Pascale. 

I have discussed the ISS and IGI with Barbara and Rachael. Barbara will write about the IGIs.

We feel that it is appropriate to create ISS annotations for the complex IDs as long as we have checked the orthology for each of the subunits. Which has been done for all of those we have annotated. You might want to look at creating guidelines for this and also discuss with Birgit whether she is creating GO annotations for complex IDs to multiple species complexes when there is only evidence of the BP/MF etc in one species. All complex portal GO annotations are imported to GO with IPI evidence so perhaps she doesn't do this. @bmeldal 

Best

Ruth

**Comment by pgaudet** [comment]
Hi @BarbaraCzub I dont think this is what a genetic interaction means ? 

@RLovering I note your comment on ISS, we'll take that into account that with @vanaukenk when updating the documentation on ISS. 

Thanks, Pascale

**Comment by pgaudet** [comment]
'IDA' and 'contributes to?

**Comment by BarbaraCzub** [comment]
Protein2GO does not allow for this.

The error message is: "Qualifier not valid for biological_process term".

<img width="1245" alt="screen shot 2018-04-12 at 14 37 02" src="https://user-images.githubusercontent.com/16541096/38680838-32b7af2a-3e5f-11e8-8bbf-73dad26ce1ac.png">

**Comment by pgaudet** [comment]
OK @vanaukenk says this is ok according to the guidelines. Thanks for checking ! 

Pascale
