### ISSUE TITLE
glycerate kinase activity PANTHER:PTN000815317	

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1945]
mug58 | GLYK family kinase of unknown specificity (predicted) |   

has
| glycerate kinase activity |PANTHER:PTN000815317	

http://amigo.geneontology.org/amigo/gene_product/PomBase:SPAC630.09c

also has

PANTHER:PTN000032154 from PANTHER:PTN000032154
which is much more likely:

current:
https://www.pombase.org/gene_subset/interpro:PANTHER:PTHR10285

Do the Panther family IDs change?

**Comment by pgaudet** [comment]
Hi @ValWood 

Yes some nodes can move to a different PTHR family.

**Comment by pgaudet** [comment]
So does that take care of the problem?

**Comment by ValWood** [comment]
I don't know, it's currently in Amigo. we get our PANTHER from InterPro. I would expect we are more behind than PANTHER ;)

So if 
glycerate kinase activity PANTHER:PTN000815317
is still on  SPAC630.09c Q9UUH3 it would need removing?

**Comment by pgaudet** [comment]
There is no annotation to 'Glycerate kinase activity' in that tree - was removed by PAINT touchup because primary annotations were removed. 

There *is* some pipeline problem with PAINT annotations - someone old annotations are not stripped, which is quite confusing. This is a known issue that will hopefully get fixed within the next weeks.
