### ISSUE TITLE
Review annotations to ELP3 Q9H9T3 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#1965]
Hi @RLovering 

Following up on #1806 
human ELP3 Q9H9T3  is annotated to histone acetyltransferase activity
and
regulation of transcription from RNA polymerase II promoter

This seems to be incorrect based on newer findings. 

Can you please check and remove the annotations as appropriate? 

Thanks, Pascale

**Comment by RLovering** [comment]
Hi Pascale
I was about to delete these but thought I would check how it is described in UniProt. From there I went to Pubmed, PMID: 22216241 states: On the contrary, these functions are lost when the HAT domain is deleted from hElp3. These data suggest that hElp3 can regulate the transcription of HSP70 gene, and the HAT domain of hElp3 is essential for this function.  

So it seems like the HAT annotations should stay. What is your reason for deletion?

Thanks

Ruth

**Comment by pgaudet** [comment]
@RLovering - I think "these function" refer to transcriptional elongation, not to 'histone acetyltransferase activity' and 'regulation of transcription from RNA polymerase II promoter', ist his right ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
@ValWood initially requested this --- I'll have a look but meanwhile Val if you can also have a look, that'd be great. 

Thanks, Pascale

**Comment by pgaudet** [comment]
Histone acetylation seems to be a well-known role of Elp3, see https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3630180/figure/F1/

**Comment by ValWood** [comment]
I  checked  all of the older papers  used in annotation and they all seemed to be "phenotypes" . In yeast all of the  elongation related phenotypes have been shown (at least in yeast) to be a consequence of  the effect on tRNA modification.  The histone acetylation, although  if I remember, was shown in vivo does not appear to be functionally relevant.

Here are some more recent papers for human
https://www.ncbi.nlm.nih.gov/pubmed/29497044
https://www.ncbi.nlm.nih.gov/pubmed/29415125

I can go back though this again, but I won't have time before the meeting.

**Comment by ValWood** [comment]
look at this
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4615193/

**Comment by ValWood** [comment]
there is some history in this ticket
https://github.com/geneontology/go-annotation/issues/1806

**Comment by ValWood** [comment]
and this one
https://github.com/geneontology/go-annotation/issues/1805

it does have a GNAT  domain but
This domain is not involved in histone acetyltransferase activity, but it could have a role in 5carboxymethyluridine modification through an unprecedented chemistry performed on acetyl-CoA [according to PMID:25151136]

**Comment by ValWood** [comment]
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3630180/figure/F1/

figure legend says:
note  the words "proposed"
"The lower panel highlights tRNA modification (translational control) and histone acetylation (transcriptional control) as Elongator’s proposed cellular functions."


Figure 1. Elongator complex assembly and its proposed cellular functions. The upper panel shows a schematic representation of the Elongator subcomplex arrangement. The central hexameric Elp456 subcomplex is shown in cartoon representation (Elp4 in green; Elp5 in blue; Elp6 in brown) and is flanked by two copies of the Elp123 subcomplex. Predicted domains in Elp123 are marked individually (WD40 domains, tetratricopeptide repeats (TPR); histone acetyl transferase (HAT); radical S-adenosyl-methionine (rSAM); iron-sulfur cluster - FeS). The lower panel highlights tRNA modification (translational control) and histone acetylation (transcriptional control) as Elongator’s proposed cellular functions. Additional functions, which were shown to be indirectly affected by Elongator role in tRNA modifications are DNA damage response,44 telomeric gene silencing,44 exocytosis,16 cell cycle regulation,35 transcriptional activation16 and chromatin remodeling.16 Functions that could indirectly result from translational/transcriptional activities of Elongator or because the proteins involved are additional direct targets of Elongator such as α-tubulin/Bruchpilot acetylation12 or paternal genome demethylation15 are listed separately.

**Comment by ValWood** [comment]
this very cool paper has 
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3388810/

 A provocative finding was the fact that the transcription and histone acetylation defects, and the additional phenotypes resulting from the absence of Elongator could be suppressed by the overexpression of two tRNAs (tRNALysUUU and tRNAGlnUUG) in budding yeast, which raised some doubts about the direct involvement of Elongator in other pathways beside tRNA modifications (Esberg et al., 2006). 

https://www.ncbi.nlm.nih.gov/pubmed?holding=pombase&term=22768388

**Comment by ValWood** [comment]
The above paper does some very cool work to show how elongator regulates translational fidelityhttps://www.ncbi.nlm.nih.gov/pmc/articles/PMC3388810/
via a lysine codon usage bias in a subset of genes involved in cell cycle

**Comment by ValWood** [comment]
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3562296/
More than a decade ago, the purification of the form of the RNA polymerase II (PolII) engaged in elongation led to the discovery of an associated, multi-subunit (Elp1-6) complex named “Elongator” by the Svejstrup lab. Although further evidence supported the original notion that Elongator is involved in transcription, Elongator lacked some of the expected features for a regulator of the elongating PolII. The discovery by the Byström lab, based on genetic dissection, that Elongator is pivotal for tRNA modifications, and that all the reported phenotypes of Elongator mutants are suppressed by the overexpression of two tRNAs added to the confusion. The increasing range of both potential substrates and biological processes regulated by Elongator in higher eukaryotes indicates that the major challenge of the field is to determine the biologically relevant function of Elongator. Our recent proteome-wide study in fission yeast supports a coordinated codon-dependent regulation of translation by Elongator. Here we provide additional analyses extending this hypothesis to budding yeast and worm.

**Comment by RLovering** [comment]
Ok, I have revised these annotations, but I have been unable to work out what MF term I should associated with ELP3, whether as actual activity or as contributes_to, please could you help me here? Or should I just use the term in PomBase GO:0016746 | transferase activity, transferring acyl groups

I have put an alert in P2G on the paper record and the protein record annotated saying: the HAT activity has been disputed, some of the expt data can be attributed to tRNA modification. see https://github.com/geneontology/go-annotation/issues/1965

Thanks

Ruth

**Comment by ValWood** [comment]
We still don't know the MF.

You could annotate 

GO:0016746 | transferase activity, transferring acyl groups  but not from PomBAse. Our annotation is and I EA from a KW, does human not have this mapping?

You could maybe ISM to one of the protein families...

**Comment by ValWood** [comment]
THese annotations are still present on ELP3, along with others. I will  flag the questionable ones in P2GO  and tage this ticket. The Unipro description needs updating too.  I will mail UniPRot helpdesk for this.

**Comment by ValWood** [comment]
more historical tickets,
but there are many
https://github.com/geneontology/go-annotation/issues/1806
https://github.com/geneontology/go-annotation/issues/1805
https://github.com/geneontology/go-annotation/issues/1270

It is also confirmend in fission yeast that all elongator phenotypes can be supressed by overexression of tRNA. I checked with lots of people in the community and it's well accepted that this is not a histone acetyl transferase, even though this activity has need detected via in vitro assays

**Comment by ValWood** [comment]
from
http://europepmc.org/abstract/MED/11714725

has been doubted since 2006

 Elongator was first isolated based on its ability to coprecipitate with the elongating RNA polymerase II and to acetylate histones H3 (Winkler et al., 2002, Wittschieben et al., 1999). A provocative finding was the fact that the transcription and histone acetylation defects, and the additional phenotypes resulting from the absence of Elongator could be suppressed by the overexpression of two tRNAs (tRNALysUUU and tRNAGlnUUG) in budding yeast, which raised some doubts about the direct involvement of Elongator in other pathways beside tRNA modifications (Esberg et al., 2006). 

pre 2006 publications on elongator should be curated with caution (or probably avoided)

**Comment by ValWood** [comment]
Closing, I thik all of these elongator are fixed
