### ISSUE TITLE
	PTN000430172 septin annotations

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1980]
I don't think septin (at least for fission yeast) should be annotated to

1) septin filament array (no array observed)
2) septin complex 
3) septin ring assembly (septin is a member of the ring, so a septin ring does not assemble without it?)
~4) protein-containing complex scaffold activity IBA
septin isn't a scoffolder~ these are described as scaffolds

I think probably it isn't good to annotate much for septins.... even mitotic cytokinesis 
could be dodgy because in  some paralogs are mitotic and some are  meiotic

Although oddly I don't see these annotations here
http://www.pantree.org/node/annotationNode.jsp?id=PTN000430231

but I see them in AmiGO

**Comment by ValWood** [comment]
In fission yeast  spn1,2,3,4 are mitotic
spn2,5,6 and 7 are meiotic 
I don't  know if you can resolve these in PAINT?

I think you can do
GO:0061640    cytoskeleton-dependent cytokinesis

I wouldn't make the complex annotation because the best you can do is "septin complex" which must be just a grouping term, not a specific complex. It isn't very useful as an inference.

**Comment by thomaspd** [comment]
In the tree, fission yeast 4 and 6 group together, 1 and 5 group together, and 3 and 7 group together, so it looks like the duplications that separated meiotic from mitotic septins in fission yeast are not shared among other eukaryotes.  So I agree that we should use the more general term GO:0061640 deep in the tree.  @marcfeuermann can you please review this tree (PTHR18884) and see if you agree with making this change?

**Comment by marcfeuermann** [comment]
After checking, I agree to use the more general term GO:0061640 cytoskeleton-dependent cytokinesis.
I have also removed the terms "septin ring assembly" (indeed it is part of the ring) and "septin filament array" for which we have anyway few evidence in the whole tree. I would however keep the "septin complex" since it is annotated for almost all species for which we have experimental annotation, including fission yeast (see PMID15385632 : "Our findings indicate that Spns1-4p are present throughout interphase as a diffusely localized approximately 8.5S complex containing two copies of each septin linked together as a chain in the order Spn3p-Spn4p-Spn1p-Spn2p") .

**Comment by thomaspd** [comment]
I talked to Val and this looks good now.  Closing.
