### ISSUE TITLE
GeneDB identifiers in gene_association.GeneDB_Tbrucei

### ISSUE THREAD

**Issue by tonysawfordebi** [geneontology/go-annotation#2001]
Our import pipeline is now discarding the majority of the annotations (all bar about 20) in the http://www.geneontology.org/gene-associations/gene_association.GeneDB_Tbrucei.gz because nearly all of the identifiers have changed - they have acquired a ":mRNA" suffix, for example Tb927.5.3050:mRNA

This form of identifier doesn't match what is in http://www.geneontology.org/gp2protein/gp2protein.GeneDB_Tbrucei.gz (which is, admittedly, now pretty old) or in UniProt xrefs; neither does it match the ID regex for GeneDB in db-xrefs.yaml.

**Comment by pgaudet** [comment]
@Achchuthan

**Comment by tonysawfordebi** [comment]
I've just spotted that we have exactly the same issue with gene_association.GeneDB_Lmajor

**Comment by Achchuthan** [comment]
Thank you so much for fixing these issues @tonysawfordebi. I'll make sure these issues are sorted properly and uniprot xrefs are up-to-date before the next round of submissions.

Thanks,
Achchuthan

**Comment by tonysawfordebi** [comment]
Cool; thanks, @Achchuthan 

Can you confirm what the correct form of a GeneDB ID is, please?

Also, can you verify that the information about GeneDB in https://github.com/geneontology/go-site/blob/master/metadata/db-xrefs.yaml is correct?

**Comment by Achchuthan** [comment]
Hi @tonysawfordebi,
The GeneDB ID format varies from one organism to another . The ID syntax in https://github.com/geneontology/go-site/blob/master/metadata/db-xrefs.yaml is right. The example IDs are PF3D7_1467300 and Tb927.5.2410 from _P. falciparum_ and _T. brucei_ strain 927. The gene IDs should not contain any suffices such as ":mRNA". This was added to the gene IDs in the GAF file as these annotations were associated with transcripts rather than genes itself in the database. 

The information in the https://github.com/geneontology/go-site/blob/master/metadata/db-xrefs.yaml are right.

Thanks,
Achchuthan

**Comment by ValWood** [comment]
I presume this must be sorted or @alexsign  would have reported, so closing
