### ISSUE TITLE
mitochondrial outer membrane translocase complex assembly 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2015]
I'd like to pin down precisely what this means.

It has only 19 EXP annotation, 2 form GeneDB the rest from SGD.
(oddly the term has a label saying it was created by BHF, this isn't the case because we have been using this term for over a decade).

The SGD annotations are for these 9 gene products

These are correctly TOM complex assembly:
YLR099W-A	(Mim2),
MIM1 mitochondrial TOM complex assembly protein

These seem odd:
MDM10 ERMES complex
~MMM1 ERMES complex subunit~ is OK because it is part of SAM which is involved in TOM complex assembly
MDM12 ERMES complex subunit
TOM6 mitochondrial TOM complex subunit
TOM20 mitochondrial TOM complex subunit
TOM5 mitochondrial TOM complex subunit
SAM35 mitochondrial TOM complex subunit
SAM37 mitochondrial TOM complex subunit

At PomBase we have a different set of proteins annotated to this term, by ISS to SGD
(we did these originally with Maria, who was an expert in these processes)

mim2 | SPBC409.23 | mitochondrial outer membrane translocase complex assembly protein Mim2 (predicted)
tom13 | SPBC713.08 | mitochondrial TOM complex assembly protein Tom13 (predicted)
tom20 | SPAC6F12.07 | mitochondrial TOM complex subunit Tom20 (predicted)

So it seems that for some reason the old annotations were removed and the new annotations don't reflect the original (or current) meaning of the term.

Any input anyone?

**Comment by suzialeksander** [comment]
I'm not sure what the question is here.  Looking at a paper on the ERMES ones, PMID: 17410204:
"As the β-barrel assembly defect is observed very early (after a 30 min shift), it is obviously not a consequence of morphological alterations of the mutant mitochondria. The morphology defect is observed under conditions (90 min shift) where the steady-state levels of mature assembled TOM complex are significantly reduced. These findings support the view of a primary role of Mmm1 in β-barrel assembly."
"We found that Mdm12/Mmm1 function in the major β-barrel pathway that is responsible for biogenesis of outer membrane proteins like porin, Tom40, Sam50 and Mdm10. Mdm12/Mmm1 shift the branching point of the β-barrel pathway to a stage after the SAMcore complex."

etc.
Since this paper is mentioning Tom40, a component of TOM, I'm assuming it's more of the same.  


A Kornmann paper states "Thus, one core molecular function of the Mmm1/Mdm10/Mdm12/Mdm34 complex is to connect ER and mitochondria, which can be bypassed by expressing a synthetic tether. Henceforth, we refer to the complex as ERMES (ER-mitochondria encounter structure).", so I don't think you're asking about the C annotations just the P terms?


As for the deleted annotations, we don't have any deleted annotations for YLR099-W or the other two and I can see the annotations to this term on SGD and Protein2GO.

**Comment by ValWood** [comment]
I'm trying to establish if


mitochondrial outer membrane translocase complex assembly 
refers to 
TOM assembly.
(I think it does)

But is so, the annotation seem odd, because the TOM complex subunits are not involved in the assembly of itself ? Those might be a phenotype that the complex does not assembly if a subunit is mutated but this isn't part of the process of TOM complex assembly.


I can't figure out the statement:
We found that Mdm12/Mmm1 function in the major β-barrel pathway that is responsible for biogenesis of outer membrane proteins like porin, Tom40, Sam50 and Mdm10. 

because according to current annotation Mdm10 is not in the same complex as Tom40?


I'm not sure about Ermes, although I think these ar likely to be phenotypes.
But these do seem odd don't you think:

TOM6 mitochondrial TOM complex subunit
TOM20 mitochondrial TOM complex subunit
TOM5 mitochondrial TOM complex subunit
SAM35 mitochondrial TOM complex subunit
SAM37 mitochondrial TOM complex subunit

to be annotated to TOM complex assembly?

**Comment by ValWood** [comment]
After looking more closely it seems that the annotation is confusing the assembly of

mitochondrial sorting and assembly machinery complex (GO:0001401) (SAM50)
 with the assembly of
mitochondrial outer membrane translocase (GO:0005742) (TOM)

but also, when this is resolved, most annotation will refer to proteins being involved in the assembly of the complex that they are themselves a member of, which isn't correct.

**Comment by srengel** [comment]
SAM complex and TOM complex are both is_a mitochondrial outer membrane translocase complex.  not sure what you are asking us to do here.  unclear why i got assigned or what i'm being asked to do.

**Comment by ValWood** [comment]
This is quite old. I can no longer see  mitochondrial outer membrane translocase complex assembly annotations to the cognate complex for these terms.
