### ISSUE TITLE
Review annotations to GO:0090249 'regulation of cell motility involved in somitogenic axis elongation' - possible new term for annotation

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go-annotation#2040]
@RLovering 

In https://github.com/geneontology/go-ontology/issues/15967 , we are proposing to merge 'cell motility involved in somitogenic axis elongation' into 'cell migration involved in somitogenic axis elongation' as in the context of development, migration, i.e. directed movement, is observed as opposed to just motility, i.e. movement.

There are no annotations to 'cell motility involved in somitogenic axis elongation' but there are two experimental annotations to 'regulation of cell motility involved in somitogenic axis elongation' to  Xenopus tropicalis proteins from PMID:15687260 that Varsha curated a few years back.

Can you please take a look at the annotations to see if it would be okay to migrate them to a potential new term, 'regulation of cell migration involved in somitogenic axis elongation'?

Also, could you review the evidence code for the Xenopus Nkd annotation.  I was wondering if it is more appropriately IGI evidence based on this text:

"To find evidence for a cooperative function of PR72 with Nkd, we performed double knock-down for PR72 and Nkd with low MO doses, which gave no obvious phenotype when injected alone (data not shown). When we injected the same low amount of PR72 and Nkd MO together, we found embryos with similar phenotypes as we found with higher doses PR72 MO alone (Fig. 5A). This additive effect strongly suggests cooperation between PR72 and Nkd during Xenopus development."

Thank you.

P.S. If you are busy, perhaps we could ask Malcolm Fisher from Xenbase to take a quick look.

**Comment by RLovering** [comment]
Hi Kimberley

please go ahead with the revisions to the ontology. I think this will be fine. FYI Varsha used IGI and IMP for the annotations because the single knockdown did have an effect: 
see results section refering to fig 4: We find that depletion of XPR72 with two distinct sets of PR72 MOs causes severe developmental defects, while similar amounts of control MO show no developmental defects. PR72-depleted embryos do not move or swim, which is indicative of differentiation defects of the somites forming the muscle cells. These embryos show a short axis phenotype (Fig. 4B) with a structure reminiscent of an open blastopore caudally (Fig. 4B, arrowheads), which is most likely due to incomplete closure of the blastopore during late gastrulation and indicates an effect on morphogenetic cell movements required for elongation of the body axis. A low frequency of neural tube closure defects (Fig. 4B, arrows) also indicates defects in morphogenetic cell movements during gastrulation. 

And as you point out they also state later for Fig 5: When we injected the same low amount of PR72 and Nkd MO together, we found embryos with similar phenotypes as we found with higher doses PR72 MO alone (Fig. 5A).  ie high doses cause the phenotype due to more complete reduction of protein, but low doses cause partial k/o and these are more susceptible to reduced Nkd levels. 

Thanks for asking me

Ruth
