### ISSUE TITLE
PTN000167322 (PTHR22778)

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2043]
PTN000167322 (PTHR22778) has nested NOT annotations. 
@huaiyumi and myself need to look into this. Should this be allowed ?

**Comment by thomaspd** [comment]
I don't see nested NOT annotations anymore:
http://pantree.org/tree/family.jsp?accession=PTHR22778, so this is resolved, at least for this family.

I agree these should not be allowed, i.e. if there's already a NOT at node A, then you can't have another NOT of the same function on a descendant of A. This makes sense, since you can only NOT a function that would otherwise be inherited, and the NOT at A prevents inheritance by any descendant of A.  @huaiyumi, do we need to have @mugitty add a check in PAINT for this, or does it already have the correct behavior?

**Comment by mugitty** [comment]
Since PAINT release 2018_08_30_1, the PAINT client will not permit the curator to 'unNOT' an IBA that is the result of a IKR
The PAINT server also performs integrity checks to ensure a given IBD annotation does not have multiple 'NOT's.

**Comment by thomaspd** [comment]
Thanks, I will close this issue
