### ISSUE TITLE
Confirm content of goa isoform gafs

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go-annotation#2062]
For GO Central pipeline, we need to confirm exactly what annotations are included in the goa isoform gafs and how they should be handled for production GAFs.

**Comment by ValWood** [comment]
4 years old @vanaukenk  was this adressed?

**Comment by pgaudet** [comment]
I think this is clarified. GO will start loading 'true biological' isoforms soon, with new files that Alex is producing. 
The file called 'isoforms' also contains TrEMBL entries, which is super confusing because most biologists would not necessarily consider these isoforms, they are just other sequence submissions that have not been merged. 


I'll assign to @suzialeksander and myself to document. 

Thanks, Pascale

**Comment by ValWood** [comment]
I agree it is very confusing to get redundant entries from Trembl. Espeicially for proteomes that are fully represented in UniProt.

**Comment by pgaudet** [comment]
This will get fixed shortly - Alex is now producing a single file for human, dog, cow, chicken, and pig, that contains proteins, RNAs, complexes, and splice isoforms (ie, not "TrEMBL isoform", which may just represent different sequences of a single gene. 

So, this ticket is replaced by https://github.com/geneontology/go-site/issues/2214
