### ISSUE TITLE
RNA polymerase II, core complex

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-annotation#2078]
There are 3 human proteins annotated to RNA polymerase II, core complex that look odd.

https://www.uniprot.org/uniprot/Q9H5H4 - ZNF768 Zinc finger protein 768 assigned by Interpro
https://www.uniprot.org/uniprot/Q9UBK2 - PPARGC1A Peroxisome proliferator-activated receptor gamma coactivator 1-alpha assigned by Uniprot
https://www.uniprot.org/uniprot/O94763 - URI1 Unconventional prefoldin RPB5 interactor 1, assigned by Uniprot
https://www.uniprot.org/uniprot/Q8TD26 - CHD6 Chromodomain-helicase-DNA-binding protein 6, assigned by Uniprot

I'm guessing they should be removed?

**Comment by pgaudet** [comment]
@ggeorghiou @asangrador Can you please have a look ?

**Comment by ggeorghiou** [comment]
Hi, the UniProt annotations are not in the GOA database anymore with the exception of CHD6 which already has an open dispute to be reviewed by a curator at SIB. What you see on the UniProt website is out of date due to how UniProt production runs so on the next public release, you should see those annotations removed.

**Comment by pgaudet** [comment]
Fixed by @lbreuza
