### ISSUE TITLE
Human proteins: Review annotations to DNA-binding transcription factor activity (GO:0003700) should NOT be also annotated to catalytic activity (GO:0003824) 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2208]
https://docs.google.com/spreadsheets/d/17mISqgr4JtlHO2ggpibcQ5pbOkes1d8v1Hh81nudpVg/edit#gid=0

**Comment by RLovering** [comment]
I have updated this spreadsheet to show which records need to be reviewed, however I have not completed the table yet. But I have identified that some of the ones I pulled out are not annotated to catalytic activity, but to binding of an enzyme

**Comment by RLovering** [comment]
Hi Pascale

I have gone through all the human proteins in the spreadsheet and tried to decide which annotations need revising. I have contacted UniProt and Reactome if it looks like their annotations need to be edited. 
However, I have been a bit cautious about making decisions about some of them (or some families) and so I have created an extra column with your name at the top, could you or Val (if Val is interested or has time) look at these and make a decision about if these should be dbTFs, co-regulators or neither or if a new MF term is required.

Thanks

Ruth

**Comment by RLovering** [comment]
Emails from Reactome re dbTF errors:
Subject: RE: [Reactome-help] [Protein2GO] Query concerning annotation to protein Q13127
 
Hi Peter,
 
These annotations look similar to some others we encountered a few weeks ago.  The physical entity of the catalyst activity using “histone deacetylase activity” looks to be a defined set whose members are complexes.  In version 66, the GAF script was only excluding physical entities that were themselves a complex rather than a set of complexes.  The changes made for version 67 should catch this case of a set of complexes as well as some others.
 
I am actually going to run both version of the script against test_reactome_67 (the script is read-only and has no effect on the database contents) and do a comparison so we can see exactly which annotations are being excluded by the changes added to the script.
Thanks,
Joel
AND:
Hi Ruth,
OK. the fix that catches these cases will be in place in time for the GAF to accompany our December 2018 release and at that point components of complexes should no longer get molecular function annotations unless they have been identified via manual curation as being the part of the complex that actually mediates the function.
Peter

**Comment by pgaudet** [comment]
Out of date.
