### ISSUE TITLE
spore germination/sporulation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2216]
Does anybody know why
spore germination

Definition (GO:0009847 GONUTS page)
The physiological and developmental changes that occur in a spore following release from dormancy up to the earliest signs of growth (e.g. emergence from a spore wall).

is not part_of 

GO:0043934    sporulation

Definition (GO:0043934 GONUTS page)
The process whose specific outcome is the progression of a spore over time, from its initiation to the mature structure. A spore is a structure that can be used for dissemination, for survival of adverse conditions because of its heat and dessication resistance, and/or for reproduction.

**Comment by mah11** [comment]
Yes: because sporulation is the *formation* of a spore. It ends when the spore is fully formed, which can be literally years before conditions change and the spore germinates. (It may be worth deviating from the usual standard "progression over time" definition wording to make that clearer, but sporulation ends before spore germination begins.)

**Comment by ValWood** [comment]
ok, wrong tracker anyway...
