### ISSUE TITLE
PTN000262353 - PTHR12254 Update of source annotations

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#2231]
The annotations associated with the genes from PTN000262353 infers 'Notch signaling pathway':

FBgn0002629
FBgn0002732
FBgn0026320

have been updated to "negative regulation of Notch signaling pathway"

**Comment by pgaudet** [comment]
This tree contains 4 duplicated fly genes; I removed all annotations because I am not sure how much we can expect in terms of conservation of function. @hattrill let me know if you want me to add annotations back. 

<img width="520" alt="image" src="https://user-images.githubusercontent.com/4782928/54282090-867b8480-459b-11e9-8d07-79cbcd95b38d.png">


Thanks, Pascale

**Comment by hattrill** [comment]
Perfect - these are a bunch of crazy genes and they all behave differently with regard to Notch signaling.
