### ISSUE TITLE
Review annotations to GO:0008320 protein transmembrane transporter activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2310]
Hello, 

For the MF refactoring and cleaning up of the protein transporter activity branch, I have looked at annotations to GO:0008320 protein transmembrane transporter activity and while most seem OK, I'd like the following to be reviewed: 

https://docs.google.com/spreadsheets/d/1iUlL-xu3hZ99A2ixbS8aA1KxLsE_kaS-B6oqT0aRnro/edit#gid=0

1 BHF
1 CACAO 
4 PseudoCAP

Thanks, Pascale

**Comment by dsiegele** [comment]
@pgaudet 

I reviewed the CACAO annotation of Mouse:BL1S3 to GO:0008320 and marked it as incorrect. The experimental result shows mislocalization of a target protein (Tyrp1) due to disruption of protein trafficking in the endosomal pathway.  I don't think this is evidence for transmembrane transporter activity.

**Comment by pgaudet** [comment]
@glwinsor did you have a chance to look at those ?

**Comment by glwinsor** [comment]
Yes, I did. I think TatA, TatB, and TatC annotations should remain unchanged since the paper shows that tat (composed of these three proteins) transports an enzyme (PvdN) across the cytoplasmic membrane. 

The other annotation for CdrB (PA4625) is based on a study that strongly suggests CdrA is transported across the outer membrane by CdrB. CdrA and CdrB were predicted to comprise a two partner secretion system based on sequence similarity and fact they are adjacent. The paper showed that a mutation in CdrB prevents CdrA from accumulating in the supernatant.  Is this sufficient evidence for that term? Thanks!

**Comment by pgaudet** [comment]
Thanks Goeff !

**Comment by RLovering** [comment]
done for UCL
