### ISSUE TITLE
PAINT fluconazole transport | IBA withPTN001160704

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2344]
pombe
caf5 | GO:0015903 | fluconazole transport | IBA with S000000212 , PTN001160704

(a spermine family transporter)

**Comment by marcfeuermann** [comment]
PTN001160704  node from PTHR23502 corresponds to a small branch that contains only 16 leafs, including _S. cerevisiae_ FLR1 (Fluconazole resistance protein 1) and _C. albicans_ MDR1.  _S. cerevisiae_ FLR1 has been shown to be involved in in efflux of fluconazole, diazaborine, benomyl, methotrexate, and other drugs. _C. albicans_ MDR1 confers resistance to numerous chemicals including azoles such as fluconazole, voriconazole, and benztriazoles, as well as to benomyl, cycloheximide, methotrexate, 4-nitroquinoline-N-oxide, sulfometuron methyl, cerulenin, and brefeldin A. The overexpression of MDR1 is a frequent cause of resistance to the widely used antimycotic agent fluconazole and other toxic compounds in the pathogenic yeast Candida albicans.
However, as there are duplications within PTN001160704 (2 paralogs for _S. pombe_ mfs1 and caf5),  as substrate specificity is highly variable between close-related transporters from different species, and as resistance acquisition is not always a direct effect of efflux of the compound (we've submitted an article about those topics a week ago), I've removed the propagation of fluconazole transport-related terms.
In general, it is dangerous to propagate any substrate specificity within transporter families such as MFS and ABC families. 
Annotation to "drug transport" related terms will also be addressed very soon since they seem to be highly misused.
Cheers
Marc.

**Comment by ValWood** [comment]
> In general, it is dangerous to propagate any substrate specificity within transporter families such as MFS and ABC families.

I agree.... a single residue mutation can totally change the specificity so I have noticed that evolutionary conservation of function is often not consistent with sequence conservation.

Although I guess some are just general efflux, it is difficult to know...

**Comment by ValWood** [comment]
Can you send me your  article when published, my boss currently has a collaborative project looking at transporter specificity, he will probably be interested in this.

**Comment by marcfeuermann** [comment]
I will of course send you the article as soon as it is accepted :-)
