### ISSUE TITLE
add mol. fun term to GNAT domain (IPR000182)

### ISSUE THREAD

**Issue by phanivg** [geneontology/go-annotation#2390]
please add N-acetyltransferase activity ; GO:0008080 mol.fun term to GNAT domain (IPR000182). In Fly there are 28 genes with this domain of which many have proven N-acetyltransferase activity

**Comment by ValWood** [comment]
I think this was removed because of
https://github.com/geneontology/go-annotation/issues/1805

Elp3 might still be an acetyltransferase, its role in 
tRNA wobble base 5-methoxycarbonylmethyl-2-thiouridinylation
is still unclear.

It isn't a histone acetyltransferase which was the purpose of the previous ticket.

This mapping might be safe, at least until further info available.

**Comment by happy-lorna** [comment]
I have added this annotation back in - it will be visible in our next release.

**Comment by phanivg** [comment]
Thank you Valerie and Iorna
