### ISSUE TITLE
Matrix: aars2  amino acid metabolism/glycosylation (3)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2420]
Hi Sabrina,
This one is weird. I think the InterPro domain is incorrect from the protein, so if this domain is present it might be a gene fusion/gene prediction error or InterPro false positive
v

aars2 | alanyl-tRNA synthetase 2, mitochondrial (putative) |   | protein glycosylation |   | ZFIN | Danio rerio | IEA | InterPro:IPR002659 | alanyl-trna synthetase pthr11777 | protein |   | ZFIN:ZDB-PUB-020724-1

**Comment by sabrinatoro** [comment]
Thank you @ValWood 
It looks like there should be 2 genes instead of 1. 
We are working on solving the problem, but it includes ensembl and UniProt, so I don't know how quickly this will be solved. 

The annotation above will not be updated until the problem is solved, which will take time. 
If this questionable time line is an issue, please let me know, and I will manually remove it (and keep removing it). 

I am leaving this case open as a reminder to follow up on this. However, it can also be closed if it is better for you.

**Comment by ValWood** [comment]
It's OK, I can close this and report as a "gene structure  update pending"

I don't need to change any rules as it will fix over time. In the meantime, this one will appear in the logs for the  GO rule, but you will know what it is.
