### ISSUE TITLE
Matrix: drosophila slimp not tRNA metabolism PAINT

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2444]
This seems to. be a divergent family member in drosophila

http://amigo.geneontology.org/amigo/gene_product/FB:FBgn0051133

There have NOT annotations for the tRNA metabolism processes and functions. Some of these are observed by PAINT, and some not

**Comment by ValWood** [comment]
@hattrill  please sanity check

**Comment by hattrill** [comment]
SLIMP: can bind mt tRNA ser, but cannot bind ATP, activate serine, or make serine-tRNA. 

NOT seryl-tRNA aminoacylation
NOT serine-tRNA ligase activity
NOT ATP binding
from PMID:20870726 are correct

Removed cellular respiration and mitochondrion morphogenesis as phenotype.


@marcfeuermann can you check these:

cytoplasm from PANTHER:PTN000925729 should be removed (it is mitochondrial)
seryl-tRNA aminoacylation PANTHER:PTN000925729 as it does not do this.

? NOT serine-tRNA ligase activity PANTHER:PTN000925729|PANTHER:PTN000925807 seems strange as nodes not populated with genes.

**Comment by marcfeuermann** [comment]
The annotation of PTHR11778 seems weird. Might be due to recent update of the tree. There is an easy distinction between cytoplasmic and mitochondrial proteins, which heve been now correctly annotated. I've also blocked annotation of function and process to node PTN000925807 containing SLIMP and 4 other insect proteins and resulting from a duplication event.
