### ISSUE TITLE
Matrix: cohesin human SMC3

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2526]
I don't see SMC3 mentioned in this paper.  MAybe it's a different name, but I'm pretty sure that cohesin doesn't localize to the basement membrane, and that these are not processes that cohesin is 'programmed' to perform.

UniProtKB:Q9UQE7 | SMC3 | involved_in | GO:0051702    interaction with symbiont | ECO:0000314   IDA | PMID:19444697 |   | 9606 Homo sapiens | CAFA |  

UniProtKB:Q9UQE7 | SMC3 | involved_in | GO:0044791    positive regulation by host of viral release from host cell | ECO:0000314   IDA | PMID:19444697 |   | 9606 Homo sapiens | CAFA |  

UniProtKB:Q9UQE7 | SMC3 | part_of | GO:0005604    basement membrane | ECO:0000304   TAS | PMID:8621634 |   | 9606 Homo sapiens | CAFA | part_of (UBERON:0002097)

**Comment by ValWood** [comment]
cohesin
@RLovering 

UniProtKB:Q9UQE7 | SMC3 | involved_in | GO:0032876    negative regulation of DNA endoreduplication | ECO:0000315   IMP | PMID:15917200 |   | 9606 Homo sapiens | BHF-UCL

is this one a readout? Is endoreduplication a normal process for human?
(not sure, I thought not)

**Comment by ggeorghiou** [comment]
Hi @ValWood 

Just having a look at this now. 

Seems like the annotations are correct because SMC3 is actually called Bamacan (which actually stands for Basement Membrane-Chondroitin Sulfate Proteoglycan, UniProt entry https://www.uniprot.org/uniprot/Q9UQE7 ). 
 
For these two annotations:
UniProtKB:Q9UQE7 | SMC3 | involved_in | GO:0051702    interaction with symbiont | ECO:0000314   IDA | PMID:19444697 |   | 9606 Homo sapiens | CAFA |  

UniProtKB:Q9UQE7 | SMC3 | involved_in | GO:0044791    positive regulation by host of viral release from host cell | ECO:0000314   IDA | PMID:19444697 |   | 9606 Homo sapiens | CAFA |

PMID:19444697 is showing exactly that SMC3/Bamacan is involved in these viral processes. 

For this annotation:

UniProtKB:Q9UQE7 | SMC3 | part_of | GO:0005604    basement membrane | ECO:0000304   TAS | PMID:8621634 |   | 9606 Homo sapiens | CAFA | part_of (UBERON:0002097)

The paper says Bamacan is found at the basement membrane. (this is actually the paper that discovered and named it). As for why it was annotated to a TAS statement, Alice was kind enough to leave a note attached to it in Protein2GO: 'TAS evidence code refers to the fact that the authors used a polyclonal antibody shown to recognise CS/DSPGs in general/ Later the presence of HSPG2 and SMC3 in these structures was confirmed by monoclonals, but the pictures are not provided.'

So technically these annotations are correct.

**Comment by ValWood** [comment]
But SMC3 is a core component of mitotic cohesin? I'm sure this isn't multifucntional and that this is historical data predating the (now) 263 human papers on SMC3.

I'll ask cohesin experts about this.

**Comment by ValWood** [comment]
Hmm this is odd, despite the many 100's of papers on SMC3 and cohesin and the very few papers on  the  basement membrane, the wikipedia page seems to give this as much prominence. I wonder who wrote it ;)

https://en.wikipedia.org/wiki/SMC3

it barely  mentions cohesin!
https://en.wikipedia.org/wiki/SMC3

**Comment by ValWood** [comment]
In light of the knowledge about SMC3, I don't think this is really enough to support a functional role in the basement membrane......its just  a 2 hybrid and an colocalization?

The colocalization is worrying because SMC3 is absolutely necessarily chromatin associated in all cells throughout the mitotic and meiotic cell cycle (even at interphase). If this isn't the case your chromosomes would fall apart!


J Neurovirol. 2009 May;15(3):229-37. doi: 10.1080/13550280902913636.
The proteoglycan bamacan is a host cellular ligand of vaccinia virus neurovirulence factor N1L.
Mohan KV1, Zhang CX, Atreya CD.
Author information
Abstract
Neurovirulence is one of the pathological complications associated with vaccinia virus (VV) infection/vaccination. Although the viral N1L protein has been identified as the neurovirulence factor, none of the host N1L-interacting factors have been identified so far. In the present study, we identified N1L-interacting proteins by screening a human brain cDNA expression library with N1L as a bait protein in a yeast two-hybrid analysis. The analysis revealed that N1L interacts with human brain-originated cellular basement membrane-associated chondroitin sulfate proteoglycan (bamacan). The N1L-binding domain of bamacan was mapped to its C-terminal 227 amino acids. The N1L-bamacan interaction was further confirmed in both VV-infected and N1L-transfected mammalian cells. Following the confirmation of the protein interactions by coimmunoprecipitation experiments, confocal microscopic analysis revealed that N1L colocalizes with bamacan both in VV-infected B-SC-1 cells as well as in mice neuronal tissue. Furthermore, a human neural cell line, which expresses bamacan to moderately elevated levels relative to a non-neural cell line, supported enhanced viral growth. Overall, these studies clearly suggest that bamacan interacts with the VV-N1L and such interactions seem to play a positive role in promoting the viral growth and perhaps contribute to the virulence of VV in neural cells.

PMID: 19444697 

There isn't really any functional information in this paper.

**Comment by ValWood** [comment]
This is one of my favourite proteins/complexes, I read over 100 papers on it and I never came across any that mention this work, or any role other than chromosome cohesion  (I'm also using  it as one of the case studies in the Matrix paper, so keen to remove any oddities for this)

**Comment by ValWood** [comment]
This 2009 paper is cited 3 times and none of the citations add anything to this work. I looked at the paper again and we can't really use an overexpression affecting viral growth as a valid experiment (the cell would be compromised in such a scenario)......The authors don't even acknowledge that this is a major cohesin subunit, even though this was published in Cell back  in 1999. 
https://www.ncbi.nlm.nih.gov/pubmed/10412984  
and they must have known this.
This is the thing I find most bizarre about this paper! Almost certainly if it had been reviewed by cohesin community it would not be published....

**Comment by ValWood** [comment]
This basement membrane association is considered overturned/ignored two of the foremost cohesin experts (they point out flaws in the experiments and that cohesin would likely bind  highly charged proteoglycan).

**Comment by ggeorghiou** [comment]
Right, knowing that now, I'll go ahead and delete the annotations.

**Comment by colinlog** [comment]
@RLovering  Is endoreduplication a normal process for human?
Yes it is. Human megakaryocytes do it. So, definitely a physiological process also in humans. It is a different process from polytene chromosome endoreduplication in insect salivary glands though!

**Comment by ValWood** [comment]
So now the question is, is SMC3 involved in endoreduplication.

T he annitation is IMP, but it is from a review?

Cornelia de Lange Syndrome and the link between chromosomal function, DNA repair and developmental gene regulation.
Strachan T1.
Author information
Abstract
Cornelia de Lange Syndrome (CdLS) is a rare multiple malformation disorder with characteristic facial features, growth and cognitive retardation, and many other abnormalities. CdLS individuals were recently shown to have heterozygous mutations in a previously uncharacterised gene, NIPBL, which encodes delangin, a homologue of fungal Scc2-type sister chromatid cohesion proteins and the Drosophila Nipped-B developmental regulator. Nipped-B and vertebrate delangins are also now known to regulate sister chromatid cohesion, probably as part of oligomeric complexes required to load cohesin subunits onto chromatin. CdLS is likely to be one of several developmental disorders resulting from defective expression of a multi-functional protein with roles in chromosome function, gene regulation and double-strand DNA repair - a combination of properties shared by certain bacterial proteins responsible for structural maintenance of chromatin.

PMID: 15917200

**Comment by ValWood** [comment]
I don't see anything about endoreduplication in this review. Or SMC3?
Although SMC3 does cause Cornelia De Lang Syndrome, this review is mainly about  NIPBL (cohesin loading factor, adherin), another CDLS causing gene.

**Comment by colinlog** [comment]
Hope I am not spamming :-|

Cornelia de Lange Syndrome (CLS) is also caused by other cohesin subunit
gene mutations (Rad21, SMC1, SMC3 cohesin subunits and NippedB which is the
loader of cohesin most recent is PMID:30125677). This incontrovertibly
links the CLS syndrome to the cohesin complex and led to the name
'cohesinopathies'. the molecular etiology is not known. In view of
chromatin architectural role of cohesin in interphase (together with CTCF)
the molecular etiology may be 'epigenetic gene control loss',as Dale
Dorsett claimed in the 90's

To the best of my knowledge endoreduplication is not a Cornelia de Lange
cellular symptom. In fact when yeast are depleted of cohesin this will not
yield endoreduplication, but rather aneuploidy, ranging from <1n to 2n
chromosome complements in the daughter cells. This is extremely
toxic/lethal and irreversible at the cellular level. Of course subtle
cohesin subunit mutations may exist that cause endoreduplication-like
phenotypes, but to my knowledge this has not been established. For
completeness; I discovered an endoreduplication phenotype for a yeast
chromatin remodeller complex subunit (SFH1, PMID: 17542652 ) that is
partially reproduced in human cancers (SNF5 mutants PMID:15769941). As RSC
and Cohesin may work together (PMID: 30922844 ) there may be an
endoreduplication link, but I do not think it is firmly established yet. A
recent biorXiv paper where authors were attentive to ploidy also does not
report effects of cohesin disfunctioning as endoreduplication. So in short:
currently endoreduplication is not a cohesin-driven biological process,
even though cohesin is involved in maintaining proper ploidy during mitosis
through its role in the spindle checkpoint as the factor that is
inactivated by the separase, as Kim Nasmyth and others elegantly
demonstrated in the late 90's!

**Comment by ValWood** [comment]
This makes sense. I'll bet the toxic aneuploidy phenotype  has been misinterpreted as "endoreduplication". 

Interesting stuff....

**Comment by ValWood** [comment]
yay, https://www.pombase.org/term/DOID:11725

**Comment by RLovering** [comment]
Hi Val

I have removed all negative regulation of DNA endoreduplication annotations for proteins annotated to  PMID:15917200, There were 5 proteins annotated to this term based on this paper (listed below). I don't know if you are keeping track of the revisions undertaken based on your matrix. 

UniProtKB:P49959 | MRE11 | 
UniProtKB:Q14683 | SMC1A | 
UniProtKB:Q8N3U4 | STAG2 | 
UniProtKB:Q969H0 | FBXW7 |
UniProtKB:Q9UQE7 | SMC3 |

Best

Ruth

**Comment by ggeorghiou** [comment]
@ValWood can we close this ticket? Looks like everything has been addressed.

**Comment by ValWood** [comment]
Great thanks everyone. Nice clean up on cohesin
