### ISSUE TITLE
Matrix: amino acid metabolism / nitrogen cycle

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2539]
Is  arginine metabolic process correct for 

DUR1,2 | Urea amidolyase |   | arginine metabolic process |   | UniProt | Saccharomyces cerevisiae S288C | IEA | UniProtKB-KW:KW-0056 | carboxylase:pyruvate/acetyl-coa/propionyl-coa carboxylase pthr18866 | gene |   | GO_REF:0000037 | 20190622

is
allophanate hydrolase activity
Ontology
molecular_function
Synonyms
allophanate lyase activity, urea-1-carboxylate amidohydrolase activity
Catalysis of the reaction: H(2)O + 3 H(+) + urea-1-carboxylate = 2 CO(2) + 2 NH(4)(+).

urea carboxylase activity
Catalysis of the reaction: ATP + bicarbonate + urea = ADP + 2 H(+) + phosphate + urea-1-carboxylate. Source: EC:6.3.4.6, RHEA:20896

**Comment by srengel** [comment]
@pgaudet not sure why this is assigned to me because this is an IEA annotation - SGD didn't make this annotation.

regarding whether it's relevant - arginine is upstream of this enzyme, it's broken down to urea which is acted upon by DUR1,2.  so it's a question of how upstream or downstream we want def's to go (eternal question).

**Comment by pgaudet** [comment]
@sylvainpoux @ggeorghiou Can you please check the SP keyword ?

**Comment by sylvainpoux** [comment]
I agree this is indirect. I deleted the KW
Thanks
Sylvain

**Comment by ValWood** [comment]
Oh I thought it was actually OK after I looked at the pathway because arginine is part of the pathway. I guess it depends where it feeds in.
Should I keep the exception or remove it do you think?
