### ISSUE TITLE
ERCC6 annotation review

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2554]
From
https://github.com/geneontology/go-ontology/issues/15848

ERCC6 is involved in 

transcription-coupled nucleotide-excision repair
(it's  repair helicase)

 So a number of annotation look suspect here:

photoreceptor cell maintenance Source: MGI
positive regulation of defense response to virus by host Source: MGI
positive regulation of DNA repair Source: MGI
positive regulation of DNA-templated transcription, elongation Source: MGI
positive regulation of gene expression Source: MGI
~regulation of DNA-templated transcription, elongation Source: MGI~
~transcription elongation from RNA polymerase I promoter Source: MGI~

UniProtKB:A3KMN2 | Ercc6 | acts_upstream_of_or_within | GO:0035264    multicellular organism growth | ECO:0000316 IGI | PMID:22323595 | MGI:MGI:95412 more... | 10090 Mus musculus | MGI

UniProtKB:A3KMN2 | Ercc6 | acts_upstream_of_or_within | GO:0009636    response to toxic substance | ECO:0000315 IMP | PMID:11408355 | MGI:MGI:1932102 | 10090 Mus musculus | MGI

~UniProtKB:A3KMN2 | Ercc6 | acts_upstream_of_or_within | GO:0006362    transcription elongation from RNA polymerase I promoter | ECO:0000315  IMP | PMID:23562818 | MGI:MGI:1932102 | 10090 Mus musculus | MGI~

**Comment by pgaudet** [comment]
I created a spreadsheet to keep track of those
https://docs.google.com/spreadsheets/d/1HhrgOHvGCv5kNsSjDB57oOxlzH9n1Rqfz0x2ESQ2Dto/edit#gid=0

@ValWood Can you check that those were the terms you are asking to be reviewed? 

Thanks, Pascale

**Comment by ValWood** [comment]
Will do. I can also add more information if it isn't immediately why these seem incorrect, but that will take more time.

Basically Rad26/ERCC Rad26 stabilizes RNAPII at DNA lesions . I would not expect "positive regulation of elongation" 

I'm questioning "regulation of repair" because I think the involvement is direct? but this might be wrong.

Maybe 
regulation of DNA-templated transcription, elongation Source: MGI
but if anything I would expect "negative regulation"

**Comment by ValWood** [comment]
I crossed out the "regulation of elongation" ones above.

Because the repair is coupled to transcription there is "interference" between the 2 sets of machinery.  i.e not regulating specific genes, or global transcription elongation.

It might be useful here to have a specific term
"negative regulation of transcription elongation involved in transcription-coupled repair"

**Comment by ukemi** [comment]
@krchristie, can you have a look at the transcription role? The paper I looked at quickly (J:198536) made it seem reasonable to me that this gene product plays a role in transcription. The photoreceptor maintenance annotation doesn't seem out of place to me either since I would suspect that they are particularly sensitive to UV and would therefore need this pathway. However, I didn't read that paper. The toxic substance doesn't seem out of place either since according to the abstract the substance was DMBA. Maybe specify this annotation.

**Comment by ValWood** [comment]
Hi @krchristie  feel free to close this  based on David's comments. I might be out of the loop on Rad26/ERCC6 role.  I thought that Rad26 removed pol II during TCR.

**Comment by ValWood** [comment]
I  wouldn't do annotate
response to toxic substance for DBMA. This is just a DNA damaging agent, used in the assay so why not  

GO:0006974    cellular response to DNA damage stimulus
which is what it is showing process-wise

It just seems a bit odd to annotate this way. Otherwise, every DNA repair enzyme should be annotated to "response to toxic substance".  Isn't the process more important than the type of substance which activated it? (there isn't a separate pathway for every DNA damaging agent)

**Comment by krchristie** [comment]
@ukemi - I have reviewed the paper that is the source of the annotation to `transcription elongation from RNA polymerase I promoter - GO:0006362`:

>Nonnekens J et al. Mutations in TFIIH causing trichothiodystrophy are responsible for defects in ribosomal RNA production and processing. 2013
J:198536
PMID:23562818

I thought this paper was really solid and presents strong evidence that follows up on previous work that TFIIH is involved in transcription by RNAP I as well as RNAP II. I have made some minor alterations to the original annotations and also added annotations to a gene that had not previously been annotated based on some inhibitor studies. I have marked the spreadsheet that the transcription annotation was `checked and unchanged`.

**Comment by krchristie** [comment]
@ukemi - Could you please tell me how to put in qualifiers to say `upstream of or within` versus `directly involved in` (I know those aren't exactly the right phrases, but I think you get the meaning) in the MGI EI. I thought this paper was evidence for a direct involvement of TFIIH in RNAP I transcription elongation so I'd like to mark it with that qualifier so that it is clear that it is a direct participant.

**Comment by krchristie** [comment]
@ValWood - It is definitely not a mistake that Ercc6 (aka CSB in the Nonnekens paper) is annotated to RNAP I transcription. This was the point of the Nonnekens paper. Here is a quote:

> Since  mutations  in  TFIIH  cause  severe  human  genetic  diseases,  we  further  examined  the  impact  of  clinically  relevant TFIIH  mutations  on  RNAP1  transcription.  Like  TFIIH,  CSB (another  NER  protein)  plays  a  role  in  RNAP1  transcription.

**Comment by ValWood** [comment]
Ah right, I need to look into this more for PomBase. I  know that TFIIH is involved in transcription and repair but  didn't think that ERCC6/rad26 was part of this complex. It doesn't have TFIIH  in SGD either?

**Comment by ValWood** [comment]
Got it. It still seems a bit conflicting, negative regulation of txn in yeast and positive in mammals. I guess all will become clear later...

**Comment by krchristie** [comment]
@ValWood - I have checked all the experimental annotations made by MGI and marked that on the spreadsheet. You will have to ask the original annotators to review these remaining four annotations that are made to human genes, either to:
- UniProtKB:P0DP91 (Chimeric ERCC6-PGBD3 protein)
- UniProtKB:Q03468 (DNA excision repair protein ERCC-6)

GO Term | With info
-- | --
positive regulation of defense response to virus by host Source: MGI | ISO with UniProtKB:P0DP91 (Chimeric ERCC6-PGBD3)
positive regulation of DNA repair Source: MGI | ISO with UniProtKB:P0DP91 (Chimeric ERCC6-PGBD3), ISO with UniProtKB:Q03468 (DNA excision repair protein ERCC-6)
positive regulation of DNA-templated transcription, elongation Source: MGI | ISO with UniProtKB:Q03468 (DNA excision repair protein ERCC-6)
positive regulation of gene expression Source: MGI | ISO with UniProtKB:P0DP91 (Chimeric ERCC6-PGBD3)


@hdrabkin - Do you have any idea why mouse Ercc6 is getting ISO annotations from two different human proteins via this load: J:164563 "Mouse Genome Informatics Scientific Curators (2010) Human to Mouse ISO GO annotation transfer."

**Comment by krchristie** [comment]
Ercc6 is not part of TFIIH, but the experiments using the mutant of Ercc6 seemed equally solid to those on TFIIH subunits. I took a quick look at one of the ISO papers and this one on human ERCC6 also talks about its role in transcription elongation, but for RNAP II rather than RNAP I for this paper. It is known that helicases are required to open the transcription bubble, so it might not be surprising that other helicases that interact with the DNA can affect transcription as well as DNA repair.

> Selby CP, Sancar A. Cockayne syndrome group B protein enhances elongation by
RNA polymerase II. Proc Natl Acad Sci U S A. 1997 Oct 14;94(21):11205-9. PubMed
PMID: 9326587 

Honestly, I find this approach to try to get rid of the annotations that don't conform to preconceived notions that we "know" what is going on a bit dangerous.

**Comment by ValWood** [comment]
The idea isn't to "get rid " of annotations, but to check for consistency and weed out old and indirect data. There are many, many examples of curation of old outdated science. However, this wasn't a good example. I thought ERCC6 annotation seemed very inconsistent - sometimes direct annotation to transcription, and sometimes regulation, and the same for repair. 

 I believe most of them are really worth checking because ~>90% seem to result in fixes or improvements. If the evidence is I can add suitable rules to exclude them from the checks.

I clearly didn't look at this one closely enough, and I agree that this is "positive regulation of transcription elongation", and that this is a universally conserved role of ERCC6

I will put "transcription-coupled nucleotide-excision repair"  in the exceptions.

**Comment by hdrabkin** [comment]
@krchristie , the load relies on mapping of UniProt ids in the GOA_human file to a human ortholog mapping to  an MGI marker. 
ISO with UniProtKB:P0DP91 (Chimeric ERCC6-PGBD3), 
ISO with UniProtKB:Q03468 (DNA excision repair protein ERCC-6)
Both are returned as homologs 
On Ercc6's gene detail page, under human orthology, both ids are listed.  This appears to be an error.  BUT, Q03468 is listed as the sequence for isoform CSB of P0DP91; Both come from the same gene. the P0DP91-1 is the 'fusion protein' 
Interestingly, isoform PGBD3 for P0DP91 points to  Q8N328.
'isoforms of the same protein are often annotated in two different entries if their sequences differ significantly."

**Comment by krchristie** [comment]
@hdrabkin - The UniProt Entry P0DP91 is a fusion protein between two genes: CSB (aka ERCC6) and PGDB3:
**UniProtKB - P0DP91 (ERPG3_HUMAN)**
- **Protein**: Chimeric ERCC6-PGBD3 protein
- **Gene**: CSB-PGBD3
- **Organism**: Homo sapiens (Human)

So, when the entry for P0DP91 lists Q03468 as the sequence for the CSB portion of the fusion gene, that's because that's the gene this portion of the fusion came from. However, I don't think that any annotations from the fusion protein (P0DP91) should be transferred to either of the genes that the fusion is comprised of.

Do you know to who I should submit a request for correction to not map human P0DP91 to mouse ERCC6? Is this an MGI mapping that we need to fix?

**Comment by ValWood** [comment]
https://www.uniprot.org/uniprot/P0DP91 is a readthrough and should be removed from UniPRot

this might have happened already] https://www.ncbi.nlm.nih.gov/gene/101243544

I would tag  Maria MArtin,  to check but here GitHub is not in the list

**Comment by krchristie** [comment]
I have submitted a Feedback suggestion directly to UniProt for P0DP91. However, it might be slower than usual before they fix it. I submitted something else earlier this week and the response email warns that response time might be slower than normal due to the upcoming summer vacation period in Europe.

**Comment by krchristie** [comment]
@ValWood - Ignoring the annotations made to human P0DP91 leaves only a couple from human ERCC6 (UniProtKB:Q03468). Please ask the original annotators to review these remaining two annotations made to UniProtKB:Q03468 (DNA excision repair protein ERCC-6). A very superficial look at the abstract for the transcription elongation term suggests that it should probably be made to an RNAP II specific term, as I have suggested in the spreadsheet.

GO Term | With info
-- | --
positive regulation of DNA repair Source: MGI | ISO with UniProtKB:Q03468 (DNA excision repair protein ERCC-6)
positive regulation of DNA-templated transcription, elongation Source: MGI | ISO with UniProtKB:Q03468 (DNA excision repair protein ERCC-6)

**Comment by ValWood** [comment]
OK closing this. I will open disputes on human for nay outstanding.
Thanks
Val
