### ISSUE TITLE
Rule based annotation error (GORULE:0000006)

### ISSUE THREAD

**Issue by lreiser** [geneontology/go-annotation#2556]
I was reviewing the errors in the  TAIR snapshot file  and came across this violation. The annotation was a rule based extrapolation from GOC. If IEP is restricted to BP terms then the annotation to cellular component should not be made, correct? Seems the rule needs updating.

* ERROR - Violates GO Rule: GORULE:0000006: IEP and HEP usage is restricted to terms from the Biological Process ontology -- `TAIR	locus:2092221	STP10		GO:0005623	TAIR:Publication:501768255|PMID:26893494	IEP		C	AT3G19940	AT3G19940|STP10|SUGAR TRANSPORT PROTEIN 10|MPN9.18	protein	taxon:3702	20160301	GOC		TAIR:locus:2092221

**Comment by pgaudet** [comment]
Hi @lreiser 
The rule is correctly reporting that you cannot annotate GO:0005623 (cell) by IEP. 

We have 2 options: 
1. Stop propagations from annotations supported by IEP
2. Relax the rule
(additionally we should remove inferences to 'cell', that's not very informative, and it creates inconsistencies, since one would expect almost all proteins to be annotated to cell, which is currently absolutely not the case).

Pascale

**Comment by lreiser** [comment]
Yes sorry I did not mean to imply the error was being reported incorrectly but rather that the automatic propagation was what caused the error
I agree that propagating to the term cell is not helpful.
