### ISSUE TITLE
dicty matrix

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2566]
@pfey03  wants me to include dicty.

This is the dicty matrix so there are not many violations of the current rules.
I will list them below to check.

![dicty matrix](https://user-images.githubusercontent.com/7359272/61727417-3abbc180-ad6b-11e9-8902-99e114976dd8.jpg)

**Comment by ValWood** [comment]
amino acid metabolism /mitochondrial organization (1 annotation)
amino acid metabolism /protein catabolis process (1 annotation)
amino acid metabolism /vesicle mediated transport (1 annotation) (unless GO:0006909 which is OK)

**Comment by ValWood** [comment]
- [ ]  tRNA metabolic process/cofactor metabolic process no overlap unless GO:0002143|GO:0070733|GO:0004792|GO:0006777|GO:0031071

**Comment by ValWood** [comment]
- [ ]  ribosome biogenesis / nucleobase-containing small molecule metabolic process 1 annotation

**Comment by ValWood** [comment]
- [ ]  DNA replication/ chromsome segreagation  unless 
GO:0007062 | PANTHER:PTHR28637 |

**Comment by pfey03** [comment]
DNA replication/ chromosome segregation IBA annotations not EXP

**Comment by pfey03** [comment]
@ValWood Hi Val, since I only today have a time window from the grant, I only looked at one. Also, when there are many annotations, how do I best find the one in the matrix? Tried QuickGO, but not easy to filter there or the Matrix tool. Maybe during GO meeting next month we can discuss a bit?
Thanks!

**Comment by ValWood** [comment]
Hi Petra,

Sorry for the delay.

This is a good question. This is why it takes so long, and why  I didn't want to  put another organism into the mix. 

There is a ticket to filter on evidence but not currently possible because of the way the matrix is generated (is essentially a gene list, not an annotation list).
https://github.com/geneontology/amigo/issues/569

Testing with  GO:1901605 GO:0007005 you have a single annotation.

We need to check the IEAs too at this stage, but in all likelihood, I will have already requested fixes for these (if PAINT or Interpro)

First filter on "aspect P" only (reduced the number of annotations to look at).

Second Increase the number of annotation viewed so you can see all annotations if possible. Then it's just a case of figuring the violator.

It takes a long time but  it is difficult for @kltm  to fix this because the Matrix reports on 
genes not annotations. 
Hopefully we can persuade Seth to make it easier.

**Comment by pfey03** [comment]
@ValWood l, Thanks!!

With our grant just submitted recently I also have been too busy and since then mopping up what was delayed. I will look more into the Matrix this afternoon. 

I see that creating an annotation version for filtering is maybe much more work and if it then changes how you deal with it. But me, as spread as I am, if it takes so long to dig through, for one annotation and then find it's not EXP, it's really hard. I wonder how the others deal with this. 

Looking forward to seeing you soon and maybe we have some time for Matrix...

**Comment by ValWood** [comment]
Yes easier in person.
See you soon!

**Comment by pfey03** [comment]
I checked the 
tRNA metabolic process/cofactor metabolic process no overlap

There are no exp annotations to both terms, must be IEA or IBA, only checked EXP using QuickGO first - that's the way for me to check I think.
See you soon!

**Comment by ValWood** [comment]
I'll close this, it doesnt require a ticket
