### ISSUE TITLE
Review annotations using extension 'regulates_transcription_of' 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2598]
Hello, 

We'd like to remove the relation 'regulates_transcription_of' from GO_REL. The relation can be replaced by 'has_input'.  The annotations are here: 
https://docs.google.com/spreadsheets/d/1fHDdK0XDkdNMJH6bLrKadoH9aMtsBfN9mGazaL01A_Q/edit#gid=0

If you use Protein2GO and you agree to the change, no action is needed; we'll ask P2GO to update the annotations. 

Assigned   by |  
-- | --
ARUK-UCL | 30
BHF-UCL | 127
ParkinsonsUK-UCL | 44
SGD | 87
WB | 13

Please let me know if I can go ahead with the obsoletion of the relation. 

Thanks, Pascale

**Comment by vanaukenk** [comment]
I had updated the WB annotations as part of the Noctua import work, but the updates aren't in the current WB production file.

There is only one remaining C. elegans annotation that uses 'regulates transcription of'  and that looks to be made by Parkinsons curation pipeline, so that will get fixed via the automatic updates in Protein2GO.

Fine with me to obsolete the relation when ready.

**Comment by RLovering** [comment]
Hi Pascale
unlike the other tickets this decision appears to be affecting all three GO aspects. While I don't think it should be applied to CC annotations, for a transcription factor complex that is located at a specific gene location what AE relation would you recommend.

I agree that annotations to the GO term: regulation of transcription should be automatically changed to has input, but some of the UCL annotations use the GO term regulation of gene expression. These are errors of annotation but I would like to revise these so that if the annotation should have been to the GO term regulation of transcription this will be changed. I guess as long as this spreadsheet remains we can go through these in our own time.

BTW has a decision been made about the ID that should be associated included in the annotation extension field when the GO term applied is:
regulation of gene expression
regulation of transcription
regulation of translation
regulation of cytokine production
etc

Also I am still wondering what the long term plan is going to be for signaling protiens that lead to changes in the transcription of a gene

Thanks

Ruth

@BarbaraCzub

**Comment by srengel** [comment]
SGD is fine with this change for the 87 SGD annotations listed in the spreadsheet.  we'll leave as is, and it's ok with us for them to be updated in bulk directly by P2GO.

**Comment by pgaudet** [comment]
Discussion with @RLovering 

To address the ID space issue: 
- How about using 'has_output' with the gene product being produced and use the same ID space as the gene annotated ? I think that would be a lot easier for users. 
- Then for groups who want to capture the *gene* being regulated with gene_ids, they can use has_input ENSEMBL id (or REFseq?) Ideally we would be using a single namespace for a species. 

@vanaukenk @cmungall @dustine32 @thomaspd

**Comment by RLovering** [comment]
Hi Alex
please change all the UCL annotation relations 'regulates_transcription_of' to 'has_input'
Thanks
Ruth
@alexsign

**Comment by alexsign** [comment]
@RLovering @pgaudet 
this is also updated now.

**Comment by RLovering** [comment]
many thanks
Ruth

**Comment by pgaudet** [comment]
All done , relation now obsolete in GOREL
