### ISSUE TITLE
Review annotations using extension 'has_agent' 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2618]
Hello,

We would like to stop relying on GO_REL, and start by removing relations that don't meet GO-CAM specifications.

Please review annotations using the relation  'has_agent'  in extensions:
https://docs.google.com/spreadsheets/d/1-1UMsYfrBGFUV7M2oA-ir4EOsIJuPzUVGHGiUfE27sA/edit#gid=0

Assigned   by | -- | -- | --
AgBase | 12 | 
ARUK-UCL | 74 actually 90 | done all the ones in spreadsheet
BHF-UCL | 7 actually 10 | done
CAFA | 1 | 
MGI | 13 | 
ParkinsonsUK-UCL | 3 actually 4 | done
UniProt | 29 | 
Note that according to QuickGO UCL has 104 has_agent annotations. Some of the annotations are not listed on this spreadsheet.

Thanks, Pascale

**Comment by pgaudet** [comment]
See also comments in 
https://github.com/geneontology/go-annotation/issues/2551

**Comment by milarolo** [comment]
Could you please let me know where I could find the GO-CAM specifications?

**Comment by RLovering** [comment]
Hi
please advise how the following has_agent annotations should be changed:
GO term: heterotypic cell-cell adhesion AE has agent cell type 1; has agent cell type 2
Should we change these to occurs_in cell type 1 (the cell expressing the protein annotated), and delete cell type 2 (the cell 'bound' by cell 1) 
OR should we change these to occurs_in cell type 1 (the cell expressing the protein annotated), and use has_input cell type 2 (the cell 'bound' by cell 1) 

This query will help us revise a considerable number of the UCL annotations.

**Comment by pgaudet** [comment]
I think this is where we would use 'overlaps' 
@thomaspd @vanaukenk @ukemi

**Comment by RLovering** [comment]
Please could you advise on this example too:
PMID:21752258 
Wnt is released from astrocyte (CL:0000127) and 'negative regulation of oxidative stress-induced neuron death' in midbrain dopaminergic neuron (CL:2000097). so the AE field has: has_agent astrocyte (CL:0000127) and regulates_o_occurs_in midbrain dopaminergic neuron (CL:2000097)
Add this example to the regulates_o_occurs_in ticket https://github.com/geneontology/go-annotation/issues/2626
Thanks
Ruth

**Comment by BarbaraCzub** [comment]
Related questions in this ticket: https://github.com/geneontology/go-annotation/issues/2047

**Comment by pgaudet** [comment]
Hi @RLovering 
I cannot find PMID: 21752258 in the spreadsheet above. 
Are you saying Wnt regulates negative regulation of oxidative stress-induced neuron death? 
Assuming this is the case, here's how it would be annotated in Noctua: 

* [some protein] _causally_upstream_of_or_within_ [regulation of protein secretion] _has_input_ [Wnt] _occurs_in_ [some astrocyte]
* [some protein] _causally_upstream_of_or_within_ 'negative regulation of oxidative stress-induced neuron death' _occurs_in_ [some midbrain dopaminergic neuron (CL:2000097)]
* Wnt negatively_regulates [neuron death in response to oxidative stress]
(looking at the abstract, it seems like it would be appropriate to have an annotation describing how the Wnt signaling pathway is linked to negative regulation of neuron death - that seems more relevant than to express in which cell it is produced). 

Sorry that I cannot find the annotation! I hope that helps. 

Pascale

**Comment by RLovering** [comment]
Hi Pascale
In a recent GOC call Chris was supporting the need for the equivalent of regulates_o_occurs_in, and occurs_in so that 2 cell types can be described in a single annotation. Is the final decision now that only one cell type can be specified?
How do we capture the cell types involved in adhesion between heterotypic cells? Are both going to be listed as has_input so that the cell expressing the protein annotated is not clarified?

I would disagree with the suggestion that it doesn't matter which cell secretes wnt. In the brain there are many types of cells that signal to the neurons and each other, understanding which are secreting which hormones/factors/cytokines is something people want to know, if they didn't why would they bother finding this out?
To be honest it is weird how my group appear to have used either regulates_o_occurs_in/occurs_in and has_agent/occurs_in, basically meaning that the 'occurs_in relation has been used in opposite ways). 

If there is any chance of being able to capture the cell the 'factor' is secreted from then personally I prefer the has_agent for the cell expressing the protein which is being annotated as regulating a process in a second cell, and to use occurs_in for the cell that the regulated process occurs in.
For the case of adhesion terms, has_agent would be used with the cell the adhesion molecule is located on and occurs_in would be used for the cell bound by the adhesion molecule.

Finally, while the GO-CAM model looks great, it is not clear how this information would be exported to the standard GOC annotation files. But I assume from your comments that it would not be possible to know that wnt was secreted by an astrocyte.

I have no idea what has happened to PMID:21752258, I have added it to the spreadsheet. please note that it is very rare to know the protein that regulates the secretion of the hormone in these types of experiments. I have edited some of the annotations to follow the model you suggest, but I haven't yet deleted the has_agent cell yet as waiting for confirmation. 

Thanks

Ruth 
@cmungall @BarbaraCzub

**Comment by ukemi** [comment]
Unfotunately, due to the limitations of the GPAD format, there is no way to express the chain relations other than the way we do now or to devise a way to create nested expressions. I would be willing to say let's import them into models, but not export them back out again. In the future if curators want to capture this kind of expressiveness, they should make a model.

**Comment by RLovering** [comment]
Hi David, that sounds great, so we don't need to edit our annotations, so I'll remove My name and Barbara's
Thanks
Ruth

**Comment by ukemi** [comment]
My comment is specifically for the chain relations. I still think we might want to look at has_agent, depending on how you used it.

**Comment by ukemi** [comment]
PS. I've looked at @BarbaraCzub's use of the chain relations and she always used them correctly. So I know they will go into GO-CAM with the right representation. What remains to be determined is if we want them back out again.

**Comment by RLovering** [comment]
Sorry I got my tickets confused. We are keen to keep the has_agent relation, 

Our example for useage is:
GO term: heterotypic cell-cell adhesion AE has agent cell type 1; has agent cell type 2
Ideally we would like to change these to occurs_in cell type 1 (the cell expressing the protein annotated), and use has_input cell type 2 (the cell 'bound' by cell 1)

what else do we need to do to get a decision on this. 

Thanks
Ruth

**Comment by BarbaraCzub** [comment]
Hi @pgaudet, some guidelines will be very helpful indeed! I keep getting error reports from GOA about annotations with the has_agent extension relation, but I do not know what relation I should use instead.

Another example in addition to adhesion annotations is, for instance:
"cell surface receptor signaling pathway involved in cell-cell signaling" where we can use occurs_in for the cell where the surface receptor is expressed, but then the other cell (like in the adhesion examples) was captured using has_agent. So what relation do we use instead? Has_input would probably work fine, but atm Protein2GO does not allow us to use it with cell types/ CL ontology terms ( cc @alexsign ).

**Comment by RLovering** [comment]
Also VEGFA receptor ligand activity how do we state the cell that is producing VEGFA v cell that is binding VEGFA?
I would favour produced_by/has_agent/secreted_by for first cell, and occurs_in for second cell perhaps?
Thanks
Ruth

**Comment by ukemi** [comment]
I think a general issue with this kind of annotation is that we are trying to shoehorn biological complexity into simple annotations and extensions so they can be accommodated by the old annotation paradigm. @vanaukenk?
At some point we need to accept that that annotation method is limited with respect to expressivity.

**Comment by vanaukenk** [comment]
@ukemi We should look at a relevant GO-CAM (http://noctua.geneontology.org/editor/graph/gomodel:5d29221b00001310)
and decide if there are property chains that we could create to give the desired GPAD output.

**Comment by ukemi** [comment]
We should, but I'm not sure we will be able to capture all of the complexities of the model in a GPAD file without invoking the relations that represent property chains. It was my understanding that we were not going to do this.

**Comment by RLovering** [comment]
Hi All
is there any suggestion now for capturing two cell types involved in a adhesion etc?
Thanks
Ruth

**Comment by pgaudet** [comment]
Not yet, sorry.

**Comment by RLovering** [comment]
Hi All

I have discussed this with Barbara. Obviously we would ideally like to keep the information in the AE field. However, we also appreciate that capturing this much information in GO GPAD might not be possible. 

As this problem has been under discussion for such a long time, if it is not likely that a solution will be reached in the near future then we would be willing to create GO-CAM models for this, recognising that the export will not include the same amount of data as the current AE fields.

If you think we should just go ahead with this approach and delete has_agent from our annotations please confirm. If you think additional discussions may lead to a resolution confirm. At present has_agent is only used by about 140 annotations which isn't a great number. Although, as more and more signaling pathways are annotated the importance of communication between cells is likely to emerge as an aspect which it would be good to capture. 

If we are going to create these in noctua it would be good to create a template to edit, is there any suggestion about when templates might be available?

Ruth

**Comment by pgaudet** [comment]
Hi @RLovering 

Sorry this is taking so long. We are still finishing the 'easier' relations, and we'll get to that one after. 
The extensions will not be removed from P2GO (at least not automatically). Thank you for your patience. 

Pascale

**Comment by ukemi** [comment]
Hopefully not confusing things more,  it seems like what we want is the inverse relation of capable_of. (def: A relation between a material entity (such as a cell) and a process, in which the
  material entity has the ability to carry out the process.) example of usage: mechanosensory neuron capable of detection of mechanical stimulus involved in sensory perception (GO:0050974); osteoclast SubClassOf 'capable of' some 'bone resorption'

However, in the case of an annotation what we want is the inverse of: A relation between a
  material entity (such as a cell) and a process, in which the
  material entity carries out the process.

Of course, this doesn't make things any simpler.

**Comment by RLovering** [comment]
Hi 
I have decided to give up on has_agent options. I have removed or changed all has_agent AE relations listed in the linked spreadsheet
Best
Ruth

**Comment by pgaudet** [comment]
All removed
