### ISSUE TITLE
Review annotations using extension 'regulates_o_occurs_in'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2626]
Hello,

We would like to stop relying on GO_REL, and start by removing relations that don't meet GO-CAM specifications.

Please review annotations using the relation 'regulates_o_occurs_in' in extensions:

https://docs.google.com/spreadsheets/d/1nNj09d_gs0Dv2u_Esq3MRMxwzJmy9FQl0mpjovNfuag/edit#gid=0

Impacted groups: 

Assigned   by |  
-- | --
ARUK-UCL | 975
BHF-UCL | 39
FlyBase | 2
MGI | 3167
ParkinsonsUK-UCL | 51
SynGO-UCL | 1
UniProt | 108
WB | 2

Thanks, Pascale

**Comment by milarolo** [comment]
Do we have to delete the extension or replace it?

**Comment by pgaudet** [comment]
This is how we are planning to convert the annotations using extension 'regulates_o_occurs_in'. 
If this correctly represents the data, you can just leave them and when we import these annotations into Noctua, they will be automatically converted: 

<img width="807" alt="image" src="https://user-images.githubusercontent.com/4782928/64725236-7b66ca00-d4d4-11e9-9409-af267f191747.png">


Thanks, Pascale

**Comment by RLovering** [comment]
An example to curate? 
PMID:21752258 
Wnt is released from astrocyte (CL:0000127) and 'negative regulation of oxidative stress-induced neuron death' in midbrain dopaminergic neuron (CL:2000097). This would be captured in the AE field with: 
? relation astrocyte (CL:0000127) and 
occurs_in midbrain dopaminergic neuron (CL:2000097) rather than regulates_o_occurs_in 
Added this example to the has_agent ticket https://github.com/geneontology/go-annotation/issues/2618
Thanks
Ruth

**Comment by BarbaraCzub** [comment]
Related questions in this ticket: https://github.com/geneontology/noctua-models/issues/44

**Comment by pgaudet** [comment]
See my answer in the other ticket #2618

**Comment by ukemi** [comment]
I believe this is out of date. We have a method for importing chain relations into GO-CAM models. These annotations can stay for now.

**Comment by RLovering** [comment]
Great I will remove my name and Barbara's from these
Best
Ruth

**Comment by ukemi** [comment]
Double check with @vanaukenk, but I think these all pass the import tests.

**Comment by pgaudet** [comment]
All done
