### ISSUE TITLE
DNApol-theta not a replicative polymerase PANTHER:PTN000015249

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#2665]
![Screenshot 2019-09-27 at 09 15 38](https://user-images.githubusercontent.com/11865746/65754649-665f7d00-e109-11e9-80e5-2da359a625f1.png)

FBgn0002905 DNApol-theta 
DNA-dependent DNA replication (GO:0006261) | IBA with PANTHER:PTN000015249

DNA pol theta is a DNA repair polymerase and there does not fit in the definition for 'replication' and DNA-dependent DNA replication should be blocked to this node.

The annotation to 'cytoplasm' should also be removed as I think this is unlikely.

There is one source for this annotation, which is probably correct as it appears to correspond to E.coli DNA polymerase I. The problem is the propagation to DNA pol theta in other species (incl, human O75417)

Tagging @sjm41

**Comment by sjm41** [comment]
Further to Helen's previous comment:

PTN000015249 also adds "5'-3' exonuclease activity" to members of the DNA POLYMERASE I (PTHR10133) family, which includes DNA Pol-theta proteins.

The source for that is a single annotation to an E.coli gene.
But eukaryotic Pol-theta proteins lack this activity.
E.g. from PMID: 27657134:
Interestingly, Polθ-polymerase also contains an inactive exonuclease-like subdomain which is homologous to Klenow fragment (Figure 1) [25]. The exonuclease-like subdomain, however, is inactive due to the lack of integral residues needed for metal binding and DNA degradation.

Can you remove this term from the node, or at least block its propagation to eukaryotes?

Thanks.

**Comment by marcfeuermann** [comment]
Updated.

**Comment by hattrill** [comment]
Thanks!

**Comment by sjm41** [comment]
Hi @marcfeuermann 

I still see this MF annotation on the node:
_PTN000015249 also adds "5'-3' exonuclease activity" to members of the DNA POLYMERASE I (PTHR10133) family, which includes DNA Pol-theta proteins
Can you remove this term from the node, or at least block its propagation to eukaryotes?_

**Comment by marcfeuermann** [comment]
Oups sorry, I missed this one :-(   
Also corrected.

**Comment by sjm41** [comment]
Thanks Marc!
