### ISSUE TITLE
PAINT/ MGI:MGI:135496 (lipid, carbohydrate metabolism)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2756]
Is this annotation correct for

inositol polyphosphate phosphatase

(other species are to phosphatidylinositol dephosphorylation)

inp53 | inositol polyphosphate phosphatase Inp53 (predicted) |   | inositol phosphate dephosphorylation |   | GO_Central | Schizosaccharomyces pombe | IBA | MGI:MGI:1354961PANTHER:PTN000127779 more... | inositol 5-phosphatase pthr11200 | protein |   | PMID:21873635 | 20180406

**Comment by ValWood** [comment]
| syj1 | inositol-polyphosphate 5-phosphatase, synaptojanin homolog 1 |   | inositol phosphate dephosphorylation |   | GO_Central | Schizosaccharomyces pombe | IBA | MGI:MGI:1354961PANTHER:PTN000127779 more... | inositol 5-phosphatase pthr11200 | protein |   | PMID:21873635 | 20180406


syj2 | inositol-polyphosphate 5-phosphatase, synaptojanin homolog 2 (predicted) |   | inositol phosphate dephosphorylation |   | GO_Central | Schizosaccharomyces pombe | IBA | MGI:MGI:1354961PANTHER:PTN000127779 more... | inositol 5-phosphatase pthr11200 | protein |   | PMID:21873635 | 20180406


these terms . 
inositol phosphate dephosphorylation
and
phosphatidylinositol dephosphorylation
  are in different branches. One has parent to lipid metabolism and one to carbohydrate metabolism


<img width="835" alt="Screenshot 2020-01-13 at 17 56 09" src="https://user-images.githubusercontent.com/7359272/72279641-7787b780-362e-11ea-9931-0853f6090509.png">

**Comment by hdrabkin** [comment]
I think these are in two different branches because

phosphatidylinositol dephosphorylation I think refers specifically to the phosphatidylinositol (PI) substrate as classified as the glycerophospholipid that contains a glycerol backbone, two non-polar fatty acid tails, a phosphate group substituted with an inositol polar head group. 

I think the inositol phosphate dephosphorylation refers to inositol as the sugar alcohol ( a carbohydrate ) and it's phosphorylated derivatives (IPs) ; as in Inositol trisphosphate which binds it's receptor to release calcium into the cytoplasm.; 

They are related because  Phosphatidylinositol  plays an important role in polyphosphoinositide turnover which produces two second messengers, inositol 1,4,5-trisphosphate (IP3) and diacylglycerol (DG). 

I think the paper in question for Synj1 was annotated to both because the levels of inositol phosphates were being measured so not clear where they come from (the PI or the IPs). 
Synj2 seems to be coming from RGD load using PMID:11498538, which specifically assays the dephosphorylation of the IPs directly (not the PIs) so I think that one holds.
Awaiting a book chapter on IP metabolism

**Comment by ValWood** [comment]
OK  I will close this one.
