### ISSUE TITLE
Review annotations to GO:0005724 nuclear telomeric heterochromatin and GO:0031933 telomeric heterochromatin

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2883]
Hello, 

The terms 'GO:0005724 nuclear telomeric heterochromatin' and 'GO:0031933 telomeric heterochromatin' will be obsoleted, see https://github.com/geneontology/go-ontology/issues/19086.

The telomere is composed of two regions: 
* GO:0000781 chromosome, telomeric region
* GO:1990421 subtelomeric heterochromatin

The telomeric region does not contain heretochromatin. However annotations have been inconsistent so we cannot do a merge. Please review your annotations and change to either GO:0000781  or GO:1990421. This impacts 32 annotations. There are no mappings. 

Please review annotations are here: 

Contributor   (Assigned by) | Number of annotations

**GO:0005724 nuclear telomeric heterochromatin'**
https://docs.google.com/spreadsheets/d/1RvE23pJcnqPLVPAwNz3LLkBdOsn0ZYRibAdSRvU7XWo/edit#gid=0

- [x] FlyBase | 1
- [x] PomBase | 22
- [x] SGD | 5
- [x] UniProt | 4

Thanks, Pascale

**Comment by RLovering** [comment]
I don't understand what is going on. the spreadsheet includes annotations to 
GO:0000784 nuclear chromosome, telomeric region and   GO:0000781 chromosome, telomeric region
This does not state it is heterochromatic. Can't we have a term for the end of the chromosome ie  keep
GO:0000781 chromosome, telomeric region
but have the 2 child terms:

   NEW child term: non-coding TTAGGG-repeat telomere region
    GO:1990421 subtelomeric heterochromatin

Then if there is evidence for the gene product being associated with one of these specifically ie the shelterin complex proteins, then these can be assigned to the telomere  or subtelomere terms

It looks like it is difficult to get evidence which of these the gp is associated with, especially as the telomere repeats are also present in the subtelomere, therefore a grouping term will enable the general location to be stated.

I would be happy for all our annotations to stay with the existing term as the existing definition does not exclude the subtelomere, which also has 'telomeric DNA repeats'. See wikipedia definition of subtelomere https://en.wikipedia.org/wiki/Subtelomere and existance of telomere repeats within specific blocks.

best

Ruth

**Comment by ValWood** [comment]
I think what @colinlog  was saying is that it is  clear to partition between the heterochromatin and the D-loop which is formed from the repetitive tract and is considered to be the telomere  'proper'. This would be independent of the existence of 'old' telomere ends in the subtelomeres. If the region forms heterochromatin it's subtelomeric. At least that was my understanding. @colinlog  can you confirm? Maybe it isn't this simple?

<img width="297" alt="Screen Shot 2020-03-17 at 15 13 36" src="https://user-images.githubusercontent.com/7359272/76870797-1a90c380-6862-11ea-9f72-7612ab934172.png">

I would infer the existing term
GO:0000781    chromosome, telomeric region
The terminal region of a linear chromosome that includes the telomeric DNA repeats and associated proteins.

to refer only to the DNA repeats at the ends of the chromosomes (I'm pretty sure that  "telomeric DNA repeats" at the terminal neds  is intended to refer to the  telomere 'proper')


I hope  this is correct  and isn't going to change again because I spent the past few hours reannotating the PomBase gene products and this worked very nicely. But I work on a simple species.

**Comment by ValWood** [comment]
Ruth  I looked through the human annotations and  most appear to be orthologs of the things I have annotate which occur in the D-loop region

These are the exceptions that seem that they belong in the subtelomeric heterochromatin pot:

- [ ] EZH1 Histone-lysine N-methyltransferase EZH1 Homo sapiens family not named pthr45747
- [ ] SIRT7	NAD-dependent protein deacetylase sirtuin-7	Homo sapiens	family not named pthr45853	protein	UniProtKB	
- [ ] KDM1A	Lysine-specific histone demethylase 1A	Homo sapiens	amine oxidase pthr10742	protein	UniProtKB	
- [ ] H3-3A	Histone H3.3	Homo sapiens	histone h3 pthr11426	protein	UniProtKB	
- [ ] HIST3H3	Histone H3.1t	Homo sapiens	histone h3 pthr11426	protein	UniProtKB	H3FT
- [ ] CBX5	Chromobox protein homolog 5	Homo sapiens	chromobox protein pthr22812	protein	UniProtKB	HP1A
- [ ] HIST1H2BB	Histone H2B type 1-B	Homo sapiens	histone h2b pthr23428	protein	UniProtKB
- [ ] SIRT6	NAD-dependent protein deacetylase sirtuin-6	Homo sapiens	family not named pthr45853	protein	UniProtKB	
- [ ] DOT1L	Histone-lysine N-methyltransferase, H3 lysine-79 specific	Homo sapiens	histone h3 methyltransferase pthr21451	protein	UniProtKB	
 -[ ] HAT1	Histone acetyltransferase type B catalytic subunit	Homo sapiens	histone acetyltransferase type b catalytic subunit pthr12046	protein	UniProtKB	
- [ ] EZH2	Histone-lysine N-methyltransferase EZH2	Homo sapiens	family not named pthr45747	protein	UniProtKB	KMT6
- [ ] HIST1H2AA	Histone H2A type 1-A	Homo sapiens	histone h2a pthr23430	protein	UniProtKB

**Comment by ValWood** [comment]
It seems fairly straightforward if the heterochromatin is confined to the subtelomere?

**Comment by colinlog** [comment]
Yes, the idea is that the T-loop (Telomeric loop, agreed, it does have the
same apparent structure of a Displacement D-Loop, but it is a looped
chromosome end, in fact it is a Telomere loop) involves only the telomeric
repeats. This is the basis for the loop formation, that the terminal 3' end
of the chromosomal telomeric repeats invade the upstream repeats and
displace a part of that strand to form a T-loop.

Hence, the definition 'The terminal region of a linear chromosome that
*includes* the telomeric DNA repeats and associated proteins.' is for a top
term that encompasses *whatever* the terminal region may be. We believe it
should have two descendants that are distinct and *cannot include *one
another. One is a telomere term and all its descendants should only concern
molecules involved in the telomeric repeats and T-loop biogenesis,
maintenance and perhaps erosion. The other is a subtelomere region term
(GO:0099115?) and all its descendants would concern the parts of the
chromosome that abut the telomere region but are not themselves the
telomeric repeat parts and the associated T-loop. In some species, the
sub-telomeric region is heterochromatic (S.c with Sir2/3/4, animals H3K9me3)

**Comment by RLovering** [comment]
OK my understanding is not great. I guess because the human 'telomere' can be anything from 1kb to 11kb depending on the cell examined and the age of the person,  I have assumed that the telomere is the region which is just repeats with no genes. I was under the impression that the loop is very short and that therefore the majority of telomere is not the loop, therefore need to be careful not to define the telomere only based on the loop, as the DNA that makes up the telomere that is not in the loop when you are born will one day be part of the telomere as the repetitive region reduces in length.

**Comment by ValWood** [comment]
but if we define  have the herochromatin and the telomere/T-loop there is no ambiguity. A region can't be both heterochromartin and telomeric presumably?  

Presumably, if the erosion proceeds to a point that you can't form proper telomere ends you have chromosomes ends with no telomeres? -  A telomere is a structure, not a  location...

Nice review for T-loop.
https://www.frontiersin.org/articles/10.3389/fgene.2019.00792/full

**Comment by colinlog** [comment]
I believe I was myself unclear Ruth? I read 'includes' as 'there is more
than what follows'. I probably should ave read 'includes' as 'harbouring
only' the telomeric DNA repeats and associated protein?

Basically, some organisms do not have telomerase but they have linear
chromosomes and therefore telomeres. Drosophilla is one such. So we need a
GO term that is distinct for the terminal regions of any chromosomes called
telomere and a second (child) GO term that is about the telomeric repeats
of most eukaryotic chromosomes. That in turn should have a sibling term
that describes the chromosome region that abuts the telomeric repeats, also
known as the sub-telomeric region. Both are biologically about the ends of
chromosomes commonly referred to in biology as telomeres. Currently these
two (telomeric and sub-telomeric) are not that distinctly
described/annotated, as we found when reviewing the (sub)telomeric
heterochromatin GO terms.

The telomeric repeats are encoded by the TERC internal RNA template
component of the reverse transcriptase that adds telomeric repeats to the
3'end during replication of some stem cells and of most immortal cell lines
(there is also an ALT mechanism of telomere maintenance) . The T-loop is
not a permanent feature as it will likely be disrupted every time a cell
replicates its DNA, regardless of whether that cell posseses telomerase
activity. The G-rich strand of the repeats, regardless of being in the loop
or not, has a propensity to form G-quadruplex structures. The displaced
strand is bound by POT1. In the the loop POT1 also binds the displaced
strand. the T-loop harbours many DNA repair(-like) factors as well as a
complex of complexes called the 'Shelterin complex' made up of TRF1
complexes and TRF2 complexes and TIN2 (etc. etc) that include DNA
recombination factors.

However, there is also the sub-telomeric region. That is usually gene-poor
and not made up of only telomeric repeats, but often rich in specific
families of repetitive elements. The sub-telomeric regions are usually
heterochromatin (in most human chromosomes histone H3 lysine 9
tri-methylation [H3K9me3] is found there), but species, and chromosomes can
differ in these aspects.

Finally, some chromosomes have as 'subtelomeric region, rDNA repeats.
Thisisthe case for human chromosomes 13, 14, 15, 21 and 22 of the human
genome, the five so called acrocentric human chromosomes, because their q
arm is very short and is essentially only made up of sub-telomeric rDNA
repeats (all in all around 400) that nucleate the formation of nucleoli in
human cells.

**Comment by pgaudet** [comment]
The current structure of the ontology is: 

    GO:0000781 chromosome, telomeric region
    GO:1990421 subtelomeric heterochromatin

Maybe we could make GO:0000781 the parent of GO:1990421 and create a sibling new term, chromosome, telomeric loop region? That would allow to annotate to the parent when the data (or the authors) are not clear about which part if the telomere they are looking at. 

@colinlog @ValWood @RLovering What do you think ?

**Comment by RLovering** [comment]
I like this suggestion, I think this was what I trying to propose ;)

**Comment by ValWood** [comment]
In principle think this would work (and I agree with the arrangement)

However, you would need to very clearly broaden  (change) the def of
GO:0000781 chromosome, telomeric region 
to EXPLICTLY refer to the telomere AND the subtelomere.
AND you would need to give those the opportunity  who used  GO:0000781  exclusively for the telomere to make the annotation as specific as they originally intended. 

For this reason, although existing annotations would be correct, I prefer obsoletion.
Also,  we need to remember that GO terms are used to logically define phenotype terms based on the original definition.  So  we should not really broaden terms in the interests of making less annotation work, because there are increasingly knock-on effects outside of GO.

**Comment by colinlog** [comment]
I believe you know the 'best practices' for GO way better than I myself can
envisage right now. But happy to learn ;-)
The desired outcome would be
Telomere (CC?) with two children Telomeric region (CC?) and subtelomeric
region (CC?).
What I wonder is whether we can align definitions with definitions found in
SO, which may have these terms also already? the GO and SO would be using
the same terms with the same descriptions/definitions. Or is such
'federation' of terms not desirable in your opinion?
Cheers, Colin

**Comment by RLovering** [comment]
Hi Colin
I think it depends how these are defined but I believe the plan is:
Telomere region 
>telomere (repeats and loop and no genes)
>subtelomere (repeats and genes, no loop)

SO has:
telomere http://purl.obolibrary.org/obo/SO_0000624
A specific structure at the end of a linear chromosome, required for the integrity and maintenance of the end. 

subtelomere http://purl.obolibrary.org/obo/SO_0001997
A heterochromatic region of the chromosome, adjacent to the telomere (on the centromeric side) that contains repetitive DNA and sometimes genes and it is transcribed.

The parent to both is chromosomal_structural_element. So I don't think we should align complete with this because experiments mean that we need to have a grouping term.
Plus I think we need better definitions.

Ruth

**Comment by colinlog** [comment]
Hi Ruth, thanks for looking it up. Would it then be an idea to refer to the
synonymous term in SO, but to formulate our own -proper- GO definitions? I
further our proposal below. Perhaps the ultimate agreement we reach can
then be added to ticket 19086?

On amigo (http://amigo.geneontology.org/amigo/term/SO:0000624) I got
SO:0000624 back for telomere (!) so it is already implemented in GO to use
the SO term? I personally find it is quite ok as the upper term for our
hierachy, and make a proposal for the description in green (F0) telomere
region-> (i) telomeric repeat region + (i) subtelomeric region F1 children

synonym of SO:0000624 The end of a linear chromosome, required for the
integrity and maintenance of the end. A chromosome telomere usually
includes a region of telomerase-encoded repeats the length of which rarely
exceeds 20 bp each and that prmit the formation of a telomeric loop
(T-loop). The telomeric repeat region is usually preceded by a
sub-telomeric region that is gene poor but rich in repetitive elements.
Some telomeres only consist of the latter part (eg: D. melanogaster
telomeres).

There is the obsoleted term GO:0005696 with definition
A complex of DNA and protein that seals the end of a chromosome. The
telomeric DNA consists of simple tandemly repeated sequences specific for
each species. Typically one strand is G-rich and the other C-rich. The
G-rich strand forms a 3'-terminal overhang, the length of which varies with
species. The single strand overhang is bound by a variety of proteins,
including telomere capping proteins that bind to the single-stranded DNA.
*Source:* ISBN:0198506732
<https://www.worldcat.org/search?q=bn%3A0198506732>, PMID:11352055
<http://www.ncbi.nlm.nih.gov/pubmed/11352055> Comment This term was made
obsolete because the definition was too sequence oriented and too
restrictive.
Shall we resurect 5696  for 'telomeric repeat region' ??? it is precisely
what we discussed. we can add the shelterin speiel if we wish to be
exhaustive...

Then comes sub-telomeric region. There I think we should try Pascale's
suggestion rather than the SO:0001997 definition. Not sure if the term
subtelomeric region exists in GO??? Whatever it becomes, it would become
the parent of GO:1990707 nuclear subtelomeric heterochromatin.   A region
of the chromosome, adjacent to the telomere (on the centromeric side) that
contains repetitive DNA elements and sometimes genes. This region is
usually heterochromatin.



Telomere region

telomere (repeats and loop and no genes)
subtelomere (repeats and genes, no loop)

*So the new stuff really compared to the vey short proposal just above, is
to qualify repeats, one kind being short and telomerase-encoded, the other
larger and being mobile DNA elements, or some such repetitive DNAs that are
significantly larger than the telomeric repeats.*

**Comment by ValWood** [comment]
Note that the SO term and GO for telomere term are different entities . The SO term refers to the "sequence" only. The GO terms are for the physical  biological structures. "DNA  + protein". 
It is OK to refer to the SO terms in the  logical definitions  for GO terms if suitable (i.e. to describe the sequence region where the physical structure occurs), but they are different things.

**Comment by pgaudet** [comment]
Hi @srengel @hattrill 
Sorry this ticket is complicated !! But @colinlog has made suggestions to rehouse your annotations. 

Please review your annotations so we can proceed wit the obsoletion. 
https://docs.google.com/spreadsheets/d/1RvE23pJcnqPLVPAwNz3LLkBdOsn0ZYRibAdSRvU7XWo/edit#gid=0

(I think @hattrill you have reviewed the annotation but it's not marked in the spreadsheet) 


Thanks, Pascale

**Comment by hattrill** [comment]
FB done :)

**Comment by pgaudet** [comment]
@srengel I am going ahead with the obsoletion.

**Comment by srengel** [comment]
SGD now done :)
