### ISSUE TITLE
Review annotations to regulation of cytokine secretion 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2896]
Regulation of x cytokine secretion will be merged into 'regulation of x production' 

Annotations need to be reviewed: 
https://docs.google.com/spreadsheets/d/1CI008Xa-x2ocQWWkltAeME1iiCWFW_g1kYJUvkFruUI/edit#gid=0

More details to come. @addiehl @RLovering and I will make suggestions for how to fix those annotations. 

Thanks, Pascale

**Comment by RLovering** [comment]
Hi Pascale
I think it is misleading to say these will need fixing?

Also I did my own check of annotations associated with the cytokine secretion term. Which are are not listed in your spreadsheet ( I have added one for the record).
ABCA1 is a transporter for IL1beta. The annotated paper https://www.ncbi.nlm.nih.gov/pubmed/11855831 seems to be a bit vague about this but a more recent paper https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6125162/ explains: the secretory routes of mature IL-1β are still not fully understood....We also show that C.pn-induced IL-1β secretion can occur through the ABCA1 transporter, which negatively impacts cholesterol efflux due to competition for this shared transporter.
I had assumed interleukins were mostly exocytosed, but apparently not. I think this would be a case for keeping the ' GO:0032611 interleukin-1 beta production' term. and creating an annotations along the lines of:
ABCA1 'GO:0032611 interleukin-1 beta production', occurs_in macrophage
AND
ABCA1 'GO:0140115 export across plasma membrane' part_of ' GO:0032611 interleukin-1 beta production', has_input IL1beta, occurs_in macrophage
OR
ABCA1    GO:0023061 signal release' part_of ' GO:0032611 interleukin-1 beta production', has_input IL1beta occurs_in macrophage

I have created all of these annotations in Protein2GO but happy to delete them once a decision is made
Ruth

**Comment by RLovering** [comment]
Also I have just added some annotations to this paper https://www.sciencedirect.com/science/article/pii/S0006291X05007898 PMID:15882992 (added to spreadsheet). NLRC4 activates caspase 1 which cleaves IL1B.
So NLRC4 pos reg IL1B production
and Caspase 1 is involved in il1B production, (involved in protein processing/maturation, would be good to have an interleukin processing term)
Ruth

**Comment by suzialeksander** [comment]
associated ontology ticket has been closed.
