### ISSUE TITLE
4 entries for the same GP

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2903]
@hattrill 
have you come across this?

<img width="1179" alt="Screenshot 2020-03-24 at 13 24 09" src="https://user-images.githubusercontent.com/7359272/77430383-00f7fa80-6dd3-11ea-9382-5eb7211bbefb.png">

4 entries for the same gene product,  EXP annotation look identical?

**Comment by hattrill** [comment]
Hi Val,
This is because there are multiple FBgn:UniProtKB ids. When GOA imports annotations made to gene products, it propagates them to the UniProtKB id assoicated with this gene. Ideally, there would just be one swissprot id and any isoforms would be under them. There are various reasons why there might be multiple mappings:  lots of trembls, proteoforms that can't be brought under one SP id, etc. 
When we make new annotations, we use the id from the ref set.
Humans are lucky - most have just a 1:1 UniProtKB:gene as it all been reviewed, other species, such as D.mel, are a bit of a way off. But UniProt are chipping away at it.

**Comment by ValWood** [comment]
Ah OK, of course. I though all the models were 1:1 already ;)
