### ISSUE TITLE
Proposed list of GAF 2.2 qualifiers/relations

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go-annotation#2917]
In order to make greater use of the gene product-to-term relations that can currently be applied in existing curation tools, e.g. Noctua and Protein2GO, we are proposing to expand the list of qualifiers/relations used in GAF Column 4.

For GAF2.2 the value should be a text string that exactly matches the text strings in the list below, i.e. individual words separated by an underscore, e.g. acts_upstream_of_or_within_positive_effect.  When negation (i.e. NOT) and a qualifier/relation are used together, NOT should be pipe-separated from the qualifier/relation, e.g. NOT|enables.

Below is the proposed list:

**Molecular Function**
enables (default) (RO:0002327)
NOT|enables

contributes_to (RO:0002326)
NOT|contributes_to

**Biological Process**
***Note that each annotation group will decide what their default BP relation will be, but in the Relations Ontology 'acts upstream of or within' is the parent relation for all other BP relations.***

involved_in (RO:0002331)
NOT|involved_in

acts_upstream_of (RO:0002263)
NOT|acts_upstream_of

acts_upstream_of_positive_effect (RO:0004034)
NOT|acts_upstream_of_positive_effect

acts_upstream_of_negative_effect (RO:0004035)
NOT|acts_upstream_of_negative_effect

acts_upstream_of_or_within (RO:0002264)
NOT|acts_upstream_of_or_within

acts_upstream_of_or_within_positive_effect (RO:0004032)
NOT|acts_upstream_of_or_within_positive_effect

acts_upstream_of_or_within_negative_effect (RO:0004033)
NOT|acts_upstream_of_or_within_negative_effect

**Cellular Component**
***There are two default CC relations: 1) for localization of gene products, the default relation is 'located in'; 2) for membership in protein-containing complexes, the default relation is 'part of'.***

located_in (default for gene product localization) (RO:0001025)
NOT|located_in

part_of (default for membership in protein-containing complex) (BFO:0000050)
NOT|part_of

is_active_in (RO:0002432)
NOT|is_active_in

colocalizes_with (RO:0002325)
NOT|colocalizes_with

For current 2.1 file format, see: http://geneontology.org/docs/go-annotation-file-gaf-format-2.1/

@cmungall @pgaudet @ukemi

**Comment by hattrill** [comment]
@vanaukenk when can we expect to see the final specs for GAF2.2? I assume that the gp2term rels, as specified above, aren't going to change.

**Comment by vanaukenk** [comment]
@hattrill 
I don't expect the allowed gp2term rels to change.
I'll confirm with the software group about the final specs, but like GPAD/GPI 2.0, I think we'd like to roughly aim for June 1st.

**Comment by hattrill** [comment]
Thanks @vanaukenk 
I guess that adding the gp2term rels into column 4 is the only "real" change? No new columns/data? (just thinking in terms of new data to add to the db or files to map from, so we can get all the upstream bits in place.)

**Comment by hattrill** [comment]
I can forsee us producing GAF2.1 and GAF2.2 side-by-side for a bit while we ask users to update their tools. Is there anything we should think about wrt the naming of these files?

**Comment by hattrill** [comment]
Hi @cmungall @vanaukenk 

I have a question about the relations specified and the RO. This primarily comes about as we are trying to figure out how use these terms in term search. 
The GAF2.2 specifies that the relation name contains underscores. In RO these are without underscores, but I can see subsets, the chado one caught my eye: https://github.com/oborel/obo-relations/blob/master/subsets/ro-chado.obo, that include the underscores. But, the string for terms with commas does not exactly match. 

e.g. for  RO:0004032 in ro-chado.obo:
acts_upstream_of_or_within,_positive_effect
vs 
acts_upstream_of_or_within_positive_effect
in the GAF2.2 spec

Is there a subset of the RO that matches for use with GAF2.2?
I am asking as to be able to differentiate GO annotations with these relations in search displays, we would need to use a cv to index the text strings.

**Comment by vanaukenk** [comment]
@hattrill 
I put this on the agenda for today's GO software call; will let you know what the GO developers say.

**Comment by kltm** [comment]
@hattrill 

What you may be looking for is something like http://purl.obolibrary.org/obo/go/extensions/legorel.owl , which, IIRC, contains the relations used. As far as I know, there is no proper subset in RO--just the manually listed one listed in the spec. @balhoff may be able to provide more clarity on this.

That comma kinda weirds me out, but the commas "really seem to be there". The original of the whole underscore/label thing is unclear to me and I do not know why we are not including it as our (apparently?) unofficial riff on the label. Perhaps @balhoff may be able to provide some idea here as well about the history or rationale?

**Comment by balhoff** [comment]
Is it too late to make the GAF qualifiers use OBO IDs, like GPAD 2.0, instead of labels?

**Comment by hattrill** [comment]
There are a few points here.
1. Ideally we should be consistent with other databases - what we see in QuickGO, Alliance and AmiGO, SGD should all be the same. GAF2.2 and GPAD should be aligned - if we can't directly map the gp2term rels from both files, there will probably be some issues for some users.

(Note the confusion with SGD: https://github.com/geneontology/helpdesk/issues/252). 

At the moment, these underscored strings are kind of a soft cv that map to real cv terms.

2. If we use RO ids in this space, then I am ok with this, we will then use the term name from the RO in FB. 

3. I am with @kltm  in the dislike of commas - they have unintended consequences. I feel this is probably tangential, but having a string w/o commas makes it easier to read by humans and computers. If there could be any movement on this....I have some suggestions!

(If we stick with underscores in GAF2.2, then having 
acts_upstream_of_or_within,_positive_effect
rather than
acts_upstream_of_or_within_positive_effect
is better for consistency.)

**Comment by kltm** [comment]
@hattrill @balhoff @vanaukenk 

I think the context of the GAF 2.2 is important here: it is the last whimper of a doomed format. The future is GPAD/GPI 2.0 (or serialized GO-CAM); that's what the universe of exchange should look like and it's quite a nice, especially compared to the weirdnesses we get in GAF. To squeeze just a little more water out of the stone that is GAF 2.1, the desire is for the change to be as close to GAF 2.1 as possible--hopefully allowing GO groups to make the change with very minor tweaks--while still accomplishing the required useful work. To do this, there are two changes:

* Qualifier field is required. This is an easy format change for parsers (if not emitters) because is is still valid GAF 2.1
* Qualifier field is from an expanded list. This should again be fairly easy for parsers (just increase the number of legal strings), but harder for emitters, which will need to figure out an appropriate relation.

Given this, I think that proper IDs are off the table in this timeline--that would require every group to revisit the column in a more fundamental way. I'm not sure how much wiggle room there even is for the comma question (re: https://github.com/geneontology/geneontology.github.io/blob/issue-go-annotation-2917-gaf-2_2-doc/_docs/go-annotation-file-gaf-format-22.md), as this list was pretty much approved at the last GO meeting and switching it now, as idiosyncratic as it might be, would probably slow things down with a new round of questions and feedback. 

Also, @hattrill, we have no guidance for naming, but I might suggest that they live in a gaf2.2 directory in parallel until the switch is made, which will make it easier for testing.

**Comment by balhoff** [comment]
@kltm that makes sense. Then I think it is important to just state (as you are) that the list of allowable values is exactly the strings listed in the spec. The spec states a mapping from these strings to an RO identifier. Any relation of these strings to the rdfs:label provided for an RO identifier within RO is beside the point, and no one should attempt to construct these from RO labels via any automatic space-replacing procedure.

**Comment by balhoff** [comment]
(there currently is an automatic space-replacing procedure for relation labels in the Minerva GPAD export, which happily will go away with updating to the new GPAD spec)

**Comment by vanaukenk** [comment]
@kltm @balhoff 

Yes, I agree that makes sense and just to be clear, we will NOT be including commas in the strings for the gene product-to-term relations in GAF2.2; we'll proceed with relation strings as they're listed in the github spec linked in Seth's comment above.

**Comment by hattrill** [comment]
Ok. 
In the future, what version will users see in AmiGO and Alliance pages?

**Comment by kltm** [comment]
I have no information for Alliance ATM, but I would say "GAF 2.2" for GO as soon as we have switched over--the strings as defined on the format. Again, while there could be a data hiccup, there  no real change in the pipeline and display systems as long as we pass the data through--this is a data update for upstream providers mostly: already, essentially the exact same thing as what we have now except in an increase an acceptable values.

**Comment by hattrill** [comment]
Hi @vanaukenk - what are the default qualifiers for ROOT terms?

**Comment by vanaukenk** [comment]
@hattrill 

For MF, I think we can safely use 'enables'.

For BP and CC, we can either go to the most or least specific relations.  I'm tending towards the more specific relations, but have an email out to @thomaspd and @cmungall to also get their thoughts.  Either way, we will need to document this internally and for our users.

@ukemi @pgaudet

**Comment by hattrill** [comment]
thanks @vanaukenk

**Comment by hattrill** [comment]
Hi @vanaukenk any final word on this:
molecular_function (ND) enables 
biological_process (ND) involved_in
seem like the only real choice for root,

but can we safely go for
cellular_component (ND) located_in

seems to make sense to me....I don't know where it is located???

**Comment by vanaukenk** [comment]
@hattrill 

This is on the agenda for today's manager's call.  I hope to post a final decision after that.  Thx.

**Comment by hattrill** [comment]
Thanks @vanaukenk (would be great to have this soon as we are trying to retrofit data in test DB at the moment)

**Comment by vanaukenk** [comment]
@hattrill 

We discussed this on the manager's call and agreed that groups should consistently use the more specific gene product-to-GO term relations for all root node annotations:

biological_process (GO:0008150) involved_in (RO:0002331)
molecular_function (GO:0003674) enables (RO:0002327)
cellular_component (GO:0005575) is_active_in (RO:0002432)

I've updated the documentation here:
https://github.com/geneontology/geneontology.github.io/blob/issue-go-annotation-2917-gaf-2_2-doc/_docs/go-annotation-file-gaf-format-22.md

And added this information to the "ND Evidence Code" [wiki page](http://wiki.geneontology.org/index.php/No_biological_Data_available_(ND)_evidence_code#Gene_Product-to-Term_Relations).

**Comment by hattrill** [comment]
Thanks, @vanaukenk

**Comment by hattrill** [comment]
Hey @alexsign could you add these can a rule/check in P2GO?
Thanks 
"GO term relations for all root node annotations:
biological_process (GO:0008150) involved_in (RO:0002331)
molecular_function (GO:0003674) enables (RO:0002327)
cellular_component (GO:0005575) is_active_in (RO:0002432)"

**Comment by prmani** [comment]
@vanaukenk , GPAD lists qualifier-relation column as "relation|qualifier" , for example "acts_upstream_of_or_within|NOT", shouldnt it be the reverse ? (our parser will need to know this), or I can recode to make it agnostic .  who do I as about this?

**Comment by vanaukenk** [comment]
@prmani 
Do you mean for GPAD 2.0?  If so, GPAD 2.0 has a separate column for negation.
https://github.com/geneontology/go-annotation/blob/master/specs/gpad-gpi-2-0.md

**Comment by prmani** [comment]
Right! Sorry I was having a complete brain freeze! I was looking at the old file.. :)

**Comment by vanaukenk** [comment]
No worries.  Lots of moving parts right now :-)

Thanks for checking.

**Comment by hattrill** [comment]
@kltm is it possible to test the GAF2.2 load? We have a file.....

**Comment by kltm** [comment]
@hattrill It may be possible to check individual files; full run throughs are not quite ready yet. For testing, the ticket to hang out on would be https://github.com/geneontology/go-site/issues/1562#issuecomment-723263458
