### ISSUE TITLE
InterPro2GO for Phosphotransferase KptA/Tpt1 (IPR002745)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#2920]
http://www.ebi.ac.uk/interpro/entry/InterPro/IPR002745/

Current GO-MF term is quite high-level:
transferase activity, transferring phosphorus-containing groups (GO:0016772)

But InterPro description and associated EC xref (2.7.1.160) suggest this more specific MF term could be used instead:
tRNA 2'-phosphotransferase activity (GO:0000215)

Can you review please?

@hattrill @happy-lorna

**Comment by EBI-Hsinyu** [comment]
Hi, 
Thank you for the e-mail. The problem is that there are some homologues that do not have this pathway. I updated the abstract to explain this (as below). In fact, NAD+ ADP-ribosyltransferase activity (GO:0003950 ) is mentioned by Munir et al.. I have replaced the original GO term with GO:0003950. 

"Many Tpt1 homologues have no obvious need for an RNA 2'-phosphotransferase because: (i) they lack tRNA introns; and/or (ii) they are not known to have an enzymatic pathway that generates 2'-PO4, 3'-5' phosphodiester RNA structures. There are more evidence showing that Tpt1 homologues are not limited to the canonical activity of Tpt1 healing the 2'-PO4, 3'-5' phosphodiester RNA splice junction formed during fungal and plant tRNA splicing. Instead, the ADP-ribosyl transfer to a phosphorylated substrate is the unifying mechanistic feature of Tpt1-catalyzed reactions."
PMID: 30202863
PMID: 31019096

Regards, 
Hsin-Yu

**Comment by sjm41** [comment]
Hi Hsin-Yu

I just stumbled across this InterPro2GO association again.

Last time round, you changed changed the MF to "NAD+ ADP-ribosyltransferase activity (GO:0003950)" because PMID: 31019096 states "ADP-ribosyl transfer to a phosphorylated substrate is the unifying mechanistic feature of Tpt1-catalyzed reactions, which are not limited to the canonical activity of Tpt1 healing the 2′-PO4, 3′–5′ phosphodiester RNA splice junction formed during fungal and plant tRNA splicing."

Problem is that the canonical activity (tRNA 2'-phosphotransferase activity (GO:0000215)) described for yeast and mouse at least (and propagated to orthologs via http://www.pantree.org/node/annotationNode.jsp?id=PTN000293810) isn't a child of that term:
![Screenshot 2021-04-30 at 16 13 47](https://user-images.githubusercontent.com/16306861/116715923-14f72e00-a9cf-11eb-8848-6715032e81a2.png)

So, I think the MF for IPR002745 may have to be 'transferase activity' (GO:0016740)?
(Unless there is a parentage issue within the GO structure?)

**Comment by EBI-Hsinyu** [comment]
Hi Steven, 

You are right. GO:0016740 is better suited for this entry. I have replaced this GO term, and this will be visible in InterPro86.0.

Regards, 
Hsin-Yu

**Comment by sjm41** [comment]
Great, thanks Hsin-Yu!
