### ISSUE TITLE
Is KDM5A, P29375, a coTF or a dbTF?

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#3008]
Hi Colin

https://pubmed.ncbi.nlm.nih.gov/18270511/ confirms RBP2 (KDM5A, P29375) binds a 6 base motif CCGCCC, has enzyme activity and regulates transcription. In November I annotated this as a dbTF with the following statement in P2G: Colin Logie confirmed this has DNA binding TF activity based on DNA binding and regulation of transcription Nov 2019 [rl].

I know that these proteins are difficult to call, but these can be used to help clarify guidelines. I think we have to admit that there will always be some errors in our dbTF v coTF lists, however would you mind revisiting this protein to double check whether this should be a dbTF or a coTF.

Best

Ruth

@pgaudet

**Comment by colinlog** [comment]
https://pubmed.ncbi.nlm.nih.gov/18270511/ 

Figure1: the demethylation brought about by transient overexpression is global and cannot therefore be 'gene specific' not good for GO:0003700
Figure 2: Affinity is not sub-micromolar, so ok, but not super-convincing. Therefore sequence specific DNA binding GO:0043565 annotation may well be supported
Figure 3: structure of DNA binding, supports Figure 2
SupFigure 6: does not rule out the co-factor hypothesis, much hand waving in the figure legend about residual activity. 

Other knowledge:
KDM5A is an oxygen sensor (PMID:30872526) and as such it appears to be involved in controling levels of H3K4me3 in HeLa cells. Also in that study, it is not obvious that it is intrinsically gene-specific or a dbTF?

Conclusion: as we set out in the guidelines, even having gene-specific effects cannot prove dbTF status, as the same is expected of dbTF coregulators that the dbTFs rely on.  Parsimony would dictate to keep the co-activator annotation for KDM5A, and to not or very very cautiously annotate KDM5A as a dbTF factor. However sequence specific binding cannot be refuted without evidence to the contrary. Liefke et al 2010 do say this as data not shown, see last paragraph of this annotation review. the question that remains open is whether sequence specific DNA binding activity is truly important for biology that KDM5A. More research will show that, or not.

Importantly: the binding site CCGCCC has not yet been found _in vivo_ for KDM5A. So there is no chromatin IP data that would correlate the motif with KDM5A occupancy, and investigate (i) whether mutation in the DNA binding domain of KDM5A would show loss of DNA bindng on those regions and (ii) whether mutation of the DNA binding domain will lead to loss of recruitment to the promoters it is bound to. So the recruitment by dbTFs such as RBPJ remains most likely hypothesis. G&D paper of December 2019: PMID:31727771 does not make any mention of sequence specificity of KDM5A, they still have a model where it is a corepessor for RBPJ and the intracellular domain of NOTCH.

Indeed, it is well known that KDM5A interacts with RBPJ and represses the activity of the nuclear NOTCH activation complex (Liefke et al. 2010). That paper shows in Figure 4G that KDM5A depends on RBP-J to bind to promoter DNA of the Deltex-1 promoter. So KDM5A is definitely a co-repressor. I miss this type of experimental aproach in the 2008 https://pubmed.ncbi.nlm.nih.gov/18270511/  paper used to claim that KDM5A is a sequence specific TF, namely that the DNA binding domain is important to target KDM5A _and._ that if you remove it's DNA binding site in a promoter, it is not bound there anymore. Admittedly it is more difficult to prove direct DNA binding in vivo than it is to prove the dependence on a bona fide dbTF for KDM5A recruitment... 

Liefke et al 2010 discussion
"
Although it has been suggested that the Arid domain of KDM5A can bind to a short DNA sequence, CCGCCC (Tu et al. 2008), the importance of this finding is challenged by the fact that this sequence is very common in CGIs, yet KDM5A is found only at a small number of genes in ChIP-on-chip experiments (Lopez-Bigas et al. 2008; Pasini et al. 2008). Morover, 11 of these putative KDM5A DNA-binding sites can be found at the CGI of Deltex-1, but only one is present in the Deltex-1 enhancer. Therefore, no correlation exists between the position with a high density of putative KDM5A-binding sites and the dynamically regulated H3K4 trimethylation site at the Deltex-1 gene. **Furthermore, in EMSA assays we could not corroborate binding of KDM5A at the proposed sites (data not shown).** Thus, we hypothesize that the PHD3 domain of KDM5A binds to H3K4m3 at active promoters, and once the H3K4me3 substrate is demethy- lated, KDM5A is released.

"

Annotation conclusion: the evidence level to enter the select club of sequence-specific DNA binding transcription factors is quite high. KDM5A was almost there, it has the sequence-specific DNA binding activity form the 2008 paper. However, I am still not sure it really finds its way to its target genes by directly binding DNA via it ARID domain. Hene KDM5A is still most likely fitting to the curator guidance comment for GO:0003712 transcription coregulator activity 
"
Curator guidance: Most transcription coregulators do not bind DNA. Those that do usually bind DNA either in a non-specific or non-direct manner. 
"
This curator guidance was specifically written to deal with the ARID domain proteins, and KDM5A has as alternative name: Jumonji/ARID domain-containing protein 1A (JARID1A). Most of the field does not believe JARID1A is a dbTF. Most of the field believe it is a coregulator! 

Note also: as it is a H3K4me3 demethylase, KDM5A would naturally be classified as a corepressor. However, it may in some contexts be an epigenetic coactivator, since the yeast KDM5 ortholog JHD2 appears to cooperate with the SET1 H3K4 trimethylase in maintaining gene activity potential, rather than to oppose it, by virtue of only erasing H3K4me3 from nuclesomes where only one of the two Histone H3's are trimethylated on lysine 4 PMID:30842216.

**Comment by RLovering** [comment]
Hi Colin

thank you so much and I am so sorry you have had to do such a big investigation. I am just trying to work out how we can explain in guidelines why we make a call one way or the other for these more difficult proteins

Best

Ruth
