### ISSUE TITLE
PANTHER:PTN000775508  - PTHR30511 - D-alanine biosynthetic process

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3100]
I don't think that D-alanine biosynthetic process is the physiological role here is it?

alr1 | alanine racemase Alr1 |   | D-alanine biosynthetic process |   | GO_Central | Schizosaccharomyces pombe | IBA | PANTHER:PTN000775508 UniProtKB:P0A6B4 UniProtKB:P9WQA9 | alanine racemase pthr30511 | protein

(and alr2)

**Comment by ValWood** [comment]
similarly 
sry1 | serine racemase Sry1 |   | D-serine biosynthetic process |   | GO_Central | Schizosaccharomyces pombe | IBA | MGI:MGI:1351636 PANTHER:PTN000034721 more... | serine / threonine racemase family member pthr43050 | protein |   | PMID:21873635 | 20170228

maybe it is relevent in higher eukaryotes but not yeast?

**Comment by ValWood** [comment]
I believe are largely toxic to yeast do conversion is likely to be D->L. It is possible there are some D- amino acids in the cell wall, but I can't find any real; evidence, and no evidence that these enzymes are involved.

**Comment by pgaudet** [comment]
Wikipedia states "The right-handed form, D-alanine, occurs in polypeptides in some bacterial cell walls[5]:131 and in some peptide antibiotics, and occurs in the tissues of many crustaceans and molluscs as an osmolyte" (https://en.wikipedia.org/wiki/Alanine)

From the paper cited for pombe, PMID:11244061 "S. pombe uses D-alanine as a sole nitrogen source", so perhaps the pombe annotation should be D-alanine catabolic process, rather than metabolic ?

**Comment by ValWood** [comment]
You mean rather than "biosynthetic?"

That would work I guess.  Is it really catabolism though, its conversion to L-alanine  for use.

Metabolic would be OK.

**Comment by pgaudet** [comment]
> alr1 | alanine racemase Alr1 |   | D-alanine biosynthetic process | pthr30511


Annotation is already gone. 


> sry1 | serine racemase Sry1 |   | D-serine biosynthetic process |   | GO_Central | Schizosaccharomyces pombe | IBA | MGI:MGI:1351636 PANTHER:PTN000034721 more... | serine / threonine racemase family member pthr43050 

Removed
