### ISSUE TITLE
cspA P0A9X9 - change annotation transcription -> regulation of transcription

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#3118]
Hi @keseler 

In PMID 1961761: cspA P0A9X9 is not directly mediating transcription, it it a regulator 

Thanks, Pascale

**Comment by keseler** [comment]
Hi @pgaudet,

I changed that annotation in EcoCyc (and in fact removed the other annotations to GO:0006351 as well, because they weren't right either). As you know, though, this will take its sweet time to trickle down into our E. coli GAF.

There are likely a boatload more annotations for other txn regulators to GO:0006351 that should probably be more specific and say regulation; will you eventually run into these as well, or was the cspA annotation a one-of because the papers cited didn't support this GO term?

Cheers,
Ingrid

**Comment by pgaudet** [comment]
Hi @keseler 

I came across this one a bit randomly while doing PAINT curation. We will try to do more systematic consistency checks on all the transcription factors at some point in the future (right now we are focusing on fixing human misannotations). 

Thanks, Pascale
