### ISSUE TITLE
NR0B1/DAX1 (P51843): is binding to double-strand a really key feature for classifying a protein as DbTF?

### ISSUE THREAD

**Issue by mlacencio** [geneontology/go-annotation#3135]
Dear @RLovering, @pgaudet, @colinlog 

Me, Martin and Astrid think that the main question here is: Can't we consider proteins that bind single-stranded DNA specific sequence DbTFs and show a clear role as transcription regulator as DbTFs? Is there any consensus among the transcription regulation community about this? If yes, please, let us know. If not, maybe we should reach an agreement. In any case, we should make this aspect clear in the curation guidelines.

If we agree that DbTFs can also bind single-strand specific sequences, then there are at least one  paper to support NR0B1 role:
PMID:9384387: hairpin binding in promoter. from paper: Binding sites for DAX-1 are found in the promoters of the dax-1 and StAR (for steroidogenic acute regulatory protein) genes. DAX-1 binds DNA and acts as a powerful transcriptional repressor of StAR gene expression (checked by Martin Kuiper)

Thanks!

**Comment by pgaudet** [comment]
Hi @mlacencio 

Good point ! As pointed out in the guidelines we have written (https://docs.google.com/document/d/1bqCxx7QUblrc9q4PIynbJzoCXv248UWBxJa7fguJyXs/edit#), it is useful to review the literature before making a call on a gene's function, especially when the activity is not clear. The paper you cite is from 1997. Clearly the function of this gene is not straight forward, especially that there is a spliced isoform with potentially a different function. 

In this case however, binding a hairpin, rather than a specific sequence, probably counts as a coTF rather than as a TF. 

@colinlog thoughts? 

Thanks, Pascale

**Comment by pgaudet** [comment]
@mlacencio Note that there is a function: 'DNA hairpin binding' that you can annotate.

**Comment by colinlog** [comment]
I concur with Pascale; coTF is what fits the biochemistry and bioinfo
observations. Structured DNAbinding is not sequence specific, and we really
do double strand DNA binding for the dbTFs.

**Comment by RLovering** [comment]
FYI on the P2G dispute I wrote the following:
I have discussed this with Colin and he has stated that: if the DNA binding is to single strand DNA, that is not evidence for DAX1 being a dbTF. The literature definitely points at a corepressor MF. Unless there is a convincing double strand DNA binding (not single stranded) experiment. I have disputed the InterPro mappings too see https://github.com/geneontology/go-annotation/issues/2981 Please remove these annotations Thanks Ruth

Note that the InterPro IPR001723 has removed the DNA binding. Please delete this annotation

I have closed the P2G dispute so that the discussion can be conducted here rather than by email

**Comment by mlacencio** [comment]
Dear @RLovering and @pgaudet

I have removed the annotations!

Best,

Marcio
