### ISSUE TITLE
Q86SX6 + small molecule metabolic process

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-annotation#3240]
This annotation looks odd, 
Fe/S biosynthesis protein Q86SX6 has small molecule metabolic process TAS  Reactome:R-HSA-1430728

I think this can be removed? The term is defined:
The chemical reactions and pathways involving small molecules, any low molecular weight, monomeric, non-encoded molecule.

so Fe/S clusters are not 'small molecules' by definition?

**Comment by pgaudet** [comment]
@deustp01

**Comment by deustp01** [comment]
This happened because we failed to put an appropriate GO term,  GO:0016226 iron-sulfur cluster assembly, on our pathway "Mitochondrial iron-sulfur cluster biogenesis", a child of our "[small molecule] metabolism" pathway (R-HSA-1430728). I'll add the GO BP term - the fix will propagate to our public site in our December release.

Bur I think Fe/S clusters are small molecules: CHEBI:30408 iron-sulfur cluster - Definition | An iron-sulfur cluster is a unit comprising two or more iron atoms and bridging sulfur ligands.

**Comment by Antonialock** [comment]
> Bur I think Fe/S clusters are small molecules: CHEBI:30408 iron-sulfur cluster - Definition | An iron-sulfur cluster is a unit comprising two or more iron atoms and bridging sulfur ligands.

I guess they are not 'big' molecules, but the def of was just going on the def of ' small molecule metabolic process' specifically states 'monomeric' molecule, I wasn't entirely sure what that means, and if Fe/S is considered  'monomeric'

**Comment by deustp01** [comment]
Aha! That points to another Reactome mis-annotation. GO makes a distinction between small-molecule metabolism and metabolism, with entities like dimers (sucrose, for example) excluded from small-molecule. Reactome doesn't, so our grouping pathway "Metabolism" needs  GO:0008152 "metabolic process" as its GO BP term. Also now fixed for propagation to public site in December.

**Comment by Antonialock** [comment]
Thanks!
