### ISSUE TITLE
AIRE O43918 is not a dbTF

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#3273]
Hi Pascale and Marcio

Colin has provided more information about why this protein is not a dbTF, but can be curated as a coTF. Colin points out that although the protein may bind DNA specifically, it does not provide a genomic address. I have reviewed the data in each of the 3 papers annotated and suggested whether the annotation is supported or not below.

(this paper is not curated) https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5310976/
from Intro:
Aire appears not to bind to a particular promoter or enhancer motif, exhibiting only a low, non-discriminatory affinity for DNA11. Rather, it seems to recognize generic features of transcriptionally quiescent sites, like chromatin marks typical of silenced loci, e.g. unmethylated lysine 4 of histone 3 (H3K4me0)11,12, and promoters with stalled RNA polymerase II (RNA-PolII)13,14.

(this paper is not curated) https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3258631/
from Intro: Aire binds chromatin through an interaction between its PHD1 domain and the amino-terminal tail of histone H3, but only in its hypomethylated state, a mark associated with poorly transcribed genes (9–12).

Existing annotations (as well as a couple of PAINT annotations)
Pascale please remove - DONE- : O43918 | AIRE | GO:0000976 | transcription   regulatory region sequence-specific DNA binding | ECO:0000314 (IDA) | PMID:18292755
-- | -- | -- | -- | -- | --
Marcio - this one can stay: O43918 | AIRE | GO:0000977 | RNA polymerase II   transcription regulatory region sequence-specific DNA binding | ECO:0000314 (IDA) | PMID:11533054
Marcio - please remove: O43918 | AIRE | GO:0001228 | DNA-binding   transcription activator activity, RNA polymerase II-specific | ECO:0000315 (IMP) | PMID:11274163
Pascale please check that the PAINT annotations do not propagate the sequence specific DNA binding nor the dbTF annotations.

Information extracted from the curated papers:   
PMID:18292755 paper title:The autoimmune regulator PHD finger binds to non-methylated histone H3K4 to activate gene expression.
In results: Thus, AIRE interacts, by means of its first PHD finger, specifically with histone H3 in both isolated and nucleosomal contexts. The DNA binding data is ChIP and the authors discuss this as chromatin binding.

PMID:11533054 paper (2001) title The autoimmune regulator   (AIRE) is a DNA-binding protein abstract states: AIRE dimers and tetramers,   but not the monomers, can bind to G-doublets with the ATTGGTTA motif and the   TTATTA-box. Competition assays revealed that sequences with one TTATTA motif   and two tandem repeats of ATTGGTTA had the highest binding affinity.
https://www.jbc.org/content/276/44/41357.long 
Colin please comment on this data and why this data is NOT sufficient for sequence specific binding (note recombinant protein expressed in e coli)

PMID:11274163 paper (2001) title: Subcellular localization   of the autoimmune regulator protein. characterization of nuclear targeting   and transcriptional activation domain. Abstract states: AIRE can activate the interferon beta minimal promoter in a transfection assay
But luciferase assay in COS cells and already had low level of transcription so this does not confirm DNA sequence-specific binding.

Thanks

Ruth

**Comment by colinlog** [comment]
Hello, Although the 2001 paper is unambiguous as to the DNA binding activity, AIRE is really involved in a very special gene expression program that involves expressing ANY human gene in the thymus (medullary thymic epithelial cells ) so as to educate T-cells with all possible endogenous MHC-presented antigens. This does NOT involve sequence-specific DNA binding but rather the stochastic activation of any promoter via interaction with nucleosomes with its PHD domain (protein-protein interaction, not DNA-dbTF interaction) (PMID: 18292755 and 26084028 also referenced on the Uniprot page for AIRE). Hence, at a first glance, I do not believe it is smart to propagate the 2001 sequence-specificity as such. Also because I do not know of an endogenous gene target for AIRE that depends on such a response element.  In other words, where is the second part of the definition of a dbTF, namely that this protein activates at least one gene by recognizing a genomic DNA sequence in its promoter or enhancer? I believe that is the major idea in current reviews about AIRE function. Having said that, perhaps someone will show that AIRE is a dbTF in a particular type of brain cell (where it is weakly expressed)? So, I would not want to dispute the 2001 annotation as to sequence-specific DNA binding. But AIRE is not a genomic address reader, as far as I can gather.

**Comment by pgaudet** [comment]
PAINT now only has 'RNA polymerase II transcription regulatory region sequence-specific DNA binding IBD' - I think this is correct ?

**Comment by pgaudet** [comment]
@mlacencio can you please fix the disputed annotation ?

**Comment by RLovering** [comment]
Pascale: I think Colin's comments do support keeping the DNA binding term you suggest

**Comment by mlacencio** [comment]
Hi @RLovering !

It does make sense that AIRE can't be considered a DbTF as it can't provide a  genomic address at least in mTECs in thymus. Additionally, the  papers mentioned by you provide strong evidence for a coTF activity. However, before correction, I would like to know what is "IBD".

Thanks!

Marcio

**Comment by pgaudet** [comment]
Hi @mlacencio 

IBD is the evidence code we give to ancestral nodes (inferred from biological descendants). Sorry about the jargon ! 

Thanks, Pascale

**Comment by RLovering** [comment]
Hi Marcio
we have only about 20 human proteins still annotated as dbTFs which shouldn't be. It would be great if these could get fixed soon. I will add this text to all of the outstanding tickets if I can find them.
Hope all is well with you
Ruth

**Comment by mlacencio** [comment]
Dear @pgaudet and @RLovering ,

Pascale, thanks for the clarification!

Ruth, I will do it until Friday this week! Sorry for my one-month silence. I am doing well, thanks for asking.

Best,

Marcio

**Comment by RLovering** [comment]
Brilliant, thanks again Marcio, really appreciate having these issues all closed now
Best
Ruth
