### ISSUE TITLE
PTN000317629  not GO:0003714	 transcription corepressor activity  - PTHR13082

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3413]
sap18 |   | IBA with PTN000317629 , FBgn0024491

sap18 is a splicing factor

**Comment by ValWood** [comment]
@hattrill

**Comment by hattrill** [comment]
We have quite a number of papers that say it is a  transcription coreg and a splicing factor:
some examples:
#SUBMITTED ID	PUBMED_ID	TITLE
FBrf0218368	22388736	The structure of the ASAP core complex reveals the existence of a Pinin-containing PSAP complex.
FBrf0206861	19049982	SAP18 promotes Krüppel-dependent transcriptional repression by enhancer-specific histone deacetylation.
FBrf0188188	16135462	dSAP18 and dHDAC1 contribute to the functional regulation of the Drosophila Fab-7 element.
FBrf0192573	16823614	Drosophila dSAP18 is a nuclear protein that associates with chromosomes and the nuclear matrix, and interacts with pinin, a protein factor involved in RNA splicing.

PMID:22388736 "The emerging picture of the ASAP complex is that of an assembly of proteins at the interface between transcription, splicing and NMD. It thus appears to be a hub in the protein interaction network that regulates gene expression."

**Comment by ValWood** [comment]
Some of the splicing factors are involved in chromatin  assembly. Is that one of these?
I'm still not sure "transcription corepressor activity" is the correct term as that implies that it binds directly to a DNA binding TF?

**Comment by hattrill** [comment]
Searching with SAP18 on pubmed - lots of splicing and co-reg papers. 

I am pretty sure that we decided that coregulators could be part of a repressor complex.

PMID:19049982 and PMID:11256608 detects direct binding with a DNA binding TF.

Acts in a HDAC or as a HDAC-TF bridge.

**Comment by ValWood** [comment]
OK, will look further...

**Comment by ValWood** [comment]
OK this makes sense but I don't think it should be transferred to yeast (which do not have kruppal)

**Comment by hattrill** [comment]
That sounds sensible - probably an acquired function.

In general, I think that when a PAINT node only has one supporting entity, unless it really is a 'no brainer' - like a ribosomal subunit - then it should not be propagated. Most of our disputes seem to arise from single entity transfers.

**Comment by marcfeuermann** [comment]
Just for information, a PAINT curator does not only look at the primary GO annotations, but also checks annotations in the different model and non-model databases as well as what's in the literature. Personally, I'm also checking the protein sequences for the presence of specific features (such as trans-membrane domains when there is a membrane location term). 
In the case of the PTHR13082 family, in addition to D. melanogaster, transcription repression has also been shown for human SAP18 (PMID:9150135, PMID:17002296 ,... ), even if it is not yet annotated in GO. Moreover,  PMID:16429262 also shows that the Arabidopsis thaliana SAP18 homolog is involved in transcription repression:
"Our results indicate that AtSAP18 functions to link the HDA complex to transcriptional repressors that are bound to chromatin in a sequence-specific manner, thereby providing the specificity of signal transduction accompanying transcriptional repression under stress conditions.
So we have quite a few evidences that SAP18 homologs interact with HDA complexes to repress transcription (when broadening the search outside of GO) and it is once again not a case of "single entity transfer". Therefore I think it was reasonable to propagate this activity. It is possible that the activity was lost in fungi (but lets keep in mind that it is not because something has not been studied that it does not exist). One possibility would be to block this term in fungi, but without any conviction.
I would be happy to have some more input.

**Comment by hattrill** [comment]
Hi @marcfeuermann 
We do come across many examples where we raise a ticket about a single entry. Our curators try to mention if it is a single entry in the ticket, so can be searched in a crude fashion:
https://github.com/geneontology/go-annotation/issues?q=single+

**Comment by ValWood** [comment]
I still think that the role here is in some aspect of heterochromatin  organization.
As such, I don't think 
GO:0003712    transcription coregulator activity/corepressor
 is the correct term.

I would tend to go to
GO:0140110    transcription regulator activity, until we know what the exact role in  gene expression is (or even just regulation of transcription). I still don't think it is a  co-repressor unless you have really good evidence that it operates by binding directly to a DNA-binding transcription factor. This seems unlikely y as most of the data indicates some connection to histone acetylation.

More likely it is one of many splicing components that affect gene expression  through chromatin organization and this looks like one of these?

@colinlog

**Comment by hattrill** [comment]
I am not sure how this does fit with def - it does bind DNA binding TFs and the Def for transcription coregulator activity has scope for chromatin modification?

A protein or a member of a complex that interacts specifically and non-covalently with a DNA-bound DNA-binding transcription factor to either activate or repress the transcription of specific genes. ****Coregulators often act by altering chromatin structure and modifications**. For example, one class of transcription coregulators modifies chromatin structure through covalent modification of histones. A second ATP-dependent class modifies the conformation of chromatin. A third class modulates interactions of DNA-binding transcription factor with other transcription coregulators**.

**Comment by ValWood** [comment]
OK then it does sound OK then!

**Comment by pgaudet** [comment]
Reviewed with @colinlog 
Colin says that SAP18 belongs to the SIN3 complex, which is clearly a co-repressor complex by its histone deacetylase activity.

**Comment by pgaudet** [comment]
Actually, looking at the sequence alignment, the fungi branch is similar but quite divergent, so I will add an NOT by IRD ("stop propagation")

**Comment by pgaudet** [comment]
<img width="1031" alt="image" src="https://user-images.githubusercontent.com/4782928/211018660-4a59c52d-1882-4cd0-9c0f-f11f5e277a19.png">

**Comment by pgaudet** [comment]
Although it is weird that pombase calls is a histone acetyltransferase complex:
https://www.pombase.org/gene/SPCC126.13c

**Comment by ValWood** [comment]
Yes, I reviewed this above  based on Helens comments, I could not see good evidence that  it was a splicing factor, all seemed to point to HAC complex subunit. So I think you can propagate,. It is definitely true ortholog of human SAP18 https://www.flyrnai.org/cgi-bin/DRSC_orthologs.pl?input_species=4896&output_species=0&additional_filter=None&search_fields=***&search_datasets=***&gene_list=SPCC126.13c

I was confused by the historical association  as a splicosome subunit...
