### ISSUE TITLE
question about new DNA-crosslink repair activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3488]
I wonder if anyone has curated any gene products related to the 
recently identified DNA crosslink repair activity?
basically the cleavage of topoisomerase DNA-protein crosslinks.

It would be nice if we could get the activity annotated and then propagated via PAINT

metazoan
xenopus @malcolmfisher103
human @sylvainpoux @deustp01 
https://pubmed.ncbi.nlm.nih.gov/27871365/

https://pubmed.ncbi.nlm.nih.gov/28811590/
S. cerevisiae @edwong57 

review

https://pubmed.ncbi.nlm.nih.gov/32674013/

Debulking of topoisomerase DNA-protein crosslinks (TOP-DPC) by the proteasome, non-proteasomal and non-proteolytic pathways
Topoisomerases play a pivotal role in ensuring DNA metabolisms during replication, transcription and chromosomal segregation. To manage DNA topology, topoisomerases generate break(s) in the DNA backbone by forming transient enzyme-DNA cleavage complexes (TOPcc) with phosphotyrosyl linkages between DNA ends and topoisomerase catalytic tyrosyl residues. Topoisomerases have been identified as the cellular targets of a variety of anti-cancer drugs (e.g. topotecan, irinotecan, etoposide and doxorubicin, and antibiotics (e.g. ciprofloxacin and levofloxacin). These drugs, as well as other exogenous and endogenous agents, convert the transient TOPcc into persistent TOPcc, which we refer to as topoisomerase DNA-protein crosslinks (TOP-DPC) that challenge genome integrity and lead to cell death if left unrepaired. Proteolysis of the bulky protein component of TOP-DPC (debulking) is a poorly understood repair process employed across eukaryotes. TOP-DPC proteolysis can be achieved either by the ubiquitin-proteasome pathway (UPP) or by non-proteasomal proteases, which are typified by the metalloprotease SPRTN/WSS1. Debulking of TOP-DPC exposes the phosphotyrosyl bonds, hence enables tyrosyl-DNA phosphodiesterases (TDP1 and TDP2) to access and cleave the bonds. In this review, we focus on current knowledge of the protease pathways for debulking TOP-DPC and highlighting recent advances in understanding the mechanisms regulating the proteolytic repair pathways. We also discuss the avenues that are being exploited to target the proteolytic repair pathways for improving the clinical outcome of topoisomerase inhibitors.

(I did not read the review yet but a cursory glance I could not find any appropriate terms to describe this activity)

**Comment by sylvainpoux** [comment]
Hi Val,

it is related to a request term I made several months ago for SPRTN ( GO:0106300 protein-DNA covalent cross-linking repair)
I updated SPRTN and curated many papers, including the paper you mention (PMID:27871365). 

I'm pretty sure that you commented this ticket at that time, because we could not create a FUNCTION as we don't know how the enzyme acts (which reaction it mediates). As consequence only the Process term was created

Please note that PMID:27871365 paper also contains knowledge for wss2 in S-pombe (SPCC1442.07c). But it does not contain any experimental evidence for the cross-linking activity in pombe in this article.

Last but not least, I just updated GO annotation of for WSS1 in S.cerevisiae (YHR134W) for PMID:24998930, because it proves the involvement in GO:0106300 protein-DNA covalent cross-linking repair. You should be able to propagate this annotation via PAINT now when it is available

Thanks

Sylvain

**Comment by ValWood** [comment]
Thanks @sylvainpoux I thought that it seemed familiar!

https://github.com/geneontology/go-ontology/issues/19856

I will just do what was described here.


GO:0106300    protein-DNA covalent cross-linking repair
