### ISSUE TITLE
Human Annotation of NUDT1 to dGTPase and metabolism need to be reviewed

### ISSUE THREAD

**Issue by ukemi** [geneontology/go-annotation#3581]
The manual annotations listed in QuickGO of the human NUDT1 protein to GO:0006203 “dGTP catabolic process” based on experimental evidence, are wrong. The term definition is “The chemical reactions and pathways resulting in the breakdown of dGTP, guanosine triphosphate.” NUDT1, however, is a 7,8-dihydro-8-oxoguanine triphosphatase, with measurable but 17-fold weaker activity on dGTP than on 8-hydroxy-dGTP (kinetic data are not shown for the mouse protein). (The UniProt assignment of MF GTPase activity seems similarly wrong.)

**Comment by deustp01** [comment]
NUDT1 P36639

**Comment by pgaudet** [comment]
Is this Reactome annotation correct ?

 | GO:0034656 | nucleobase-containing small molecule catabolic process | ECO:0000304(TAS) | ECO:0000304 | (TAS) |   | Reactome:R-HSA-2393930
-- | -- | -- | -- | -- | -- | -- | --
ECO:0000304 | (TAS)

I need we need some concept for repair of damaged nucleotide but I cannot find it; do we have a process like that ?

**Comment by pgaudet** [comment]
I also dont know if we want to keep 'DNA protection' and 'DNA repair' - this is at the level of nucleotides, not DNA. 

Thoughts ?

**Comment by deustp01** [comment]
> Is this Reactome annotation correct ?

Good question. We've applied the GO term to a group of reactions in which nucleotide triphosphates containing modified bases are hydrolyzed to yield the monophosphate forms of the same modified bases. That is said to protect the cell from incorporation of the abnormal nucleotides into DNA, so it would make sense for there to be some sort of mechanism in place (not annotated in Reactome) to dispose of these abnormal nucleotide monophosphates so that they cannot be re-converted into triphosphates and thus once again be available for incorporation into DNA.

It will take some digging to figure out whether there are any relevant experimental data (Rhea, for example, has no reactions that use 8-oxo-dGMP as a substrate for further breakdown), so a good interim fix is to change the GO BP term from GO:0034656 "nucleobase-containing small molecule catabolic process" to its parent  GO:0055086 "nucleobase-containing small molecule metabolic process".

**Comment by ukemi** [comment]
@deustp01 just as a sanity check, did you look at the ChEBI hierarchy for these modified nucleotides? If they are children of what we use as nucleobase-containing small molecules and they are the primary input of a process that degrades them or their enzymatic activity is an intermediate in a pathway that degrades them , then this would be ok??????

**Comment by ukemi** [comment]
> That is said to protect the cell from incorporation of the abnormal nucleotides into DNA, so it would make sense for there to be some sort of mechanism in place (not annotated in Reactome) to dispose of these abnormal nucleotide monophosphates so that they cannot be re-converted into triphosphates and thus once again be available for incorporation into DNA.

This is exactly the reason why we had the protection terms in the ontology. They represent processes/functions that were preemptive rather than responsive. But if I recall correctly, folks did not like them.

**Comment by deustp01** [comment]
> did you look at the ChEBI hierarchy for these modified nucleotides

Now I have and it does not look useful. This is the only parentage I could find and it skips directly to a much higher level: 8-oxo-dGMP(2−) (CHEBI:63224) is a organophosphate oxoanion (CHEBI:58945)

**Comment by pgaudet** [comment]
The human annotations have been corrected. I'l close this - please reopen if other actions are needed.
