### ISSUE TITLE
Reactome: BP annotations attached to nuclear pore complex components

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#3626]
@deustp01 or some else at Reactome:

Could you review the propagation of terms to NPC subunits?
A spot check of these human NPC subunits:
Q8TEM1	NUP210
Q9BW27	NUP85
Q9BVL2	NUP58
Q8NFH4	NUP37
shows that they are being associated with several processes that are not directly related to their function:
GO:0016032	viral process	ECO:0000304	TAS	Reactome:R-HSA-162599	
GO:0016925	protein sumoylation	ECO:0000304	TAS	Reactome:R-HSA-4655355	
GO:0019058	viral life cycle	ECO:0000304	TAS	Reactome:R-HSA-9609690	
GO:0060964	regulation of gene silencing by miRNA	ECO:0000304	TAS	Reactome:R-HSA-5578749	
GO:0006110	regulation of glycolytic process	ECO:0000304	TAS	Reactome:R-HSA-170822	
GO:0019083	viral transcription	ECO:0000304	TAS	Reactome:R-HSA-168325	
GO:1900034	regulation of cellular response to heat	ECO:0000304	TAS	Reactome:R-HSA-3371453	
GO:0075733	intracellular transport of virus	ECO:0000304	TAS	Reactome:R-HSA-1176059
(although you could argue the latter, I think that users would wish to see this term only applied to factors that direct that process rather than the pore itself)

Thanks

**Comment by ValWood** [comment]
might be out of date.

**Comment by deustp01** [comment]
> Could you review the propagation of terms to NPC subunits?
> A spot check of these human NPC subunits:
> [lines omitted]
> GO:0016925 protein sumoylation ECO:0000304 TAS Reactome:R-HSA-4655355
> [and other biological processes]

First, I need to get fairly upset about this wildly delayed piece of housekeeping. As far as I can tell, we generated an annotation in 2013 that associated sumoylation with a complex containing RANBP2 and many other proteins including nuclear pore components. In 2021, probably in response to this complaint, we fixed our annotation to point to the RANBP2 component of the complex as the specific entity that enables SUMOylation. And without checking in detail, I believe we made similar fixes to other events tagged on Helen's list to make our annotation appropriately narrow, consistent with most users' expectations, per Helen.

Today, in response to this complaint, I looked in QuickGO for Reactome-generated annotations of the NUPs in Helen's list and for each of them found multiple CC annotations, appropriate because many workers have independently noted the subcellular localizations of nuclear pore components, but ZERO annotations of any BP or MF term for any of the NUPs Helen listed.

So indeed, as Val said, the complaint not only is out of date but is clearly documented to be out of date in a resource that is available to the people generating the complaints. Wouldn't it make better use of our time, when reviving ancient tickets, to do some background checking first? I mean, can't a script do this better than I can? @pgaudet @thomaspd @cmungall ?!

**Comment by ValWood** [comment]
I think the main problem is that it isn't specifically anybody's task to review the annotation tracker. The tickets come in from many groups or users and need to be assigned to many  different groups groups for actioning. Only the tickets that GO needs to deal with regularly are really regularly  monitored. 

I decided to review the tracker in my 'free' time the past couple of evenings to close some of the legacy issues.  Note that this task isn't part of my formal GO work. I'm only trying to be a good citizen. There are many things I would rather be doing in the evening so if I think somebody else is a more appropriate person to do the follow-up I will assign to them to check or just close (sorry!).

I don't see an obvious way how the follow-up could be automated. Of the 100+ tickets closed in the past couple of days,  most are one-offs and nearly all have required unique solutions.

What we should do:

- Make sure that all tickets are assigned to be actioned in a timely manner (or close them).
- Encourage people to action/close the tickets assigned to them.
- Review regularly to send reminders and close the answered tickets.

Hopefully, once all the legacy tickets are closed we won't be in this situation again. I guess we could just ignore the old tickets but that doesn't feel appropriate, and most appear to result in useful improvements to annotation.

Anyway, I'll close this one. If there are issues about how to manage this task more generally they can be escalated via the manager's call.

**Comment by hattrill** [comment]
@ValWood thank you for checking these old tickets. It does need to be done and you are a good citizen.
