### ISSUE TITLE
PTN002521528 / PTHR24418 NOT issue

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#3701]
Hi @huaiyumi @mugity @dustine32 

This has been reported in https://github.com/geneontology/go-annotation/issues/3304#issuecomment-721084948

In PTN002521528, FBgn0046685  
- has NOT 'protein kinase activity' IKR
-  but also getting 'non-membrane spanning protein tyrosine kinase activity' IBA

I think the non-PAINT IKR is being ignored? We had requested that this gets fixed; has this happened ? 

@huaiyumi this may be a good discussion topic for the next PAINT call. 

Thanks, Pascale

**Comment by dustine32** [comment]
@pgaudet Right now the qualifier checking is same-term only:
https://github.com/pantherdb/fullgo_paint_update/blob/ba3498c34aa49f79de62c92e83743c032c73b42e/scripts/createGAF.pl#L528
BTW Original ticket for the check: https://github.com/pantherdb/fullgo_paint_update/issues/39

From the perspective of the 'non-membrane spanning protein tyrosine kinase activity' IBA, only all experimental annotations to its same term and same gene are checked. Since there are none of these to compare, there can be no qualifier disagreement, so we think the IBA is good. But we can talk about expanding it to also check experimental annotations to all ancestor terms, which would include 'protein kinase activity'.

The other issue is we don't consider IKR to be "experimental" in this check, so the FlyBase IKR wouldn't be checked even if we did expand to ancestor terms:
https://github.com/pantherdb/fullgo_paint_update/blob/ba3498c34aa49f79de62c92e83743c032c73b42e/scripts/createGAF.pl#L266

Perhaps for the purposes of comparing qualifiers here, we should expand this list of evidence codes to include IKR? Good topic for the PAINT call!

**Comment by sjm41** [comment]
FYI @hattrill

**Comment by mugitty** [comment]
![image](https://user-images.githubusercontent.com/6527204/116134937-52815180-a685-11eb-9690-97e0c58f0e68.png)

The PAINT software supports experimental IKR at leaf node.  Furthermore, protein tyrosine kinase activity (GO:0004713) and non-membrane spanning protein tyrosine kinase activity (GO:0004715) is not propagated to node FBgn0046685

**Comment by dustine32** [comment]
Thanks @mugitty! Another good reason for me to finally finish the XML-to-GAF IBA formatter so that I can use the IBAs directly output from the PAINT tool.

**Comment by hattrill** [comment]
Hi @dustine32 @mugitty could you explain what is going on? Has a fix been made to the PAINT tool or are you dicussing a pipeline issue here?

**Comment by dustine32** [comment]
@hattrill Right, I was referring to a pipeline change to make the fix. Specifically, looks like the logic in the PAINT tool (as @mugitty pointed out) is blocking the IBA like we want, and I'm currently working to derive the PAINT IBA GAF files directly from this logic. (short answer: not fixed yet, but will be fixed soon!)

**Comment by hattrill** [comment]
Thanks @dustine32 I am unconfused now! :-)

**Comment by dustine32** [comment]
@pgaudet @hattrill While using this ticket's NOT conflict example for developing  https://github.com/pantherdb/fullgo_paint_update/issues/52, I noticed this change in AmiGO:
![image](https://user-images.githubusercontent.com/2678599/128093411-06f5802f-86cc-4565-9be9-bb380381696b.png)
So, the positive IBA to 'non-membrane spanning protein tyrosine kinase activity' seen before has now turned into a `NOT` IBA due to an IKR added in the PAINT tool.

Just tagging @thomaspd because we were just discussing this strategy and I think he'll approve of it!

**Comment by sjm41** [comment]
Thanks @dustine32 - that looks good to me. Does the PAINT 'NOT' only appear in the branch containing fly Wsck? I guess it should do as other members of pthr24418 are bona fide tyrosine kinases.

**Comment by pgaudet** [comment]
@sjm41 is right - this only applies to a single sequence, I dont think the NOT IBA should be there, the PAINT curator would not have made an annotation here. The presence of a NOT should prevent the positive IBA from being made.

**Comment by dustine32** [comment]
Thanks for the quick response!

@sjm41 This IKR `NOT` is on the Arthropoda clade (PTN004704423).

@pgaudet Since the PAINT `NOT` is an IKR, it will create the `NOT` IBA. If this IKR (looks like @marcfeuermann created it on 2021-05-05) is changed in PAINT to an IRD it should totally block all IBAs (positive or `NOT`) for this term to this sequence.

**Comment by pgaudet** [comment]
OK I see - attaching a new screenshot because this is different from what we used to have https://github.com/geneontology/go-annotation/issues/3701#issuecomment-827069893

<img width="696" alt="image" src="https://user-images.githubusercontent.com/4782928/128481817-2ff95aa0-6ef4-453c-9d14-228dd7533c28.png">

**Comment by pgaudet** [comment]
I think this is now resolved?

**Comment by sjm41** [comment]
Yes, I think can be closed.
