### ISSUE TITLE
PMID:15496587 SAP30B (reviewing unknowns)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3712]
PMID:15496587 is used to annotate SAP30BP
to
positive regulation of cell death | ECO:0000314   IDA

I believe this annotation should be removed- and also the associated KW to " apoptotic process"

I'll raise a Protein2GO dispute for the annotation

( I am checking our priority unknowns list which includes the yeast ortholog of this gene)

**Comment by ValWood** [comment]
Expired EBI account so tagging @pgarmiri 

(this paper contains only a localization and interactions, no process information)

**Comment by pgarmiri** [comment]
Hi @ValWood ,

I had a look at the paper and it seems that there is a flow-cytometry experiment in fibroblasts

![image](https://user-images.githubusercontent.com/22025005/114404041-3ec1ef80-9b9d-11eb-94a7-18093e800c83.png)

Obviously, this is not conclusive, so perhaps a qualifier like 'acts_upstream_of_or_within_positive_effect' to the parent term  GO:0010941 'regulation of cell death', would be more suitable?

Penelope

**Comment by ValWood** [comment]
I don't think this experiment should be used for GO annotation.
If this is a quantitative analysis  they  express (most likely inappropriately), and this causes cell death. This is more of a phenotype from inappropriate expression- many  endogenous proteins are toxic is inappropriately expressed. For example a meiotic gene expressed in vegetative cells. I don't think this is enough  information make a GO annotation (especially to cell death where it is tricky to determine an evolved role. I think you really need to be sure that it is programmed cell death to make an annotation.  

@pgaudet do you agree?

This is conserved from  yeast so a role in cell death is unlikely.

**Comment by pgaudet** [comment]
I agree with @ValWood that the connection between the observation and the gene can not really be assessed based on this experiment. Without any more data I would probably not annotate either. 

I think some GO terms that are frequent readouts can be quite misleading (cell death, cell proliferation, DNA replication,,, many others), and we should be very careful when annotating.  

Looking at other sources of information (since the paper mentioned, PMID:15496587, is from 2004), I found 2 other papers with some functional characterization: PMID:21221920 (human) and PMID:31743857 (plants). Both point to some role as a transcription co-factor (same as the original paper). I think an annotation to regulation of transcription would be appropriate. The other 2 papers mention some responses to stress, that's not very informative but could be correct. 

WRT cell death in PMID:15496587, the authors describe Firgure 4 with the following sentence "However,  these data  imply   that   the  function of HTRP,  might involve the repression  of some  gene  related   to  cell  survival." -> ie, they dont state that there is a role in cell death. 

They call the gene a repressor because it interacts with a repressor, but I dont see evidence one way or the other. 

Thanks, 
Pascale

**Comment by ValWood** [comment]
direct annotations to 
http://amigo.geneontology.org/amigo/term/GO:0008219
http://amigo.geneontology.org/amigo/term/GO:0060548

should be reviewed at some point,. The mainly appear to be pro-survival......there are not so many...


SRSF6 | Serine/arginine-rich splicing factor 6
DUS2 | tRNA-dihydrouridine(20) synthase [NAD(P)+]-like
escrt-iii_human | ESCRT-III complex
RAD18 | E3 ubiquitin-protein ligase RAD18

Maybe the  terms need better comments about not annotating prosurvival, or blocking altogether unless the mechanism can be specified (apoptosis, autophagy)

**Comment by pgarmiri** [comment]
Thank you @pgaudet and @ValWood  for looking at this. Yes, the author's description of the fig 4  results is very inconclusive. I wouldn't add a direct annotation based in this either. I only very tentative considered keeping a high up annotation with an upstream qualifier, as it had no annotations at all. On the other hand, it might be better to have zero annotations than having a misleading one.

In any case, I have deleted the annotation and I'll check the papers you mentioned to get some BP annotations that are more appropriate. In the human paper, they say that it is induced by HSV-1 infection, so a response to virus annotation could be added. I will try to annotate  to regulation of transcription.

Penelope

**Comment by ValWood** [comment]
I think it is better to keep things which are poorly characterized as unknown than try to force an annotation. Groups are now a focussing on characterizing  the unknowns and genes with assigned processes  might get overlooked.  I am aware that grant reviewers for some of these projects are questioning why some proteins are unknowns list, but seem to be characterized in human. When I look the annotations are usually weak or misleading. In my opinion no annotation is better than phenotypes and readouts.

**Comment by pgarmiri** [comment]
@ValWood 
Btw maybe the UniProt entry should be updated accordingly (https://www.uniprot.org/uniprot/Q9UHR5) as it states that 'Induces cell death...' and have the KW 'apoptotic process' as well.

Please, report it here: https://www.uniprot.org/update

**Comment by ValWood** [comment]
done!
thanks.
