### ISSUE TITLE
Review annotations to GO:0000187 activation of MAPK activity and related

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#3735]
Dear all, 

The proposal has been made to obsolete
* GO:0000186 | activation of MAPKK activity
* GO:0000187 | activation   of MAPK activity
* GO:0007256 | activation of JNKK activity
* GO:0007257 | activation of JUN kinase activity

Obsoletion ticket: https://github.com/geneontology/go-ontology/issues/21307

since those represent molecular functions. 
 
There are about 300 EXP annotations: 

Contributor (Assigned by)
--
AgBase | 5
ARUK-UCL | 9 done
BHF-UCL | 25 done
CACAO | 2
CAFA | 2
CGD | 1
DFLAT | 3
dictyBase | 7
FlyBase | 9
HGNC-UCL | 4 done
MGI | 69
ParkinsonsUK-UCL | 6 done
RGD | 29
SGD | 10
UniProt | 94
WB | 13
ZFIN | 3

Annotations are here: https://docs.google.com/spreadsheets/d/1RwdgK5ZjgFCqO03Os6LZFcMtKmu3Xz2dxqdFkM66Vx4/edit#gid=0

Since this is a lot to review we will leave 1 month until the obsoletion. Please let me know if you need more time. 

Thanks, Pascale

**Comment by pgaudet** [comment]
There are also 8 InterPro mappings:

GO:0000186 | InterPro:IPR027257
GO:0000186 | InterPro:IPR036722
GO:0000186 | InterPro:IPR009106
GO:0000186 | InterPro:IPR017419
GO:0000187 | InterPro:IPR026830
GO:0000187 | InterPro:IPR029591
GO:0000186 | InterPro:IPR032938


@sarach06 @EBI-Hsinyu

**Comment by pgaudet** [comment]
Suggestions for replacement 
* GO:0043410 positive regulation of MAPK cascade
* GO:0043408 regulation of MAPK cascade 
* or some MF such as 
* * GO:0004708 'MAP kinase kinase activity'
* * GO:0008349 'MAP kinase kinase kinase kinase activity'
* * or another kinase. 
* 
Thanks, Pascale

**Comment by sarach06** [comment]
Hi Pascale,
Thank you very much. I have checked the entries and changed the terms. The changes will be visible in the next InterPro release (86.0).
Best,
Sara

**Comment by pgaudet** [comment]
Thank you Sara!

**Comment by RLovering** [comment]
Hi Pascale

I am not convinced that  GO:0031098 stress-activated protein kinase signaling cascade should be a child of cellular response to stress. The ontology is reflecting the name rather than the biology.
PMID: 27511108 describes the role of the JNK cascade in axon growth, but I think it is inappropriate to state that axon growth is always in response to stress, although they do also discuss neuron wounding. eg in the abstract they state: Neuronal maturation or activity deprivation activates the LZK-MKK4-JNK pathway.

Ruth

**Comment by vanaukenk** [comment]
@pgaudet 

Just want to clarify the appropriate re-annotation strategy here.

For one of the C. elegans genes, jkk-1, annotated to 'activation of JUN kinase activity', we have an existing MF annotation of 'JUN kinase kinase activity'.

Based on the discussions from the February 2021 ontology jamboree in https://github.com/geneontology/go-ontology/issues/20862 I would NOT create a new MF annotation of 'protein serine/threonine kinase activator activity' for jkk-1 since it is (just) an upstream kinase in a kinase cascade.

So our standard annotations for jkk-1 wrt the kinase cascade should be:

BP: JNK cascade (GO:0007254)
MF: JUN kinase kinase (GO:0008545)

and that's it (save extensions or causal flow otherwise captured in a GO-CAM).

Is that consistent with what you're thinking here?

Thanks.

**Comment by pgaudet** [comment]
Hi everyone, This is a reminder that these terms are scheduled to be obsoleted on Monday. Please let me know if you need more time to review. 

Thanks, Pascale

**Comment by hdrabkin** [comment]
MGI will need more time; we divided them up but two curators on vacation until Monday I belive.

**Comment by gthayman** [comment]
RGD will need more time.

**Comment by gthayman** [comment]
RGD done.

**Comment by vanaukenk** [comment]
I will need more time to finish up the WB annotation review.

**Comment by pfey03** [comment]
I Also had a lot on my plate and need some more time

**Comment by pgaudet** [comment]
Let's say June 1st, hope that works for everybody.

**Comment by suzialeksander** [comment]
sgd done

**Comment by hdrabkin** [comment]
mgi done

**Comment by pfey03** [comment]
dictyBase also done

**Comment by pgarmiri** [comment]
Hello, 
EBI-UniProt, CAFA and DFLAT annotations have been reviewed. There are 24 annotations from SIB that I have mark them in the spreadsheet with lilac tag at end of each row. (for the attention of @sylvainpoux )
Thanks,
Penelope

**Comment by vanaukenk** [comment]
WB is done.

**Comment by pgaudet** [comment]
Also fixed Panther families 
- [x] dual specificity mitogen-activated protein kinase kinase 5-related PTHR48013
- [x] serine/threonine-protein kinase tnni3k-related  PTHR44329
- [ ] jnk/sapk-associated protein PTHR13886
- [ ] jprokineticin PTHR18821
- [ ] jretinal cone rhodopsin-sensitive cgmp 3',5'-cyclic phosphodiesterase gamma-subunit-related PTHR12122
- [ ] jmap-kinase activating death domain protein madd /denn/aex-3 c.elegans PTHR13008
- [ ] jtransforming growth factor alpha PTHR10740
- [ ] jarginine vasopressin-induced protein 1 PTHR14350
- [ ] jshc transforming protein PTHR10337
- [ ] jc-x-c motif chemokine 17 PTHR37351
- [ ] jmucin-20 PTHR37358
- [ ] jinsulin/insulin growth factor PTHR11454

**Comment by pgaudet** [comment]
Terms have been obsoleted. Annotations to obsolete terms show up in error reports http://snapshot.geneontology.org/reports/gorule-report.html

**Comment by sabrinatoro** [comment]
ZFIN done (after all annotations were migrated to Noctua)

**Comment by pgaudet** [comment]
Thank you !
