### ISSUE TITLE
Review annotations to regulation of histone exchange and children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#3834]
https://docs.google.com/spreadsheets/d/1D2xpuXBuMgPizUIixfJrMFiuASDdGmAgwM4S-jI2Rmw/edit#gid=0

**Comment by ValWood** [comment]
Happy to update. I think most of these are histone chaperones (nucleosome loaders and/or unloaders).

because the term:
The replacement, within chromatin, of resident histones or histone subunits with alternative, sometimes variant, histones or subunits.

Was. a good place holder for the  missing MF terms for histone chaperones (related synonym)

Are the necessary MF terms in place for this?

This ticket is closed:
https://github.com/geneontology/go-ontology/issues/21436
but I don't immediately see which terms were added.

**Comment by mah11** [comment]
probably includes the ones added for (or mentioned in) https://github.com/geneontology/go-ontology/issues/21733

**Comment by ValWood** [comment]
By moving these annotations up to 
chromatin remodelling:
Dynamic structural changes to eukaryotic chromatin occurring throughout the cell division cycle. These changes range from the local changes necessary for transcriptional regulation to global changes necessary for chromosome segregation. PMID:12697820

we no longer capture the fact that this aspect of remodelling refers to the pathways which replace nucleosomes/histones.  Is the existing definition of chromatin remodelling too broad?

**Comment by pgaudet** [comment]
>  Is the existing definition of chromatin remodelling too broad?


Yes - this is why we have created 'GO:0140673 chromatin maintenance during transcriptional elongation' , and other related terms will be created as we review existing annotations. Suggestions are welcome.

**Comment by ValWood** [comment]
But not all of histone-exchanges are 
GO:0140673 chromatin maintenance during transcriptional elongation'

either? this term would be too narrow?

**Comment by ValWood** [comment]
Also, I would not read this term and think it was the correct term for the current annotations to histone exchange? 

chromatin maintenance during transcriptional elongation
The maintenance of chromatin structure following passage of RNA polymerase II during transcription elongation, that prevents trans-histone exchange in transcribed regions.

The definition says it prevents  trans-histone exchange so is it defined by what it isn't doing rather than what it is doing? Should it be "the maintenance of chromatin structure by _blah_ (whatever it is doing to histones)

**Comment by ValWood** [comment]
OK, I think I understand.
Where is the ticket for
GO:0140673?
I can't find it. I will transfer the relevant parts there.

**Comment by pgaudet** [comment]
Out of date
