### ISSUE TITLE
Taxon constraints not observed by PAINT

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3874]
Centrosome has "never in Fungi"

(this might be on the wrong tracker)

<img width="1284" alt="Screenshot 2021-08-19 at 10 43 49" src="https://user-images.githubusercontent.com/7359272/130224003-de763744-da6c-441a-99b1-8c1b765fbbc9.png">

**Comment by pgaudet** [comment]
I know some of these are not fixed yet - but I thought they were getting filtered by the pipeline 

@dustine32 isn't it the case?

**Comment by dustine32** [comment]
@pgaudet @ValWood Just checked and it looks like this was fixed by https://github.com/geneontology/go-site/issues/1727. There's this reported error in [2021-09-01 release](http://release.geneontology.org/2021-09-01/reports/paint_pombase-report.html):
```
ERROR - Violates GO Rule: GORULE:0000013: Taxon-appropriate annotation check -- PomBase SPAC1782.09c clp1 is_active_in GO:0005813 PMID:21873635 IBA PANTHER:PTN000596949|ZFIN:ZDB-GENE-040426-1214|UniProtKB:Q9UNH5|WB:WBGene00000383 C Tyrosine-protein phosphatase CDC14 homolog UniProtKB:Q9P7H1|PTN000597047 protein taxon:284812 20170228 GO_Central
```
This was likely due to the `is_active_in` relation not being handled by the older gaferencer version we had running at the time.

**Comment by pgaudet** [comment]
Great, thanks @dustine32
