### ISSUE TITLE
PTN001236278 positive regulation of transcription by RNA polymerase II - PTHR47636

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3932]
* **PTHR ID & PTN node:**

GO:0045944 | positive regulation of transcription by RNA polymerase II | IBA with PTN001236278 , S000004680

* **Sequences with problematic annotation (ID + gene/protein name):**
This is a member of Rpd3S/Clr6-CII complex (GO:0032221)
This is a histone deacetylase complex. 
All other members in pombe are annotated to repression.
@colinlog does this seem correct? It's a bit confusing...

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by ValWood** [comment]
We should probably look at these on a call.
I'm picking up PAINT inferences for
pombe cph1,cph2  (S.c SCO1 ; Human PHF12)
(here there is one human annotation, looked incorrect to me)
https://www.uniprot.org/citations/19041327 should this be +ve reg?


and
pombe clr6 (S.c RPD3; Human HDAC1 & 2)
Quite a lot of annotations. Some of the human ones I spot-checked looked incorrect and the 
S. cerevisiae ones are really old.

Maybe @colinlog can advise on the current consensus here?
Could this be 'interference'?

**Comment by pgaudet** [comment]
Hi @ValWood 
This is a small family with no human orthologs. The annotations were propagated from cerevisiae RCO1 https://www.yeastgenome.org/locus/S000004680
Positive regulation of transcription is citing this paper: PMC3866184

Anyway, with @colinlog we have agreed to use 'regulation of transcription' rather than positive/negative, at least for dbTFs. I dont know that this systematically applies to coTFs, maybe their function (depending on the chromatin modification they catalyze) is more easily classifiable into positive or negative regulation, but based on the paper cited (PMC3866184), I was not able to tell, they used KO's, and I am not sure of the mechanism, so I moved the annotation to 'chromatin remodeling' and 'regulation of transcription'. 

@srengel Do you want to have a look at that paper? 

Thanks, Pascale

**Comment by ValWood** [comment]
Just to note, this is positive regulation of meiosis specific genes.
This gene negatively regulates antisense transcripts, and a lot of meiosis genes are negatively regulated by antisense transcripts so although this annotation seems odd for a repressor, it looks odd.
Would we therefore end up with every repressor of antisense RNAs annotated to both  +ve and -ve regulation of transcription? I guess so?

**Comment by pgaudet** [comment]
Hi @ValWood 
Is the "repressor of antisense RNAs" a random example, or it is relevant to this ticket? 
Generally, an inhibitor of an inhibitor is a positive regulator, yes @ukemi @vanaukenk 

Thanks, Pascale
