### ISSUE TITLE
Incorrect UniProt Uni-rule mapping: 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3943]
* **UniProt KeyWord (ID and label):**

LONP2 | Lon protease homolog 2, peroxisomal |   | protein quality control for misfolded or incompletely synthesized proteins |   | UniProt | Homo sapiens | IEA | UniRule:UR000106901 | atp dependent lon protease family member pthr10046 | protein |   | GO_REF:0000104 | 20210612

I'm not sure this UNiRule mapping is correct as this particular protease seems to be I'm removal of peroxisomal signal sequences

**Comment by Antonialock** [comment]
@PedroRaposo

**Comment by PedroRaposo** [comment]
Thank you for addressing this, @ValWood. I am not sure what seems to be off about this rule. The UniRule is consistent with its InterPro signature and with the Swiss-Prot proteins it bases on for its annotation. Maybe I did not understand what the problem is - could I ask for a clarification on where the problem lies?

**Comment by ValWood** [comment]
it's OK- it appears to be both degradation and processing according to 
https://pubmed.ncbi.nlm.nih.gov/22002062/
