### ISSUE TITLE
Review annotations to GO:1903231 mRNA binding involved in posttranscriptional gene silencing

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#3976]
Dear all, 

The proposal has been made to obsolete GO:1903231 'mRNA binding involved in posttranscriptional gene silencing, see https://github.com/geneontology/go-ontology/issues/18851

Annotations are here: 

https://docs.google.com/spreadsheets/d/1BHdXJPKnkvGtY5ARUxDAZMgKkScMC2gusRTlsnQGWS8/edit#gid=0

Number of annotations by group: 
* 1303	UCL (BHF, ARUK and ParkinsonsUK)
*  166	FlyBase
*  26	ZFIN
*  7	MGI
*  6	DIBU
*  1	EcoCyc
*  1	TAIR

Thanks, Pascale

**Comment by RLovering** [comment]
Hi All
sorry I have changed my mind and I am now suggesting new MF terms are needed  NTR: Function terms for RNAs #22441 

The point I am making is that we are removing GO:1903231 mRNA binding involved in posttranscriptional gene silencing because the term name has a process in it. And yet many of the protein MF tems have a process parent (either included or implied just not listed as a parent). I am suggesting that MF terms need to be created for ncRNAs and this issue needs to be addressed before the removal of the annotations associated with the term GO:1903231 mRNA binding involved in posttranscriptional gene silencing.

Please do not edit the annotations associated with GO:1903231 mRNA binding involved in posttranscriptional gene silencing until a new MF replacement is agreed

Thanks
Ruth

**Comment by hdrabkin** [comment]
Can either of these two be used instead? These are both posttranscriptional processes.
GO:0035278
GO:0035279

**Comment by pgaudet** [comment]
We have decided to rename and move the term instead - see https://github.com/geneontology/go-ontology/issues/22441


Annotations do not need to be reviewed.
