### ISSUE TITLE
PTN000564171  transcription coregulator activity ?

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4000]
* **PTHR ID & PTN node:**

GO:0003712 | transcription coregulator activity | IBA with PTN000564171 , O75151

* **Sequences with problematic annotation (ID + gene/protein name):**

fission yeast epe1 https://www.pombase.org/gene/SPCC622.16c

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

Not sure, but epe1 does not seem to fit this definition, because it does not act by "via binding to a DNA-bound DNA-binding transcription factor"

tagging @colinlog  @pgaudet

**Comment by pgaudet** [comment]
I'll check with @colinlog

**Comment by colinlog** [comment]
I have the following comment on my earlier comment: 

We can be strict and say that the MF coTF is reserved only for the protein complexes that have been shown to be directly physically recruited by at least one DNA bound dbTF in at least one organism.  In the case where there is no evidence that epe1 and its orthologs are recruited by a dbTF then it could be annotated as I indicate below: as based on PMID: 30573453 and also 24013502.

S.pombe epe1 is part of the BP GO:0045815 transcription initiation-coupled chromatin remodeling (rather than transcription regulation) and has a MF GO:0140110 transcription regulator activity [ A molecular function that controls the rate, timing and/or magnitude of gene transcription. The function of transcriptional regulators is to modulate gene expression at the transcription step so that they are expressed in the right cell at the right time and in the right amount throughout the life of the cell and the organism. Genes are transcriptional units, and include bacterial operons.   ***Restriction*** This term should not be used for direct annotation.]  

Because 'Transcription regulator activity GO:0140110' is a do-not-annotate grouping term, the correct term for epe1 working with the SAGA H3 acetylase complex to promote transcription in heterochromatin for siRNA production would be its child term GO:0140537 transcription regulator activator activity

Molecular Function
Definition ([GO:0140537 GONUTS page](http://gowiki.tamu.edu/wiki/index.php/Category:GO:0140537))

A molecular function regulator that increases the activity of a transcription regulator via direct binding and/or post-translational modification. PMID:9597751

Comments

Usage guidance: transcription regulator activators bind to a transcription regulator to allow it to reach the chromatin or to contact other transcriptional regulators. This activity does not occur at the promoter. For activities that do occur at the promoter, consider GO:0001216 ; DNA-binding transcription activator activity or GO:0003713; transcription co-activator activity; those activities respectively bind DNA themselves or positively regulate a transcription regulator when it is located at the chromatin.

However, the targeting aspect of epe1 which in S.pombe appears to work only at specific loci is not captured by this annotation, while a coTF annotation implies that there is a gene/locus-specific mechanism at play, which is either based on (i) a dbTF, (ii) reading the local histone code or (iii) indirect recruitment via a physical interaction with well known coTF. Hence I would use reason 3 and the SGA-epe1 interaction to annotate it as coTF because it appears to be a 'co-coTF'.

**Comment by ValWood** [comment]
but then we have 2 annotations


histone H3K36me/H3K36me2 demethylase activity
and "transcription coregulator activity"  to describe one activity?
I find the parallel annotations to "transcription coregulator activity"  a bit confusing.

also te definition says
A transcription regulator activity that modulates the transcription of specific gene sets via binding to a DNA-bound DNA-binding transcription factor, either on its own or as part of a complex.

and SAGA isn't a "DNA binding TF"  then epe1 doesn't fit this definition. So is the definition the problem?

**Comment by colinlog** [comment]
SAGA is a coTF for many dbTFs, that is clear. Other/alternative molecular signals that recruit SAGA are acetylated histones and  epe1. As epe1 accumulates at heterochromatin boundaries via its degradation in the inner parts of heterochromatin domains - but not at their 'edges',  it is positioned to recruit SAGA to these boundaries. The same is true for recruitment of bdf2 by epe1. To me, as epe1 is not a dbTF, but rather gets localized through other processes, its mechanism of transcriptional activation is that of a coTF that is targeted by dbTFs, histone-bourne modifications and/or by coTFs. In this case it is a complicated targeting mechanism that involves degradation in the H3K9me2 heterochromatin domain but not at its edges - in some kind of 'focussing' mechanism based on localized degradation. Still, epe1 fits the bill for a coTF in the sense that it gets to the right chromosomal loci due to external influences (that are not direct DNA binding'and then does it job of recruiting SAGA there, a complex that is nvolved in the BP: BP GO:0045815 transcription initiation-coupled chromatin remodeling.

As for the double annotation, yes, it is a paralof of enzymes with demonstrated H3K36demethylation activity. However the papers say that catalytic mutations do not change its coTF activity. In fact it may be that this protein is not a even a demethylase. Hence, the coTF activity that is involved in 'transcription at heterochromatin boundaries' would be the correct annotation an dH3K36 demethylation may not even be true.

**Comment by ValWood** [comment]
OK, closing this one. I'm still not totally sure what to use transcription coregulator for, but hopefully I will get it soon!
