### ISSUE TITLE
ARBA:ARBA00033559 DNA clamp unloading

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4127]
These are annotations that have been recently removed because they represent Molecular functions in the biological process ontology

PomBase	SPAC1687.03c	rfc4	involved_in	GO:0090618	GO_REF:0000117	IEA	ARBA:ARBA00033559	P	DNA replication factor C complex subunit Rfc4		protein	taxon:4896	20220314	UniProt		
PomBase	SPAC23D3.02	rfc2	involved_in	GO:0090618	GO_REF:0000117	IEA	ARBA:ARBA00033559	P	DNA replication factor C complex subunit Rfc2		protein	taxon:4896	20220314	UniProt		
PomBase	SPAC27E2.10c	rfc3	involved_in	GO:0090618	GO_REF:0000117	IEA	ARBA:ARBA00033559	P	DNA replication factor C complex subunit Rfc3	SPAPJ698.01c	protein	taxon:4896	20220314	UniProt

**Comment by ValWood** [comment]
This might be out of date.

**Comment by PedroRaposo** [comment]
Hello,
All S. pombe entries now have the correct Molecular GO term GO:0061860 (DNA clamp unloader activity) instead of the Biological GO:0090618 (DNA clamp unloading). Probably because the former GO term, coming from PomBase, is more specific (see image).
![image](https://github.com/geneontology/go-annotation/assets/16338197/c636d6f1-8222-468a-8122-f2d6f2f9aea9)
But there are still 6 Swiss-Prot entries which only have the more general GO term (https://www.uniprot.org/uniprotkb?query=%28xref%3Ainterpro-IPR003593%29+AND+%28xref%3Ainterpro-IPR013748%29+AND+%28taxonomy_id%3A4751%29+AND+%28go%3A0090618%29+NOT+%28go%3A0061860%29&facets=reviewed%3Atrue), so the ARBA rule still is available, and is unable to correct the taxonomic condition Fungi.
We do not want to exclude Saccharomyces from the ARBA propagation, as we have other proteins (e.g. P40339) with the GO:0090618 added manually from the Complex Portal (with papers backing this up), in S. cerevisiae. In case you are wondering why can't we remove the taxonomy of S. pombe without interfering with S. cerevisiae, is because the lowest taxonomic level we can use in UniProt rules (ARBA and UniRule) is the genus.
So, what I can do is to ask the team if we can exclude the proteins from S. pombe from being touched by this ARBA rule (these proteins are: https://www.uniprot.org/uniprotkb?query=%28xref%3Ainterpro-IPR003593%29+AND+%28xref%3Ainterpro-IPR013748%29+AND+%28go%3A0061860%29).

**Comment by ValWood** [comment]
You can ignore this one. The GO term will be obsoleted soon to be replaced with a molecular function term.
I think we are only waiting for the obsoletions to proceed.
https://github.com/geneontology/go-ontology/issues/23461

@pgaudet I will proceed with this ticket.
