### ISSUE TITLE
PTN000847539 smoothened signaling pathway

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#4196]
* **PROTEIN PATCHED (PTHR46022) & PTN000847539 node:**

smoothened signaling pathway GO:0007224

Patch represses smoothened signaling. Binding to hh releases this inhibition. It should therefore be annotated with negative regulation of smoothened signaling pathway GO:0045879.

@ukemi do you want to review the mouse annotations for Ptch1 and @doughowe for Danio ptch1 to make them consistent as you have a mixture.

**Comment by doughowe** [comment]
Hi @hattrill, looking at zebrafish ptch1 I only see annotation for "negative regulation of smoothened signaling pathway".  What are the inconsistent annotations?  Happy to take a further look.

**Comment by hattrill** [comment]
Hi @doughowe in QuickGO I see it for PMID:19305393 and this is what I see for http://www.pantree.org/node/annotationNode.jsp?id=PTN000847539
<img width="839" alt="Screenshot 2022-06-09 at 10 01 28" src="https://user-images.githubusercontent.com/11865746/172808778-ba3e96ae-d66e-4e6e-a729-08333379a696.png">

**Comment by doughowe** [comment]
I located the annotation to smoothened signaling pathway from PMID:19305393 on Danio rerio ptch2 gene.  I reviewed that and determined it could be updated to negative regulation of smoothened signaling pathway.  I've made that edit in Noctua.  Not sure how long that will take to perk through the pipes to get back to ZFIN and over to other systems.  

I don't see a GO annotation on  PMID:19305393  on Danio ptch1, so can't update that.  The ptch1 gene does have an annotation to "smoothened signaling pathway" using IBA evidence.  We get that through PAINT annotation, so that would have to be updated by PAINT curators.  I can't update that one.

**Comment by hattrill** [comment]
Perhaps it just persists. in the GOA DB?
 @alexsign will UniProtKB:Q98864 'smoothened signaling pathway' GO:00072 IMP with ZFIN:ZDB-MRPHLNO-050308-1 be updated via the GOC pipeline?

**Comment by marcfeuermann** [comment]
This has been corrected at the PAINT level. Please close the ticket when you'll consider it as solved.

**Comment by hattrill** [comment]
Hi @ukemi  can you just check your annotation to Ptch1 so I can close this.

**Comment by ukemi** [comment]
I think I got them all.
