### ISSUE TITLE
function for "unknown"  iron ion homeostasis (Hemerythrin )

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4311]
* **ARBA rule (ID and label):**

I'd love to know the  source of 
GO:0055072 | iron ion homeostasis | IEA with ARBA00033500 | GO_REF:0000117 | 21
for Hemerythrin

It does seem to bind iron,
https://www.ebi.ac.uk/interpro/entry/pfam/PF01814/
However Hemerythrin is classically described as Oxygen-binding through two attached Fe2+ ions. 

But I can't find any  good source of a process annotation, or any indication it is involved in "iron homeostasis" (note that binding iron is not sufficient)

* **Sequences with problematic annotation (ID + gene/protein name):**
https://www.pombase.org/gene/SPAC869.06c

**Comment by ValWood** [comment]
@Antonialock

**Comment by ValWood** [comment]
@dexink  I don't know if  De-Crezy lab have ever looked at this. It looks interesting from a domain organization and species distribution perspective.

**Comment by Antonialock** [comment]
as far as I understand ARBA annotations are based on annotation of swiss-prot entries - the N.crassa entry is in trembl so it can't be used as a basis for ARBA annotations.

If I would make an uneducated guess it is because pombe hry1 and N.crassa Q7RWD2 both have interpro domain IPR012312

this domain is also found in human protein Q9UKA1 · FBXL5_HUMAN which is annotated to iron ion homeostasis

**Comment by ValWood** [comment]
Yes,that one looks OK.
