### ISSUE TITLE
EC to GO need removing

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4327]
https://www.pombase.org/gene/SPAP27G11.07c
GO:0004674 | protein serine/threonine kinase activity | IEA with 2.7.11.1
is an ATPase but not a protein kinase

**Comment by pgaudet** [comment]
EC:2.7.11.1 needs to be removed from Q9P7N1

**Comment by marcfeuermann** [comment]
This is not an easy case. In _S. cerevisiae_, this protein is considered an atypical serine/threonine kinase, because it lacks the conventional structural elements necessary for the substrate recognition as well as a lysine residue that in all other serine/threonine kinases participates in the catalytic event but seems to have retained kinase activity (PubMed:12023889). However, in the context of the EKC/KEOPS complex, the catalytic subunit KAE1 switches the activity of BUD32 from kinase into ATPase.
Not sure if the residual kinase activity is physiological and I could remove the kinase activity from UniProt entries, but some additional feedback would be welcome. In SGD it is still considered as a kinase. @srengel ?
Thanks a lot.
Marc.

**Comment by srengel** [comment]
the kinase activity is physiological, and required for the full functionality of the Grx4p glutaredoxin.  https://www.yeastgenome.org/reference/S000128386

**Comment by ValWood** [comment]
OK I will add this one back!

**Comment by pgaudet** [comment]
Can this be closed ?

**Comment by ValWood** [comment]
I think so!
