### ISSUE TITLE
Review annotations to GO:0055068 cobalt ion homeostasis

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4398]
Dear all, 

The proposal has been made to obsolete GO:0055068 cobalt ion homeostasis, see https://github.com/geneontology/go-ontology/issues/24658
There is a single TAIR annotation to this term, to AT5G03570 from TAIR:Publication:501734956/PMID:19861554

@lreiser Is this intracellular homeostasis, organism-level homeostasis, or detoxification? 

Thanks, Pascale

**Comment by lreiser** [comment]
From the paper, the gene in question encodes a FPN2, a  Ferroportin iron efflux transporter that also transports cobalt in low Fe conditions.
Mutants accumulate cobalt  in shoots (cobalt moves from root to shoot), some cursory reading suggests cobalt may have physiological role as a micronutrient

FPN1 seems to control metal efflux to vasculature and FPN2, 'normal function' wrt cobalt  is  sequestration into vacuole which makes it unavailable for intercellular transport.

This review
https://nph.onlinelibrary.wiley.com/doi/full/10.1111/nph.14175
Would suggest the proper role is cobalt detoxification since cobalt competes with Fe.

@tberardini ? Sound reasonable?

**Comment by tberardini** [comment]
@lreiser  sounds reasonable

**Comment by lreiser** [comment]
this annotation was fixed.
