### ISSUE TITLE
Review annotations to GO:1903506 regulation of nucleic acid-templated transcription	

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4532]
Dear all, 

The proposal has been made to obsolete GO:1903506 regulation of nucleic acid-templated transcription and positive and negative children 

see https://github.com/geneontology/go-ontology/issues/24383

Experimental annotations that need to be reviewed are here: https://docs.google.com/spreadsheets/d/1CNs_chlYt-o02x1unsuwF5yTxUMdPlt3zDLa-oSAIG8/edit#gid=0

Impacted groups: 
1 EcoCyc
1 TAIR 
11 UniProt (fixed) 

There are no mappings. 

Thanks, 

Pascale

**Comment by amandamackie** [comment]
Hi Pascale, I removed the terms from EcoCyc. 

I couldn't find suitable terms for 'regulation of bacterial-type RNA polymerases'

Amanda

**Comment by pgaudet** [comment]
@amandamackie 

Sorry about that. You can use the parent, GO:0006357 'regulation of transcription by RNA polymerase II'

Thanks, Pascale

**Comment by amandamackie** [comment]
@pgaudet 
OK...but coul the definition of that term be changed to make it clear that it includes bacterial-type RNA polymerase. I saw GO:0006357 but didn't think it was appropriate because it appears to be specific for RNA pol II which is a eukaryote-specific term. 

I can see that there are some molecular function terms specific for bacterial-type RNA polymerase eg. GO:0001108 bacterial-type RNA polymerase holo enzyme binding.

**Comment by lreiser** [comment]
tair is done

**Comment by krchristie** [comment]
> @pgaudet OK...but coul the definition of that term be changed to make it clear that it includes bacterial-type RNA polymerase. I saw GO:0006357 but didn't think it was appropriate because it appears to be specific for RNA pol II which is a eukaryote-specific term.
> 
> I can see that there are some molecular function terms specific for bacterial-type RNA polymerase eg. GO:0001108 bacterial-type RNA polymerase holo enzyme binding.

@amandamackie - You are correct that there is not a bacterial-type specific term in the regulation branch. The thinking had been that the bacterial species could use the parent term of all the terms representing specific types of DNA-templated RNA polymerase enzymes; my recollection is that this is the approach preferred by Jim Hu and @dsiegele 

I have added a comment to the ontology ticket that @pgaudet created: "**Fix def of GO:0006357 'regulation of transcription by RNA polymerase II' to include bacteria more explicitely #25260**"  https://github.com/geneontology/go-ontology/issues/25260 objecting to the suggestion that the definition of the term "**regulation of transcription by RNA polymerase II**" should be broadened to include bacteria, since it is inappropriate to consider RNAP II to be the parent of bacterial-type RNAP. If we are not going to have the general grouping terms for "**regulation of nucleic acid-templated transcription**" that @pgaudet is planning to obsolete, then I think we will need to have terms explicitly for '**regulation of bacterial-type RNA polymerase**'. Probably worth having comments from @dsiegele on this issue.

**Comment by pgaudet** [comment]
Sorry I typed that too fast. I mean @amandamackie should be using 'regulation of DNA-templated transcription' 

OK ? 

Thanks, Pascale

**Comment by amandamackie** [comment]
Noted and thank you
