### ISSUE TITLE
PTN000325119 GO:0003713 | transcription coactivator activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4554]
* **PTHR ID & PTN node:**

GO:0003713 | transcription coactivator activity | IBA with Q15544 , PTN000325119 | Gaudet P et al. (2011)

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPAC1002.04c
Taf11  ([transcription factor TFIID complex)
I *don't think* this is a  transcription coactivator activity?
I annotated as 
RNA polymerase II general transcription initiation factor activity
so I am filtering this one so let me know if I am wrong.
@pgaudet @colinlog 

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by marcfeuermann** [comment]
I expected some input from the transcription factor task force... Finally I followed your suggestion Val. Removed coactivator and annotated to RNA polymerase II general transcription initiation factor activity.

**Comment by colinlog** [comment]
This is correct. TAF1 is a subunit of the TFIID general transcription factor.

(1) Note that some subunits of TFIID are part of coactivator complexes (but not TAF1). So, it's up to the data in the annotated study: if that shows that a DNA-bound sequence-specific transcription factor (dbTF) is recruiting a protein(complex) to activate or repress a gene  then that protein(complex) has co-activator/co-repressor as it molecular function. 
(2) Furthermore, that recruited protein(complex) may itself recruit proitein(complexes) that are then also coactivators/repressors, because we decided to not enter the 'rabbit hole' of coactivator-coactivators and coreprressor-corepressors. 
(3) Some co-activators/co-repressors are recruited via binding to post-translational modifications of nucleosomal histones or other proteins bound to the target gene-promoter or enhancer. In those cases, although the interaction between the DNA-bound dbTF and the coactivator is not direct, they are deemed to fall under model 2 (at some point a dbTF recruited the chromatin modifier (kinase, acetylase, methyalse) and the epigenetic mark that left behind was read by a co-activator/co-repressor. Because they are carrying out the instructions of a dbTF that was bound to a gene's promoter or enhancer and thus specified that regulatory cis-acting element as the target of the co-activator/co-repressor biochemical activity they can also be assigned the molecular function co-activator/co-repressor. They are carrying out the instructions of a dbTF that was bound to a gene's promoter or enhancer and thus specified that regulatory cis-acting element as the target of the co-activator/co-repressor molecular function.

Finally, the distinction between GTF (every promoter needs the activity every time a RNA olymerase intiiates) and dbTF cofactor (regulatory activity) can be blurry.  Bottom line is that if the experiment shows that a promoter-bound dbTF recruited the activity to one specific gene promoter, then it is a dbTF cofactor GO:0003712/13/14. If the protein(complex) recruitment happens via the core promoter elements (TATA box, initiator, etc) then it is a GTF. Via the other (gene-specific elements) located in the promoter/enhancer, then it is a cofactor.

**Comment by marcfeuermann** [comment]
Thanks Colin for you feedback.
Cheers,
Marc.
