### ISSUE TITLE
Ribonucleoside-diphosphate reductase  is upstream of DNA replication (nuclear/mitochondrial)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4560]
Ribonucleotide reductase does affect DNA replication (nuclear and mitochondrial) but isn't involved directly.

RRM2B | Ribonucleoside-diphosphate reductase subunit M2 B |   | mitochondrial DNA replication |   | ComplexPortal | Homo sapiens | IMP |   | ribonucleoside-diphosphate reductase small chain pthr23409 | protein |   | PMID:17486094 | 20160411
  | RRM1 | Ribonucleoside-diphosphate reductase large subunit |   | mitochondrial DNA replication |   | ComplexPortal | Homo sapiens | IMP

**Comment by PedroRaposo** [comment]
Hello Val,
The GO term GO:0006260 (DNA replication) is coming from UniPathway, and not from a UniRule. I was informed that this resource has been discontinued and that we do not have the ability to change the mapping between "pathway" and "go" because nobody is maintaining this anymore. However, I sent an email to a curator from SIB asking if it would be possible to make some chances, since this resource was crated at SIB.
I'll update this issue once we get news.

**Comment by AndreaAuchincloss** [comment]
Hi Val, 
I have removed this UniPathway from all 178 SP entries, which will hopefully help resolve this. I'll try and figure out who can change UniPathway2GO mapping, which will be even better! I'll update when I have more news...

**Comment by pgaudet** [comment]
I dont find UPA00326 in the ontology- I emailed @alexsign

**Comment by pgaudet** [comment]
Mapping has been removed.
