### ISSUE TITLE
Review annotations to PKC

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4597]
GO:0004698	calcium-dependent protein kinase C activity
GO:0009931	calcium-dependent protein serine/threonine kinase activity
GO:0010857	calcium-dependent protein kinase activity

**Comment by pgaudet** [comment]
Te following mappings will need to be updated 
<html><head></head><body>

GO:0004698 | ec2go | EC:2.7.11.13 > GO:calcium-dependent protein kinase C activity ; GO:0004698
-- | -- | --
 

</body></html>

**Comment by deustp01** [comment]
No change: R-HSA-114683, R-HSA-114684, R-HSA-416639, and R-HSA-421007 already use GO:0004698 "calcium-dependent protein kinase C activity"
Fixed: R-HSA-8986937 and R-HSA-9005561 edited to use GO:0004698 instead of GO:0010857.
These changes will become visible in the September 2023 release of Reactome.
