### ISSUE TITLE
Review annotations to GO:0051482 positive regulation of cytosolic calcium ion concentration involved in phospholipase C-activating G protein-coupled signaling pathway

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4659]
GO:0051482 positive regulation of cytosolic calcium ion concentration involved in phospholipase C-activating G protein-coupled signaling pathway

[#25603 ](https://github.com/geneontology/go-ontology/issues/25603)

The term will be replaced by  GO:0007200 phospholipase C-activating G protein-coupled receptor signaling pathway

**Comment by pgaudet** [comment]
Group | Number of annotations 
-- | --
BHF-UCL | 2
FlyBase | 4
MGI | 3
RGD | 10
UniProt | 24

**Comment by pgaudet** [comment]
If your group has a mechanism for automated replacements, no action is needed.

**Comment by RLovering** [comment]
Hi Pascale
should receptors and ligands be associated with this term or not. Following from our signaling workshop I am assuming this is just the intracellular pathway? But looking at the ontology it from receptor/ligand inwards

For example currently DRD2 is annotated both to positive regulation of the process and to the process https://www.ebi.ac.uk/QuickGO/annotations?goUsage=descendants&goUsageRelationships=is_a,part_of,occurs_in&goId=GO:0007200&taxonId=9606&taxonUsage=descendants&evidenceCode=ECO:0000352&evidenceCodeUsage=descendants&geneProductId=UniProtKB:P14416&geneProductType=protein 

if it is the receptor/ligand plus the intracellular pathway then it would be good to include a statement confirming this eg: The pathway begins with receptor-ligand interaction, and ends with regulation of a downstream cellular process. 
If the term now is just for the intracellular component then the ontology needs to change so that the intracellular term is a parent.

Sorry for not remembering what we discussed for this

Thanks

Ruth

**Comment by pgaudet** [comment]
Hi Ruth, 

You are right: the ligand, the receptor, as well as the members of the intracellular signaling cascade should be annotated to terms that mention the receptor, such as  GO:0007200 phospholipase C-activating G protein-coupled receptor signaling pathway and GO:0060158 phospholipase C-activating dopamine receptor signaling pathway. 

You can also annotate the receptor as 'positively regulating' the PI3K/PKB pathway. 

OK ? 

Thanks, Pascale

**Comment by hattrill** [comment]
FB done.

**Comment by hattrill** [comment]
I might want to check where this pathway ends.

**Comment by gthayman** [comment]
RGD done.

**Comment by RLovering** [comment]
UCL done

**Comment by LiNiMGI** [comment]
MGI done

**Comment by pgaudet** [comment]
Thanks everyone!
