### ISSUE TITLE
Review annotations to some DNA methylation terms on specific residues

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4729]
GO:0090116 | C-5   methylation of cytosine
GO:0032775 | DNA methylation on adenine
GO:0010424 | DNA methylation on cytosine within a   CG sequence
GO:0010426 | DNA methylation on cytosine within a   CHH sequence
GO:0010425 | DNA methylation on cytosine within a   CNG sequence
GO:0032776 | DNA methylation on cytosine
GO:0090124 | N-4 methylation of cytosine

Annotations are here: https://docs.google.com/spreadsheets/d/1GvBHn8ISJJcs5aY716S9_rtv6k-qvT0iE03_0MNSJHc/edit#gid=0

Annotations to regulation terms are here: https://docs.google.com/spreadsheets/d/1vIoh1iIGFg22FdZto1BYHv7UZIuMqzB2N_U-rdbSXFw/edit#gid=0

ARUK-UCL 1 (done)
BHF-UCL 6 (done)
ComplexPortal 8
EcoCyc 3
MGI 15
ParkinsonsUK-UCL 1 (done)
RGD 11
TAIR 22
ZFIN 15
InterPro: 6

**Comment by amandamackie** [comment]
EcoCyc done

**Comment by blazaropinto** [comment]
Thank you for this, all the mentioned entries are updated. Thank you so much for pointing out the case of IPR017127, it is indeed representing a protein methyltransferase and not a DNA one, I updated the GO terms. Also in IPR017198 I updated BP to [GO:0010424: DNA methylation on cytosine within a CG sequence](https://www.ebi.ac.uk/QuickGO/term/GO:0010424).
Best,
Beatriz

**Comment by LiNiMGI** [comment]
Hi @pgaudet, The excel sheet does not include annotations to GO:0006306 DNA methylation. Is there a separate list for annotations to GO:0006306 DNA methylation? according to go-announcements/issues/637, GO:0006306 DNA methylation will also be obsoleted. Thanks,  Li

**Comment by pgaudet** [comment]
Hi @LiNiMGI there are two spreadsheets: 

Methylation: https://docs.google.com/spreadsheets/d/1GvBHn8ISJJcs5aY716S9_rtv6k-qvT0iE03_0MNSJHc/edit#gid=0

Regulation of methylation: https://docs.google.com/spreadsheets/d/1vIoh1iIGFg22FdZto1BYHv7UZIuMqzB2N_U-rdbSXFw/edit#gid=0

**Comment by sandraorchard** [comment]
Complex Portal done

**Comment by LiNiMGI** [comment]
Hi @pgaudet, I found none of the spreadsheets include existing annotations to the GO term "GO:0006306 DNA methylation", thanks.

**Comment by RLovering** [comment]
Hi Pascale

thank you for your helpful instructions about the annotations to create. I am a bit confused about how to revise the annotation for PMID:20820192. DNMT1 P26358, this is a TAS, as I didn't have time to find the expt to support this annotation: GO:0044027 negative regulation of gene expression via CpG island methylation. I agree that 'DNMT1 is not really regulating DNA methylation, it's involved in, since the DNMT1 is constitutively active to maintain the correct state of genome methylation'. However, as you know there are 2 aspects to the term negative regulation of gene expression via CpG island methylation, : 'negative regulation of gene expression' and 'CpG island methylation'. If you are keeping the term GO:0044027 negative regulation of gene expression via CpG island methylation then it is correct to say that DNMT1 is involved in negative regulation of gene expression via CpG island methylation because it is involved in 'CpG island methylation' which then negatively regulates gene expression. Alternatively you could get rid of all the 'negative regulation of gene expression, epigenetic' terms and have for example the term CpG island methylation and then ask curators to add CpG island methylation as a part of AE to negatively regulates gene expression.  

Hope you are OK with this annotations staying as it is, if not let me know and I will follow your new advice

Best

Ruth

**Comment by pgaudet** [comment]
Hi @LiNiMGI 
I dont understand 
- [Methylation spreadsheet](https://docs.google.com/spreadsheets/d/1GvBHn8ISJJcs5aY716S9_rtv6k-qvT0iE03_0MNSJHc/edit#gid=0) has 6 MGI anotations, rows 13-18
- [Regulation spreadsheet ](https://docs.google.com/spreadsheets/d/1vIoh1iIGFg22FdZto1BYHv7UZIuMqzB2N_U-rdbSXFw/edit#gid=0) has 9 MGI annotations, rows 18-26. 
Pascale

**Comment by sramachand** [comment]
ZFIN done

**Comment by pgaudet** [comment]
thanks @blazaropinto 

Sorry I skipped one entry - IPR017198 should be moved to [DNA methylation-dependent heterochromatin formation](http://purl.obolibrary.org/obo/GO_0006346); [GO:0010424: DNA methylation on cytosine within a CG sequence](https://www.ebi.ac.uk/QuickGO/term/GO:0010424). will also be obsoleted. 

Thanks, Pascale

**Comment by pgaudet** [comment]
According to the spreadseet, there are still annotations by 
MGI @LiNiMGI 
RGD  @gthayman 
and TAIR @tberardini

**Comment by blazaropinto** [comment]
Hi Pascale,

Thank you for this. That's updated now. The changes will be available in the next InterPro release.

Best,

Beatriz

**Comment by gthayman** [comment]
RGD done.

**Comment by LiNiMGI** [comment]
MGI done.
