### ISSUE TITLE
Incorrect SL-0039	mapping  for  Q09690 (Pom1 polarity kinase)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4758]
* **UniProt KeyWord (ID and label):**

Pom1 (S. pombe)
GO:0005886	
plasma membrane
IEA with SL-0039	GO_REF:0000044

* **Sequences with problematic annotation (ID + gene/protein name):**
[Q09690](https://www.uniprot.org/uniprot/Q09690)

* **Description of issue**
is not plasma membrane (is cell cortex)

**Comment by ValWood** [comment]
The same applies to the formin  For3
[O94532](https://www.uniprot.org/uniprot/O94532)

**Comment by ValWood** [comment]
and

Byr4
https://www.uniprot.org/uniprotkb/Q10951/entry

Mfm1 (@ 2&3)
https://www.uniprot.org/uniprotkb/P34068/entry

New13
https://www.pombase.org/gene/SPAC4D7.14

Ryh1
https://www.uniprot.org/uniprotkb/P17608/entry

Sle1
https://www.uniprot.org/uniprotkb/O13858/entry
Eisosome filament is part of cortex 

Spo3
https://www.uniprot.org/uniprotkb/Q9US08/entry
Is prospore membranę

Ykt6
Appears to be Golgi

**Comment by Antonialock** [comment]
pom1 I think is ok?

PMID: 21703453

"recombinant Pom1 N-terminus (MBP-Pom11–699) was able to bind directly to several, but not all, negatively charged lipids, namely [phosphatidylserine](https://www.sciencedirect.com/topics/biochemistry-genetics-and-molecular-biology/phosphatidylserine), [phosphatidylinositol phosphates](https://www.sciencedirect.com/topics/biochemistry-genetics-and-molecular-biology/phosphatidylinositol-phosphate), and [cardiolipin](https://www.sciencedirect.com/topics/biochemistry-genetics-and-molecular-biology/cardiolipin) in a protein-lipid overlay assay ([Figure 2](https://www.sciencedirect.com/science/article/pii/S009286741100540X?via%3Dihub#fig2)D). Phosphatidylserine and phosphatidylinositol phosphates are components of the plasma membrane. Cardiolipin is mostly found in the [inner mitochondrial membrane](https://www.sciencedirect.com/topics/biochemistry-genetics-and-molecular-biology/inner-mitochondrial-membrane), and so it is unclear whether this interaction exists in vivo. We also note that, probably due to its high global positive charge (+15.5 for MBP-Pom11–699, +25 for Pom11–699 at pH 7), MBP-Pom11–699 bound the nitrocellulose membrane, resulting in significant background. Together, these experiments suggest that Pom1 directly associates with lipids at the plasma membrane through its basic region."

**Comment by Antonialock** [comment]
Fixed all aside pom1, hope that's ok.

**Comment by ValWood** [comment]
Thanks! I'll annotate pom1 to  "plasma membrane"  with EXP

**Comment by ValWood** [comment]
I still struggle with these, because we can describe the same localization simultaneously as:

i) GO:0106186 | cytoplasmic side of plasma membrane, cell tip
or
ii)  GO:0051285 | cell cortex of cell tip

(i.e the same location can be described as cortex OR membrane)
