### ISSUE TITLE
PTN001732543 regulation or not?

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4812]
* **PTHR ID & PTN node:**

@colinlog  could you sanity check this one?
It's  alp5 https://www.pombase.org/gene/SPBP23A10.08
that actin -like protein which is part of Ino80/NuA4/Swr1 (at least in pombe)
Not regulation? (S. cerevisiae arp4/ human ACTL6A &B

GO:0006357 | regulation of transcription by RNA polymerase II | IBA with arp42 , S000006238 , S000003617 , PTN001732543 , FBgn0025716

* **Sequences with problematic annotation (ID + gene/protein name):**

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by marcfeuermann** [comment]
This is one of the most horrible families to PAINT. I can remove the regulation from the corresponding node and replace it by GO:0006338 chromatin remodeling. But indeed, @colinlog your input would be welcome.

**Comment by colinlog** [comment]
These actin related proteins are essential subunits of the chromatin remodelling complexes they belong to. Chromatin remodelling (nucleosome remodelling) is therefore the generic biochemical/molecular process. 

The biological process is gene expression regulation; a highly homeostatic process that involves (environmental, developmental, intrinsically) programmed gene transcription modulation, most often during the phase that precedes RNA polymerase II pre-initiation complex formation (PIC assembly) at gene promoters, gene enhancers/silencers and chromatin loop anchors (all descendants of SO:0001055 term of the Sequence Ontology http://www.sequenceontology.org/browser/current_release/term/SO:0001055)

The deeper question is: do we go (i) for biochemical process (molecular function, reaction has a substrate and a product, the reaction is performed by multi-subunit protein complexes that work together and/or sequentially on chromatinized DNA) or (ii) for the more abstract biological process which is 'enabling gene expression changes' which is another way of saying 'transcription regulation'.

Since there are examples of dbTFs that directly (physically, through binding) recruit these chromatin remodelling complexes, the regulation branch is invoked via MF dbTF cofactor (GO:0003712). Hence regulation is true. However, it is not always a dbTF that recruits these complexes; sometimes they are recruited by chromatin features, ie; epigenetic signals, that were ultimately installed on nucleosomes by dbTFs and their cofactors, but that remain active in the absence of these 'initial instigating' events. That is the essence of epigenetics.

What about a double annotation? Biological process 'transcription regulation' *and* biochemical process 'chromatin remodelling'.

**Comment by ValWood** [comment]
Can we keep this one until Friday? I'l discuss with Colin and Pascale.  I need to clarify something about the ontology.

**Comment by marcfeuermann** [comment]
Of course it is not urgent in my opinion.

**Comment by ValWood** [comment]
So these complexes have multiple functions.
Their "transcription coregulator" activity, when they act as an adaptor between a DB TF and ???
(which couples to BP  "regulation of transcription from Polymerase II")

Also later during transcription initiation coupled chromatin remodelling (which isn't a regulatory process).
So, I'm happy now that these 2 processes do not both refer to the same role.
