### ISSUE TITLE
PTN000234268 should not transfer to fungi GO:0015039 | NADPH-adrenodoxin reductase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4916]
* **PTHR ID & PTN node:**

GO:0015039 | NADPH-adrenodoxin reductase activity | IBA with P08165 , PTN000234268 , 621648 , S000002784

* **Sequences with problematic annotation (ID + gene/protein name):**

adrenodoxin is a protein not found in fungi (component of steroid hormones), and so this substrate isn't present.

The enzyme is multifunctional and the correct annotations for fungi are probably 

GO:0008860 | ferredoxin-NAD+ reductase activity
and
GO:0004324 | ferredoxin-NADP+ reductase activity
(see pombe IDAs)

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

Annotation error. The experiment supporting uses _S. cerevisiae_ arh1 in a human complementation experiment t, but the MF is not physiologically relevant.
@edwong57

**Comment by ValWood** [comment]
Also is n't

GO:0006744 | ubiquinone biosynthetic process | IBA with S000002784 , PTN000234268
-- | -- | --
[GO:0006744](https://www.pombase.org/term/GO:0006744)	
[ubiquinone biosynthetic process](https://www.pombase.org/term/GO:0006744)
[IBA](http://wiki.geneontology.org/index.php/Inferred_from_Biological_aspect_of_Ancestor_(IBA)) with [S000002784](https://www.yeastgenome.org/search?q=S000002784&is_quick=true) , [PTN000234268](http://www.pantherdb.org/panther/lookupId.jsp?id=PTN000234268)

causally upstream here?

**Comment by marcfeuermann** [comment]
Was also annotated for S. cerevisiae. From PMID:972701
"The Saccharomyces cerevisiae ARH1 gene product (Arh1p) presents homology to mammalian adrenodoxin reductase. We demonstrate the capacity of recombinant Arh1p, made in Escherichia coli, to substitute for its mammalian homologue in ferricyanide, cytochrome c reduction, and, more importantly, in vitro 11beta-hydroxylase assays. ... The biological function of Arh1p remains unknown, and to date, no mitochondrial cytochrome P450 has been identified. ARH1 is, however, essential for yeast viability because an ARH1 gene disruption is lethal not only in aerobic growth conditions but also, surprisingly enough, during fermentation."
It seems indeed not physiological
@srengel, could you please have a look at this ? Thank you.
I've restricted the annotation at the PAINT level.

**Comment by ValWood** [comment]
These annotations are still present, I will raise a taxon restriction for 
[GO:0015039 | NADPH-adrenodoxin reductase activity](https://github.com/geneontology/go-annotation/issues/4916#top)
need to doeble check species distribution. Andredoxin  seems to be present in some fungi, but not pombe or cerevisiae.
