### ISSUE TITLE
Review annotations to GO:0008334 histone mRNA metabolic process GO:0071044 histone mRNA catabolic process

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4995]
Dear all, 

The proposal has been made to obsolete 
GO:0008334 histone mRNA metabolic process 
GO:0071044 histone mRNA catabolic process

> Histone mRNAs end in a conserved stem-loop rather than a poly(A) tail. Degradation of histone mRNAs requires the stem-loop sequence, which binds the stem-loop-binding protein (SLBP), active translation of the histone mRNA, and the location of the stem-loop close to the termination codon.

PMID:18172165

**Comment by deustp01** [comment]
Are there proposed replacement terms? Should we annotate instead to the parent GO:0016071 "mRNA metabolic process"?

On the one hand, we use GO:0008334 to annotate exactly the feature of histone mRNA metabolism that, per the quote above, mechanistically distinguishes histone mRNA metabolism from that of other mRNAs ([R-HSA-7758](https://reactome.org/content/detail/R-HSA-77588)), so the existing term seems useful to distinguish among biologically distinct processes.

On the other, all the differentiating features are captured in our reaction - pathway annotation so there's no information loss, although the resulting assertion, once our annotations are dissected out into atomic GAF entries, that [Q14493 SLBP](https://www.uniprot.org/uniprotkb/Q14493/entry) enables functions involving polyadenylated RNAs seems wrong (because histone mRNA is_a mRNA).

**Comment by deustp01** [comment]
> Does this term work you?

Yes. Reactome fixed; changes will become visible in March 2023 release.

**Comment by pgaudet** [comment]
Awesome!! thanks Peter

**Comment by ValWood** [comment]
End processing and catabolism are different. End processing is maturation.  It looks like histones utilize the stem loop for end processing and catabolism so we might need these terms. I didn't look at all of the catabolism edge cases yet. At the moment I'm only looking at processing (and catabolism via surveillance during transcription).
I'm not against removing the terms per see, but I'm not sure that 
[GO:0006398 mRNA 3'-end processing by stem-loop binding and cleavage](https://amigo.geneontology.org/amigo/term/GO:0006398#display-lineage-tab) will always work as replacement.

**Comment by ValWood** [comment]
OK I looked at the annotations and they all appear to be canonical catabolic pathways so I think it is safe to obsolete.

**Comment by suzialeksander** [comment]
The corresponding go-ontology ticket does not exist
