### ISSUE TITLE
Review annotations to GO:0106163 regulation of exonucleolytic catabolism of deadenylated mRNA

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5088]
Dear all, 

The proposal has been made to obsolete 
GO:1900153 positive regulation of nuclear-transcribed mRNA catabolic process, deadenylation-dependent decay
GO:1900152 negative regulation of nuclear-transcribed mRNA catabolic process, deadenylation-dependent decay
GO:0106163 regulation of exonucleolytic catabolism of deadenylated mRNA
GO:1900151 regulation of nuclear-transcribed mRNA catabolic process, deadenylation-dependent decay

GO TERM ID: GO TERM
see [LINK TO GO-ONTOLOGY TICKET]

Experimental annotations that need to be reviewed are here: 
[LINK TO ANNOTATION REVIEW GOOGLE SPREADSHEET https://docs.google.com/spreadsheets/d/13oNsCNrIDGH26TAKCvpDW2QJXT_0vsR0g4qMKygR_b4]

Impacted groups: 
[LIST GROUPS + NUMBER OF ANNOTATIONS + ADD ASSIGNEES] 

----

Mappings that need to be reviewed: (InterPro2GO, UniProt-Keywords, UniRule) 
[LIST IDs + ADD ASSIGNEES] 

Thanks.

**Comment by RLovering** [comment]
3 UCL annotations changed to mRNA destabilization

**Comment by suzialeksander** [comment]
@ValWood if this is still a valid concern, can you please add ontology tickets, spreadsheet, and assign groups? I currently only see https://github.com/geneontology/go-ontology/issues/27171 where the title does not match the contents of the ticket, nor does that PR obsolete the remaining terms in this ticket.

Otherwise this ticket is only 1/4 done..

[GO:1900151](https://www.ebi.ac.uk/QuickGO/term/GO:1900151) 	regulation of nuclear-transcribed mRNA catabolic process, deadenylation-dependent decay 	
[GO:1900153](https://www.ebi.ac.uk/QuickGO/term/GO:1900153) 	positive regulation of nuclear-transcribed mRNA catabolic process, deadenylation-dependent decay 	
[GO:1900152](https://www.ebi.ac.uk/QuickGO/term/GO:1900152) 	negative regulation of nuclear-transcribed mRNA catabolic process, deadenylation-dependent decay 	
~~[GO:0106163](https://www.ebi.ac.uk/QuickGO/term/GO:0106163) 	obsolete regulation of exonucleolytic catabolism of deadenylated mRNA~~

**Comment by ValWood** [comment]
This one should have been closed already, not actioned
