### ISSUE TITLE
Review annotations to ncRNA terms GO:0110008 GO:0097064 GO:0034660 GO:0034470 GO:0098781  GO:0071029 GO:0071046 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5124]
Dear all, 

The proposal has been made to obsolete 

GO:0034471 ncRNA 5'-end processing No direct annotations (children have been rehoused)
GO_0034661 ncRNA catabolic process No direct annotations (children will be rehoused)

GO:0110008 ncRNA deadenylation 
GO:0097064 ncRNA export from nucleus 
GO:0034660 ncRNA metabolic process 
GO:0034470 ncRNA processing 
GO:0098781 ncRNA transcription 
GO:0071029 nuclear ncRNA surveillance 
GO:0071046 nuclear polyadenylation dependent ncRNA catabolic process

see https://github.com/geneontology/go-ontology/issues/26761

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1t5WuDDftR3XXI6ZHfBey3TIPLU_Ub5crKH1xfKviV-U/edit#gid=0

Impacted groups: 

Impacted groups: 
   2 BHF-UCL	GO:0110008 @RLovering removed but would have prefered to have changed to lncRNA deadenylation
   1 EcoCyc	GO:0034470 @keseler 
   3 MGI	GO:0098781 @LiNiMGI 
   1 PomBase	GO:0034470 @ValWood 
   2 PomBase	GO:0071029 @ValWood 
   3 PomBase	GO:0071046 @ValWood 
   2 SGD	GO:0097064 @suzialeksander 
   2 SGD	GO:0098781 @suzialeksander 
   2 TAIR	GO:0034470 @lreiser 
   ~2 UniProt	GO:0034470 @Antonialock~
   1 WB	GO:0034470 @vanaukenk 
   2 WB	GO:0034660 @vanaukenk 

----

Mappings that need to be reviewed: (InterPro2GO, UniProt-Keywords, UniRule) 
InterPro:IPR033688 RNA cytidine acetyltransferase NAT10 > GO:ncRNA processing ; GO:0034470

Thanks.

**Comment by ValWood** [comment]
Also 4 uses in extensions 
3 PomBAse
1 ARUK-UK

**Comment by RLovering** [comment]
Hi Val

what annotations have these IDs in the AE? or whick term is it and I can look it up

Thanks

Ruth

**Comment by ValWood** [comment]
Hi Ruth, yours is:

ARUK-UCL	UniProtKB:P10276	RARA	PMID:21131358		GO:0045944	positive regulation of transcription by RNA polymerase II	IDA			PANTHER:PTHR24082	20210108	GO:0098781|RNAcentral:URS00000AF93C_9606	NCBITaxon:9606

**Comment by ValWood** [comment]
@RLovering For the 2 you removed, I think they should be

GO:0180035  lncRNA processing
so it would be:

GO:0004535 poly(A)-specific ribonuclease activity GO:0004535 has_input "telomerase RNA" part_of GO:0180035  lncRNA processing
(the deadenylase is captured by the MF so it doesn't need to be captured by the process)

**Comment by blazaropinto** [comment]
Thank you,

I removed this term and added GO:1904812 to this entry. The changes will be available in InterPro 100.0.

Best,

Beatriz

**Comment by vanaukenk** [comment]
Hi - Noting here that WB annotations were already updated in Protein2GO on 2024-02-13, but since the annotation review pipeline checks what is in the latest GO release, we don't have the most up-to-date information about curation status.

From 2024-03-26 annotation call discussion with @pgaudet we agree that it would be much better to access the curation databases for annotation reviews so that ontology editors and curators aren't re-reviewing work that's already been done.

**Comment by Antonialock** [comment]
uniprot fixed

**Comment by RLovering** [comment]
Thanks Val - changes made as suggested Ruth

**Comment by LiNiMGI** [comment]
MGI done

**Comment by lreiser** [comment]
tair done

**Comment by suzialeksander** [comment]
GO:0071046 has no ontology ticket, is still a current term. @ValWood is this intentional or was that term meant to be obsoleted? 
      
The current status of terms from this ticket:
~~[GO:0071029](https://www.ebi.ac.uk/QuickGO/term/GO:0071029) 	obsolete nuclear ncRNA surveillance~~
[GO:0071046](https://www.ebi.ac.uk/QuickGO/term/GO:0071046) 	nuclear polyadenylation-dependent ncRNA catabolic process 	
~~[GO:0110008](https://www.ebi.ac.uk/QuickGO/term/GO:0110008) 	obsolete ncRNA deadenylation 	
[GO:0098781](https://www.ebi.ac.uk/QuickGO/term/GO:0098781) 	obsolete ncRNA transcription 	
[GO:0097064](https://www.ebi.ac.uk/QuickGO/term/GO:0097064) 	obsolete ncRNA export from nucleus 	
[GO:0034660](https://www.ebi.ac.uk/QuickGO/term/GO:0034660) 	obsolete ncRNA metabolic process 	
[GO:0034471](https://www.ebi.ac.uk/QuickGO/term/GO:0034471) 	obsolete ncRNA 5'-end processing 	
[GO:0034470](https://www.ebi.ac.uk/QuickGO/term/GO:0034470) 	obsolete ncRNA processing~~

**Comment by suzialeksander** [comment]
InterPro:IPR033688 RNA cytidine acetyltransferase NAT10 > GO:ncRNA processing ; GO:0034470 

Can you fix this @blazaropinto, that GO is obsolete

**Comment by ValWood** [comment]
[GO:0071046](https://www.ebi.ac.uk/QuickGO/term/GO:0071046) nuclear polyadenylation-dependent ncRNA catabolic process was intentional, catabolic processes not dealt with yet.

**Comment by blazaropinto** [comment]
Hi Suzie,

This term is no longer mapped since the InterPro 100.0 http://www.ebi.ac.uk/interpro/entry/InterPro/IPR033688/ (I can see above I dealt with that before :) ).

Best,
Beatriz
