### ISSUE TITLE
Complex Portal annotations in P2GO have 'located_in' relation

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#5183]
Hi

Looks like most/all Complex Portal annotations to complexes are getting a 'located_in' relation instead of 'part_of' relation in P2GO.
E.g. see annotations for PMID:11713534

I mentioned this to Sandra a few months ago - she checked with JuanJo, who said:
> As far as I know, we don’t add these on export. I’ve checked the goa intact file we generate on release, and I cannot find any mention of ‘located_in’ in it.

So maybe a problem with the P2GO/GOA import?

**Comment by sandraorchard** [comment]
Answer from Alex "This is the issue with Complex Portal data decomposition. I believe the discussion dated couple of years back, and at that time Birgit and GOC people agreed to use 'located_in' for all members of a complex which become individual GO annotations. I'm running this pipeline in GOA unchanged since then. I understand now GOC trying to make all relations to 'part_of' if it's GO annotated to children of 'protein contain complex'. Last month I've made this change in Protein2GO, but not to complex decomposition pipeline. I'm going make changes shortly, but it will take time to propagate this to GOA release and to the QuickGO."

**Comment by pgaudet** [comment]
Discussed this one with Alex, he is changing the code, this will be fixed at the next release (December). 

@sjm41 Should we close this? or do you want to confirm that you see these changes implemented?

**Comment by sjm41** [comment]
Happy to close if we know it's in hand.
