### ISSUE TITLE
regulation of cell cycle IEA InterPro:IPR026907

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5247]
* **InterPro ID / label**

CCNDBP1  aka GCIP

regulation of cell cycle IEA InterPro:IPR026907
derives from a single 2000 publication, only cited once
https://pubmed.ncbi.nlm.nih.gov/10801854/

UniProt does not annotate this to GO but only states
"May negatively regulate cell cycle progression. May act at least in part via inhibition of the cyclin-D1/CDK4 complex, thereby preventing phosphorylation of RB1 and blocking E2F-dependent transcription.:

the experiments aren't really convincing (an overexpression which could cause cell cycle blocks)

I don't think there is enough info to annotatate "regulation of" or even "cell cycle" from this single publication

* **Example sequences with problematic annotation (ID + gene/protein name):**

* **Description of issue**

**Comment by blazaropinto** [comment]
Hi Val,

Thank you very much for that. I've been looking into this entry and updating the description according to PMIDs 35160302, 15887118 and 34631521, which I've added
I think this GO term https://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0051726 may have stayed there because it's related to "tumor suppressor" (as per QuickGO), but you are right it doesn't seem specific enough. I've removed it. I am not sure if there is a better one I can add to this entry, do you have any idea?

Thanks again,
Beatriz

**Comment by ValWood** [comment]
I agree, I would class as "unknown" there is no good data for this family (at least curated)

**Comment by ValWood** [comment]
I will dig into this some more, i see some indicators to splicing, and DNA damage response, will follow up later and let you know.

**Comment by blazaropinto** [comment]
Thank you Val :) I'll close this ticket for now then. The changes mentioned above will be available in InterPro 101.0.

Best,
Beatriz
