### ISSUE TITLE
Review annotations to GO:0099004 calmodulin dependent kinase signaling pathway 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#5286]
Proposal for obsoletion: https://github.com/geneontology/go-ontology/issues/28158

GO:0099004 calmodulin dependent kinase signaling pathway 

Annotations are here: https://docs.google.com/spreadsheets/d/1rwKOsbM-n14xtySUcyJB8hQxTMc1SxKh4EVsTNmBhlI/edit?gid=0#gid=0

**Comment by pgaudet** [comment]
1 MGI
1 RGD
1 SynGO

**Comment by LiNiMGI** [comment]
MGI done.

**Comment by ftwkoopmans** [comment]
I'm note sure why I'm tagged for this; what is needed from the SynGO consortium?

Looking at the linked Google sheet I see CAMK2A annotated against a GO term that does not look like a SynGO annotation to me. i.e. if I look at our current dataset (release 1.2, uploaded to GO in december 2023) I find these annotations for this protein:

| SynGO ID | GO domain | GO term |
| --- | ---------------------- | -------------------------------------------- |
| 887 | Cellular Component | postsynaptic cytosol (GO:0099524) |
| 889 | Cellular Component | postsynaptic density (GO:0014069) |
| 886 | Cellular Component | presynaptic cytosol (GO:0099523) |
| 2075 | Biological Process	regulation of neurotransmitter receptor localization to postsynaptic specialization membrane (GO:0098696) |
| 981 | Biological Process | regulation of synaptic vesicle docking (GO:0099148) |

**Comment by pgaudet** [comment]
Hi @ftwkoopmans 

In GO we see an annotation to this term: https://amigo.geneontology.org/amigo/gene_product/RGD:2261
<img width="856" alt="image" src="https://github.com/geneontology/go-annotation/assets/4782928/2ebb36c1-60aa-4fca-ae15-c4db9577191b">


Is this not in your data set anymore?

**Comment by ftwkoopmans** [comment]
In my previous post I listed all current annotations in SynGO 1.2 for CAMK2A, the annotation/screenshot you posted is not in that table. If I go through all the JSON's that we uploaded at https://github.com/geneontology/syngo2lego_data_conversion , I cannot find the GO ID 0099004 anywhere (also not in previous release JSON's).

Perhaps you can backtrack where that annotation comes from / from what data source it was imported? It just occurred to me that we made some annotations in protein2go just after the GO training. This is a long time ago; we were making a bunch of annotations in protein2go to learn more about GO and explore edge-cases while annotating an initial set of proteins. This was even before we got the consortium-wide annotation efforts started, I think 8 years ago. Soon after, we launched a simplified annotation tool tailored to the SynGO consortium (this is the tooling that also produces the JSON's with annotation data that we share).

All proteins that we annotated in protein2go during this initial SynGO test phase should also be part of the latest SynGO release, so that 8 year old data has been superseded. I'm pretty sure all our protein2go annotations from ~8 years ago can be safely deleted and that is probably the origin of this specific annotation. If you can email a table of `gene symbol * GO term * annotation extension` for all "SynGO protein2go annotations" I will review these to confirm. Not sure when I'll have time though, could take a few weeks before I get around to this if the list is long.


ps. For clarity, only the latest set of SynGO annotations that we upload as JSON should be part of GO. We upload our complete collection of curated annotations through the syngo2lego_data_conversion repository with each SynGO release.

**Comment by pgaudet** [comment]
OK will do!

**Comment by pgaudet** [comment]
Discussing aith @alexsign , he will delete these annotations from P2GO (98 annotations total were originally entered).

**Comment by gthayman** [comment]
RGD done.

**Comment by gthayman** [comment]
RGD done

**Comment by suzialeksander** [comment]
Term was obsoleted.
