### ISSUE TITLE
Review annotations to GO:0070528 protein kinase C signaling & related 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#5325]
This ticket is for the review of GO:0007205 protein kinase C-activating G protein-coupled receptor signaling pathway

and
GO:0070528 protein kinase C signaling
GO:0090036 regulation of protein kinase C signaling
GO:0090038 negative regulation of protein kinase C signaling
GO:0090037 positive regulation of protein kinase C signaling

Note that there are 2 review Google sheets: one for GO:0007205 protein kinase C-activating G protein-coupled receptor signaling pathway and one for GO:0070528 protein kinase C signaling & children.

**Comment by pgaudet** [comment]
**GO:0007205 protein kinase C-activating G protein-coupled receptor signaling pathway**

MGI 2
RGD 10
UniProt 6

Obsoletion notice: https://github.com/geneontology/go-ontology/issues/28414

**Comment by pgaudet** [comment]
**For GO:0070528 protein kinase C signaling
GO:0090036 regulation of protein kinase C signaling
GO:0090038 negative regulation of protein kinase C signaling
GO:0090037 positive regulation of protein kinase C signaling**

It looks like annotations are either: 
- GO:0007205 protein kinase C-activating G protein-coupled receptor signaling pathway (or a child)
- GO:0141212 phospholipase C/protein kinase C signal transduction
- NTR positive regulation of phospholipase C/protein kinase C signal transduction
- activation of PKC without a known mechanism; annotations to be removed or changed to 'GO:0035556 intracellular signal transduction'


- 6 BHF
- 1 CGD
- 12 MGI
- 7 RGD
- 14 SGD
- 24 UniProt
- 7 WB

Thanks, 
Pascale

**Comment by jlewsmith** [comment]
CGD done

**Comment by LiNiMGI** [comment]
MGI done.

**Comment by vanaukenk** [comment]
I've removed the C. elegans annotations and didn't re-annotate to 'intracellular signal transduction' because I don't think that conveys the same information we were trying to capture with the 'negative regulation of protein kinase C signaling' annotations.  

The paper describes genetic interactions between members of the PKA signaling pathway and pkc-3 in early embryo development, and while the mechanism is not studied in this paper, the conclusion of the genetic analysis is: "These results implicate a previously unknown negative crosstalk between the PKA signalling pathway and PKC-3 function."

I may try to capture this with genetic interaction curation at WB, instead.

**Comment by srengel** [comment]
SGD done.

**Comment by RLovering** [comment]
UCL done

**Comment by Antonialock** [comment]
uniprot done

**Comment by vanaukenk** [comment]
@pgaudet 
The original annotations we had for this ticket were IGI annotations that were intended to capture that there seems to be some form (likely regulatory, but no mechanistic details were given) of cross-talk between members of the PKA signaling pathway and a protein kinase C signaling pathway.

While it is true that some of the genes in those annotations are members of a PKA signaling pathway, that's not what the original intent of the annotations was, so I think we're better off capturing the results of those experiments as genetic interactions in WB.

**Comment by gthayman** [comment]
RGD done.
