### ISSUE TITLE
PKA regulatory subunit maps to 'kinase activity'  in spkw2go

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#541]
The cAMP-dependent protein kinase regulatory subunit alpha b in ZFIN (prkar2ab) is mapped via spkw2go (SP_KW:KW-0418) to GO:0016301 'kinase activity'.  The regulatory subunits of protein kinase A (in any species) do not have kinase activity themselves...they regulate the kinase activity inherent in the PKA catalytic subunits.  

The proper mapping might be 'regulation of kinase activity' (GO:0043549)

-Doug

Reported by: doughowe

Original Ticket: "geneontology/annotation-issues/541":https://sourceforge.net/p/geneontology/annotation-issues/541

**Comment by mcourtot** [comment]
@rachhuntley: this is a very old ticket - ok to close?

**Comment by rachhuntley** [comment]
No, this one also needs to go back to UniProt as Q6NW93 still has two GO annotations derived from KW-0418.

**Comment by vanaukenk** [comment]
@sylvainpoux - I am unassigning @rachhuntley from this ticket and re-assigning it to you.  It looks like association of KW-0418 with Q6NW93 is still producing incorrect annotations.  

Thx.

**Comment by sylvainpoux** [comment]
Well, this is a TrEMBL entry and, unfortunately, I cannot do anything because the error is coming from the submitter (EMBL:AAH67676.1). 

There are 2 options here: Michele or George could contact ENA/EMBL and ask them to remove this annotation. The other option would be to integrate this entry in Swiss-Prot, but this is against our curation policy, since we only manually curate experimentally characterized proteins.

@magrane @ggeorghiou what is your opinion?

Thanks

Sylvain

**Comment by magrane** [comment]
Wow, this one has been hanging around for a long time! I don't think there's an error in the nucleotide submission. The protein is correctly called a kinase regulatory subunit in ENA although the way it is annotated (Protein kinase, cAMP-dependent, regulatory, type II, alpha, B) seems to be causing problems for the program which creates TrEMBL entries from ENA records. The program adds keywords based on information in the nucleotide records and seems to be adding the 'Kinase' keyword based on the protein name. The 'Kinase' keyword is mapped to the 'kinase activity' GO terms which produces the incorrect GO annotation. I'll pass this on to the developers here and see if anything can be done to improve the program so that the keyword is not added if the protein name also contains "regulatory". Will report back once the developers have looked into this.

**Comment by sylvainpoux** [comment]
Thanks Michele

**Comment by ValWood** [comment]
https://www.uniprot.org/uniprotkb/Q6NW93/ "kinase"  annotation is removed, closing
